.\" $Id: pdfopt.1 8022 2007-06-05 22:23:38Z giles $
.\" Using encoding of the German (de_DE) translation: ISO-8859-1
.\" Translation by Tobias Burnus <burnus@gmx.de> and Thomas Hoffmann
.TH PDFOPT 1 "8.Juli 2002" 7.21 "Ghostscript-Werkzeuge" \" -*- nroff -*-
.SH NAME
pdfopt \- Ghostscript-PDF-Optimierer
.SH SYNTAX
\fBpdfopt\fR [ \fIOptionen\fR ] \fIEingabe.pdf Ausgabe.pdf\fR
.SH BESCHREIBUNG
\fBpdfopt\fR benutzt \fBgs\fR(1), um die Adobe \fBPortable Document
Format\fR (PDF) Datei "Eingabe.pdf" in sogenannter optimierter Form nach
"Ausgabe.pdf" zu schreiben.  Optimierung platziert die Elemente der Datei in eine linearere 
Reihenfolge und fügt Verweiszeiger hinzu, die es Adobes
Acrobat(TM) Produkten erlaubt, einzelne Seiten der Datei schneller
darzustellen, wenn auf die Datei über ein Netzwerk zugegriffen wird.
.PP
Hinweis: Eingabe.pdf und Ausgabe.pdf dürfen nicht gleich sein. Falls Sie es
sind, wird die Datei vermutlich zerstört. \fBpdfopt\fR verhindert dies
gegenwärtig nicht.
.SH DATEIEN
Starten Sie "\fBgs -h\fR" um den Ort der Ghostscript-Dokumentation auf Ihrem System zu 
ermitteln, wo Sie weitere Datails finden.
.SH SIEHE AUCH
"Linearized PDF" in Adobes PDF-Referenzhandbuch
http://partners.adobe.com/asn/developer/acrosdk/DOCS/pdfspec.pdf
.SH VERSION
Dies Dokument wurde zuletzt für Ghostscript version 7.21 durchgesehen.
.SH AUTOR
Artifex Software, Inc. sind die
Hauptautoren of Ghostscript.
