#pragma once
#include "../PPTXShape.h"

namespace OOXMLShapes
{
	class CActionButtonSound : public CPPTXShape
	{
		public:
			CActionButtonSound()
			{
				LoadFromXML(
					_T("<ooxml-shape>")
					_T("<gdLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<gd name=\"dx2\" fmla=\"*/ ss 3 8\" />")
					  _T("<gd name=\"g9\" fmla=\"+- vc 0 dx2\" />")
					  _T("<gd name=\"g10\" fmla=\"+- vc dx2 0\" />")
					  _T("<gd name=\"g11\" fmla=\"+- hc 0 dx2\" />")
					  _T("<gd name=\"g12\" fmla=\"+- hc dx2 0\" />")
					  _T("<gd name=\"g13\" fmla=\"*/ ss 3 4\" />")
					  _T("<gd name=\"g14\" fmla=\"*/ g13 1 8\" />")
					  _T("<gd name=\"g15\" fmla=\"*/ g13 5 16\" />")
					  _T("<gd name=\"g16\" fmla=\"*/ g13 5 8\" />")
					  _T("<gd name=\"g17\" fmla=\"*/ g13 11 16\" />")
					  _T("<gd name=\"g18\" fmla=\"*/ g13 3 4\" />")
					  _T("<gd name=\"g19\" fmla=\"*/ g13 7 8\" />")
					  _T("<gd name=\"g20\" fmla=\"+- g9 g14 0\" />")
					  _T("<gd name=\"g21\" fmla=\"+- g9 g15 0\" />")
					  _T("<gd name=\"g22\" fmla=\"+- g9 g17 0\" />")
					  _T("<gd name=\"g23\" fmla=\"+- g9 g19 0\" />")
					  _T("<gd name=\"g24\" fmla=\"+- g11 g15 0\" />")
					  _T("<gd name=\"g25\" fmla=\"+- g11 g16 0\" />")
					  _T("<gd name=\"g26\" fmla=\"+- g11 g18 0\" />")
					_T("</gdLst>")
					_T("<cxnLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<cxn ang=\"0\">")
						_T("<pos x=\"r\" y=\"vc\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"cd4\">")
						_T("<pos x=\"hc\" y=\"b\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"cd2\">")
						_T("<pos x=\"l\" y=\"vc\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"3cd4\">")
						_T("<pos x=\"hc\" y=\"t\" />")
					  _T("</cxn>")
					_T("</cxnLst>")
					_T("<rect l=\"l\" t=\"t\" r=\"r\" b=\"b\" xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\" />")
					_T("<pathLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<path stroke=\"false\" extrusionOk=\"false\">")
						_T("<moveTo>")
						  _T("<pt x=\"l\" y=\"t\" />")
						_T("</moveTo>")
						_T("<lnTo>")
						  _T("<pt x=\"r\" y=\"t\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"r\" y=\"b\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"l\" y=\"b\" />")
						_T("</lnTo>")
						_T("<close />")
						_T("<moveTo>")
						  _T("<pt x=\"g11\" y=\"g21\" />")
						_T("</moveTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g11\" y=\"g22\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g24\" y=\"g22\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g25\" y=\"g10\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g25\" y=\"g9\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g24\" y=\"g21\" />")
						_T("</lnTo>")
						_T("<close />")
					  _T("</path>")
					  _T("<path stroke=\"false\" fill=\"darken\" extrusionOk=\"false\">")
						_T("<moveTo>")
						  _T("<pt x=\"g11\" y=\"g21\" />")
						_T("</moveTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g11\" y=\"g22\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g24\" y=\"g22\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g25\" y=\"g10\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g25\" y=\"g9\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g24\" y=\"g21\" />")
						_T("</lnTo>")
						_T("<close />")
					  _T("</path>")
					  _T("<path fill=\"none\" extrusionOk=\"false\">")
						_T("<moveTo>")
						  _T("<pt x=\"g11\" y=\"g21\" />")
						_T("</moveTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g24\" y=\"g21\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g25\" y=\"g9\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g25\" y=\"g10\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g24\" y=\"g22\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g11\" y=\"g22\" />")
						_T("</lnTo>")
						_T("<close />")
						_T("<moveTo>")
						  _T("<pt x=\"g26\" y=\"g21\" />")
						_T("</moveTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g12\" y=\"g20\" />")
						_T("</lnTo>")
						_T("<moveTo>")
						  _T("<pt x=\"g26\" y=\"vc\" />")
						_T("</moveTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g12\" y=\"vc\" />")
						_T("</lnTo>")
						_T("<moveTo>")
						  _T("<pt x=\"g26\" y=\"g22\" />")
						_T("</moveTo>")
						_T("<lnTo>")
						  _T("<pt x=\"g12\" y=\"g23\" />")
						_T("</lnTo>")
					  _T("</path>")
					  _T("<path fill=\"none\">")
						_T("<moveTo>")
						  _T("<pt x=\"l\" y=\"t\" />")
						_T("</moveTo>")
						_T("<lnTo>")
						  _T("<pt x=\"r\" y=\"t\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"r\" y=\"b\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"l\" y=\"b\" />")
						_T("</lnTo>")
						_T("<close />")
					  _T("</path>")
					_T("</pathLst>")
					_T("</ooxml-shape>")
				);
			}
	};
}