#pragma once
#include "../PPTXShape.h"

namespace OOXMLShapes
{
	class CNonIsoscelesTrapezoid : public CPPTXShape
	{
		public:
			CNonIsoscelesTrapezoid()
			{
				LoadFromXML(
					_T("<ooxml-shape>")
					_T("<avLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<gd name=\"adj1\" fmla=\"val 25000\" />")
					  _T("<gd name=\"adj2\" fmla=\"val 25000\" />")
					_T("</avLst>")
					_T("<gdLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<gd name=\"maxAdj\" fmla=\"*/ 50000 w ss\" />")
					  _T("<gd name=\"a1\" fmla=\"pin 0 adj1 maxAdj\" />")
					  _T("<gd name=\"a2\" fmla=\"pin 0 adj2 maxAdj\" />")
					  _T("<gd name=\"x1\" fmla=\"*/ ss a1 200000\" />")
					  _T("<gd name=\"x2\" fmla=\"*/ ss a1 100000\" />")
					  _T("<gd name=\"dx3\" fmla=\"*/ ss a2 100000\" />")
					  _T("<gd name=\"x3\" fmla=\"+- r 0 dx3\" />")
					  _T("<gd name=\"x4\" fmla=\"+/ r x3 2\" />")
					  _T("<gd name=\"il\" fmla=\"*/ wd3 a1 maxAdj\" />")
					  _T("<gd name=\"adjm\" fmla=\"max a1 a2\" />")
					  _T("<gd name=\"it\" fmla=\"*/ hd3 adjm maxAdj\" />")
					  _T("<gd name=\"irt\" fmla=\"*/ wd3 a2 maxAdj\" />")
					  _T("<gd name=\"ir\" fmla=\"+- r 0 irt\" />")
					_T("</gdLst>")
					_T("<ahLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<ahXY gdRefX=\"adj1\" minX=\"0\" maxX=\"maxAdj\">")
						_T("<pos x=\"x2\" y=\"t\" />")
					  _T("</ahXY>")
					  _T("<ahXY gdRefX=\"adj2\" minX=\"0\" maxX=\"maxAdj\">")
						_T("<pos x=\"x3\" y=\"t\" />")
					  _T("</ahXY>")
					_T("</ahLst>")
					_T("<cxnLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<cxn ang=\"0\">")
						_T("<pos x=\"x4\" y=\"vc\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"cd4\">")
						_T("<pos x=\"hc\" y=\"b\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"cd2\">")
						_T("<pos x=\"x1\" y=\"vc\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"3cd4\">")
						_T("<pos x=\"hc\" y=\"t\" />")
					  _T("</cxn>")
					_T("</cxnLst>")
					_T("<rect l=\"il\" t=\"it\" r=\"ir\" b=\"b\" xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\" />")
					_T("<pathLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<path>")
						_T("<moveTo>")
						  _T("<pt x=\"l\" y=\"b\" />")
						_T("</moveTo>")
						_T("<lnTo>")
						  _T("<pt x=\"x2\" y=\"t\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"x3\" y=\"t\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"r\" y=\"b\" />")
						_T("</lnTo>")
						_T("<close />")
					  _T("</path>")
					_T("</pathLst>")
					_T("</ooxml-shape>")
				);
			}
	};
}