#pragma once
#include "../PPTXShape.h"

namespace OOXMLShapes
{
	class CParallelogram : public CPPTXShape
	{
		public:
			CParallelogram()
			{
				LoadFromXML(
					_T("<ooxml-shape>")
					_T("<avLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<gd name=\"adj\" fmla=\"val 25000\" />")
					_T("</avLst>")
					_T("<gdLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<gd name=\"maxAdj\" fmla=\"*/ 100000 w ss\" />")
					  _T("<gd name=\"a\" fmla=\"pin 0 adj maxAdj\" />")
					  _T("<gd name=\"x1\" fmla=\"*/ ss a 200000\" />")
					  _T("<gd name=\"x2\" fmla=\"*/ ss a 100000\" />")
					  _T("<gd name=\"x6\" fmla=\"+- r 0 x1\" />")
					  _T("<gd name=\"x5\" fmla=\"+- r 0 x2\" />")
					  _T("<gd name=\"x3\" fmla=\"*/ x5 1 2\" />")
					  _T("<gd name=\"x4\" fmla=\"+- r 0 x3\" />")
					  _T("<gd name=\"il\" fmla=\"*/ wd2 a maxAdj\" />")
					  _T("<gd name=\"q1\" fmla=\"*/ 5 a maxAdj\" />")
					  _T("<gd name=\"q2\" fmla=\"+/ 1 q1 12\" />")
					  _T("<gd name=\"il\" fmla=\"*/ q2 w 1\" />")
					  _T("<gd name=\"it\" fmla=\"*/ q2 h 1\" />")
					  _T("<gd name=\"ir\" fmla=\"+- r 0 il\" />")
					  _T("<gd name=\"ib\" fmla=\"+- b 0 it\" />")
					  _T("<gd name=\"q3\" fmla=\"*/ h hc x2\" />")
					  _T("<gd name=\"y1\" fmla=\"pin 0 q3 h\" />")
					  _T("<gd name=\"y2\" fmla=\"+- b 0 y1\" />")
					_T("</gdLst>")
					_T("<ahLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<ahXY gdRefX=\"adj\" minX=\"0\" maxX=\"maxAdj\">")
						_T("<pos x=\"x2\" y=\"t\" />")
					  _T("</ahXY>")
					_T("</ahLst>")
					_T("<cxnLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<cxn ang=\"3cd4\">")
						_T("<pos x=\"hc\" y=\"y2\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"3cd4\">")
						_T("<pos x=\"x4\" y=\"t\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"0\">")
						_T("<pos x=\"x6\" y=\"vc\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"cd4\">")
						_T("<pos x=\"x3\" y=\"b\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"cd4\">")
						_T("<pos x=\"hc\" y=\"y1\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"cd2\">")
						_T("<pos x=\"x1\" y=\"vc\" />")
					  _T("</cxn>")
					_T("</cxnLst>")
					_T("<rect l=\"il\" t=\"it\" r=\"ir\" b=\"ib\" xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\" />")
					_T("<pathLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<path>")
						_T("<moveTo>")
						  _T("<pt x=\"l\" y=\"b\" />")
						_T("</moveTo>")
						_T("<lnTo>")
						  _T("<pt x=\"x2\" y=\"t\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"r\" y=\"t\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"x5\" y=\"b\" />")
						_T("</lnTo>")
						_T("<close />")
					  _T("</path>")
					_T("</pathLst>")
					_T("</ooxml-shape>")
				);
			}
	};
}