#pragma once
#include "../PPTXShape.h"

namespace OOXMLShapes
{
	class CRound2DiagRect : public CPPTXShape
	{
		public:
			CRound2DiagRect()
			{
				LoadFromXML(
					_T("<ooxml-shape>")
					_T("<avLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<gd name=\"adj1\" fmla=\"val 16667\" />")
					  _T("<gd name=\"adj2\" fmla=\"val 0\" />")
					_T("</avLst>")
					_T("<gdLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<gd name=\"a1\" fmla=\"pin 0 adj1 50000\" />")
					  _T("<gd name=\"a2\" fmla=\"pin 0 adj2 50000\" />")
					  _T("<gd name=\"x1\" fmla=\"*/ ss a1 100000\" />")
					  _T("<gd name=\"y1\" fmla=\"+- b 0 x1\" />")
					  _T("<gd name=\"a\" fmla=\"*/ ss a2 100000\" />")
					  _T("<gd name=\"x2\" fmla=\"+- r 0 a\" />")
					  _T("<gd name=\"y2\" fmla=\"+- b 0 a\" />")
					  _T("<gd name=\"dx1\" fmla=\"*/ x1 29289 100000\" />")
					  _T("<gd name=\"dx2\" fmla=\"*/ a 29289 100000\" />")
					  _T("<gd name=\"d\" fmla=\"+- dx1 0 dx2\" />")
					  _T("<gd name=\"dx\" fmla=\"?: d dx1 dx2\" />")
					  _T("<gd name=\"ir\" fmla=\"+- r 0 dx\" />")
					  _T("<gd name=\"ib\" fmla=\"+- b 0 dx\" />")
					_T("</gdLst>")
					_T("<ahLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<ahXY gdRefX=\"adj1\" minX=\"0\" maxX=\"50000\">")
						_T("<pos x=\"x1\" y=\"t\" />")
					  _T("</ahXY>")
					  _T("<ahXY gdRefX=\"adj2\" minX=\"0\" maxX=\"50000\">")
						_T("<pos x=\"x2\" y=\"t\" />")
					  _T("</ahXY>")
					_T("</ahLst>")
					_T("<cxnLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<cxn ang=\"0\">")
						_T("<pos x=\"r\" y=\"vc\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"cd4\">")
						_T("<pos x=\"hc\" y=\"b\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"cd2\">")
						_T("<pos x=\"l\" y=\"vc\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"3cd4\">")
						_T("<pos x=\"hc\" y=\"t\" />")
					  _T("</cxn>")
					_T("</cxnLst>")
					_T("<rect l=\"dx\" t=\"dx\" r=\"ir\" b=\"ib\" xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\" />")
					_T("<pathLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<path>")
						_T("<moveTo>")
						  _T("<pt x=\"x1\" y=\"t\" />")
						_T("</moveTo>")
						_T("<lnTo>")
						  _T("<pt x=\"x2\" y=\"t\" />")
						_T("</lnTo>")
						_T("<arcTo wR=\"a\" hR=\"a\" stAng=\"3cd4\" swAng=\"cd4\" />")
						_T("<lnTo>")
						  _T("<pt x=\"r\" y=\"y1\" />")
						_T("</lnTo>")
						_T("<arcTo wR=\"x1\" hR=\"x1\" stAng=\"0\" swAng=\"cd4\" />")
						_T("<lnTo>")
						  _T("<pt x=\"a\" y=\"b\" />")
						_T("</lnTo>")
						_T("<arcTo wR=\"a\" hR=\"a\" stAng=\"cd4\" swAng=\"cd4\" />")
						_T("<lnTo>")
						  _T("<pt x=\"l\" y=\"x1\" />")
						_T("</lnTo>")
						_T("<arcTo wR=\"x1\" hR=\"x1\" stAng=\"cd2\" swAng=\"cd4\" />")
						_T("<close />")
					  _T("</path>")
					_T("</pathLst>")
					_T("</ooxml-shape>")
				);
			}
	};
}