#pragma once
#include "../PPTXShape.h"

namespace OOXMLShapes
{
	class CStar5 : public CPPTXShape
	{
		public:
			CStar5()
			{
				LoadFromXML(
					_T("<ooxml-shape>")
					_T("<avLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<gd name=\"adj\" fmla=\"val 19098\" />")
					  _T("<gd name=\"hf\" fmla=\"val 105146\" />")
					  _T("<gd name=\"vf\" fmla=\"val 110557\" />")
					_T("</avLst>")
					_T("<gdLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<gd name=\"a\" fmla=\"pin 0 adj 50000\" />")
					  _T("<gd name=\"swd2\" fmla=\"*/ wd2 hf 100000\" />")
					  _T("<gd name=\"shd2\" fmla=\"*/ hd2 vf 100000\" />")
					  _T("<gd name=\"svc\" fmla=\"*/ vc  vf 100000\" />")
					  _T("<gd name=\"dx1\" fmla=\"cos swd2 1080000\" />")
					  _T("<gd name=\"dx2\" fmla=\"cos swd2 18360000\" />")
					  _T("<gd name=\"dy1\" fmla=\"sin shd2 1080000\" />")
					  _T("<gd name=\"dy2\" fmla=\"sin shd2 18360000\" />")
					  _T("<gd name=\"x1\" fmla=\"+- hc 0 dx1\" />")
					  _T("<gd name=\"x2\" fmla=\"+- hc 0 dx2\" />")
					  _T("<gd name=\"x3\" fmla=\"+- hc dx2 0\" />")
					  _T("<gd name=\"x4\" fmla=\"+- hc dx1 0\" />")
					  _T("<gd name=\"y1\" fmla=\"+- svc 0 dy1\" />")
					  _T("<gd name=\"y2\" fmla=\"+- svc 0 dy2\" />")
					  _T("<gd name=\"iwd2\" fmla=\"*/ swd2 a 50000\" />")
					  _T("<gd name=\"ihd2\" fmla=\"*/ shd2 a 50000\" />")
					  _T("<gd name=\"sdx1\" fmla=\"cos iwd2 20520000\" />")
					  _T("<gd name=\"sdx2\" fmla=\"cos iwd2 3240000\" />")
					  _T("<gd name=\"sdy1\" fmla=\"sin ihd2 3240000\" />")
					  _T("<gd name=\"sdy2\" fmla=\"sin ihd2 20520000\" />")
					  _T("<gd name=\"sx1\" fmla=\"+- hc 0 sdx1\" />")
					  _T("<gd name=\"sx2\" fmla=\"+- hc 0 sdx2\" />")
					  _T("<gd name=\"sx3\" fmla=\"+- hc sdx2 0\" />")
					  _T("<gd name=\"sx4\" fmla=\"+- hc sdx1 0\" />")
					  _T("<gd name=\"sy1\" fmla=\"+- svc 0 sdy1\" />")
					  _T("<gd name=\"sy2\" fmla=\"+- svc 0 sdy2\" />")
					  _T("<gd name=\"sy3\" fmla=\"+- svc ihd2 0\" />")
					  _T("<gd name=\"yAdj\" fmla=\"+- svc 0 ihd2\" />")
					_T("</gdLst>")
					_T("<ahLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<ahXY gdRefY=\"adj\" minY=\"0\" maxY=\"50000\">")
						_T("<pos x=\"hc\" y=\"yAdj\" />")
					  _T("</ahXY>")
					_T("</ahLst>")
					_T("<cxnLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<cxn ang=\"3cd4\">")
						_T("<pos x=\"hc\" y=\"t\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"cd2\">")
						_T("<pos x=\"x1\" y=\"y1\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"cd4\">")
						_T("<pos x=\"x2\" y=\"y2\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"cd4\">")
						_T("<pos x=\"x3\" y=\"y2\" />")
					  _T("</cxn>")
					  _T("<cxn ang=\"0\">")
						_T("<pos x=\"x4\" y=\"y1\" />")
					  _T("</cxn>")
					_T("</cxnLst>")
					_T("<rect l=\"sx1\" t=\"sy1\" r=\"sx4\" b=\"sy3\" xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\" />")
					_T("<pathLst xmlns=\"http://schemas.openxmlformats.org/drawingml/2006/main\">")
					  _T("<path>")
						_T("<moveTo>")
						  _T("<pt x=\"x1\" y=\"y1\" />")
						_T("</moveTo>")
						_T("<lnTo>")
						  _T("<pt x=\"sx2\" y=\"sy1\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"hc\" y=\"t\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"sx3\" y=\"sy1\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"x4\" y=\"y1\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"sx4\" y=\"sy2\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"x3\" y=\"y2\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"hc\" y=\"sy3\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"x2\" y=\"y2\" />")
						_T("</lnTo>")
						_T("<lnTo>")
						  _T("<pt x=\"sx1\" y=\"sy2\" />")
						_T("</lnTo>")
						_T("<close />")
					  _T("</path>")
					_T("</pathLst>")
					_T("</ooxml-shape>")
				);
			}
	};
}