// AVSImageShellConverter.idl : IDL source for AVSImageShellConverter
//

// This file will be processed by the MIDL tool to
// produce the type library (AVSImageShellConverter.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(907848C4-E268-45e1-AD3E-1C1E5E78A93D),
	dual,
	nonextensible,
	helpstring("IImageShellConverter Interface"),
	pointer_default(unique)
]
interface IImageShellConverter : IDispatch{
};
[
	uuid(D26F2572-4858-4564-96A6-6E0DBFA59D77),
	version(1.0),
	helpstring("AVSImageShellConverter 1.0 Type Library")
]
library AVSImageShellConverterLib
{
	importlib("stdole2.tlb");
	[
		uuid(556A0934-8517-4814-9578-55BA6AFCEA94),
		helpstring("ImageShellConverter Class")
	]
	coclass ImageShellConverter
	{
		[default] interface IImageShellConverter;
	};
};
