/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class docbuilder_utils_Utils */

#ifndef _Included_docbuilder_utils_Utils
#define _Included_docbuilder_utils_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     docbuilder_utils_Utils
 * Method:    addToPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_docbuilder_utils_Utils_addToPath
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
