#!/bin/sh
# $Id: ps2pdf12 8107 2007-07-05 19:04:29Z till $
# Convert PostScript to PDF 1.2 (Acrobat 3-and-later compatible).
ps2pdfwr="`dirname $0`/ps2pdfwr"
if test ! -x "$ps2pdfwr"; then
	ps2pdfwr="ps2pdfwr"
fi
exec "$ps2pdfwr" -dCompatibilityLevel=1.2 "$@"
