#!/bin/sh
# $Id: ps2pdf 8107 2007-07-05 19:04:29Z till $
# Convert PostScript to PDF.

# Currently, we produce PDF 1.4 by default, but this is not guaranteed
# not to change in the future.
version=14

ps2pdf="`dirname $0`/ps2pdf$version"
if test ! -x "$ps2pdf"; then
	ps2pdf="ps2pdf$version"
fi
exec "$ps2pdf" "$@"
