#pragma once
#ifndef OOX_INCLUDE_H_
#define OOX_INCLUDE_H_

#include "Folder.h"
#include "Logic\Table.h"
#include "Logic\Sdt.h"
#include "Logic\BookmarkStart.h"
#include "Logic\BookmarkEnd.h"
#include "Logic\List.h"
#include "Logic\Text.h"
#include "Logic\Symbol.h"
#include "Logic\Tab.h"
#include "Logic\Break.h"
#include "Logic\Pict.h"
#include "Logic\Drawing.h"
#include "Logic\Inline.h"
#include "Logic\FootnoteReference.h"
#include "Logic\EndnoteReference.h"
#include "Logic\FootnoteRef.h"
#include "Logic\EndnoteRef.h"
#include "Logic\Separator.h"
#include "Logic\ContinuationSeparator.h"
#include "Logic\FldChar.h"
#include "Logic\InstrText.h"
#include "Logic\DelText.h"
#include "Logic\NullRun.h"
#include "Logic\ColorsTable.h"


#include "FileTypes.h"
#include "App.h"
#include "Core.h"
#include "Document.h"
#include "FontTable.h"
#include "Numbering.h"
#include "Styles.h"
#include "Settings/File.h"
#include "FootNote.h"
#include "EndNote.h"
#include "WebSettings.h"
#include "External\HyperLink.h"
#include "Media/Media.h"
#include "Header.h"
#include "Footer.h"
#include "Theme/File.h"

#endif // OOX_INCLUDE_H_