//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASCOfficeEWSEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASCOfficeEWSEditor.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;border&gt;&lt;left /&gt;&lt;right /&gt;&lt;top /&gt;&lt;bottom /&gt;&lt;diagonal /&gt;&lt;/border&gt;
        ///
        ///.
        /// </summary>
        internal static string default_border {
            get {
                return ResourceManager.GetString("default_border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fill&gt;&lt;patternFill patternType=&quot;none&quot;/&gt;&lt;/fill&gt;.
        /// </summary>
        internal static string default_fill {
            get {
                return ResourceManager.GetString("default_fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;font&gt;&lt;sz val=&quot;11&quot;/&gt;&lt;color auto=&quot;1&quot;/&gt;&lt;name val=&quot;Calibri&quot;/&gt;&lt;family val=&quot;2&quot;/&gt;&lt;charset val=&quot;204&quot;/&gt;&lt;/font&gt;.
        /// </summary>
        internal static string default_font {
            get {
                return ResourceManager.GetString("default_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;c:chartSpace xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; xmlns:c=&quot;http://schemas.openxmlformats.org/drawingml/2006/chart&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot;&gt;
        ///  &lt;c:lang val=&quot;en-US&quot;/&gt;
        ///  &lt;c:chart&gt;
        ///    &lt;c:title&gt;
        ///      &lt;c:layout/&gt;
        ///      &lt;c:tx&gt;
        ///        &lt;c:rich&gt;
        ///          &lt;a:bodyPr/&gt;
        ///          &lt;a:lstStyle/&gt;
        ///          &lt;a:p&gt;
        ///            &lt;a:pPr&gt;
        ///              &lt;a:defRPr/&gt;
        ///            &lt;/a:pPr&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string empty_areaChart {
            get {
                return ResourceManager.GetString("empty_areaChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;c:chartSpace xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; xmlns:c=&quot;http://schemas.openxmlformats.org/drawingml/2006/chart&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot;&gt;
        ///  &lt;c:lang val=&quot;en-US&quot;/&gt;
        ///  &lt;c:chart&gt;
        ///    &lt;c:title&gt;
        ///      &lt;c:tx&gt;
        ///        &lt;c:rich&gt;
        ///          &lt;a:bodyPr /&gt;
        ///          &lt;a:lstStyle /&gt;
        ///          &lt;a:p&gt;
        ///            &lt;a:pPr&gt;
        ///              &lt;a:defRPr /&gt;
        ///            &lt;/a:pPr&gt;
        ///            &lt;a:r&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string empty_barChart {
            get {
                return ResourceManager.GetString("empty_barChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;root&gt;
        ///	&lt;dir name=&quot;xl&quot;&gt;
        ///		&lt;file name=&quot;styles.xml&quot;&gt;
        ///			&lt;styleSheet xmlns=&quot;http://schemas.openxmlformats.org/spreadsheetml/2006/main&quot;&gt;
        ///				&lt;fonts count=&quot;1&quot;&gt;
        ///					&lt;font&gt;
        ///						&lt;sz val=&quot;11&quot;/&gt;
        ///						&lt;color auto=&quot;1&quot;/&gt;
        ///						&lt;name val=&quot;Arial&quot;/&gt;
        ///					&lt;/font&gt;
        ///				&lt;/fonts&gt;
        ///				&lt;fills count=&quot;2&quot;&gt;
        ///					&lt;fill&gt;
        ///						&lt;patternFill patternType=&quot;none&quot;/&gt;
        ///					&lt;/fill&gt;
        ///					&lt;fill&gt;
        ///						&lt;patternFill patternType=&quot;gray125&quot;/&gt;
        ///					&lt;/fill&gt;
        ///				&lt;/fills&gt;
        ///				&lt;borders count=&quot;1&quot;&gt;
        ///					&lt;border&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string empty_book {
            get {
                return ResourceManager.GetString("empty_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;c:chartSpace xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; xmlns:c=&quot;http://schemas.openxmlformats.org/drawingml/2006/chart&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot;&gt;
        ///  &lt;c:lang val=&quot;en-US&quot;/&gt;
        ///  &lt;c:chart&gt;
        ///    &lt;c:title&gt;
        ///      &lt;c:layout/&gt;
        ///      &lt;c:tx&gt;
        ///        &lt;c:rich&gt;
        ///          &lt;a:bodyPr/&gt;
        ///          &lt;a:lstStyle/&gt;
        ///          &lt;a:p&gt;
        ///            &lt;a:pPr&gt;
        ///              &lt;a:defRPr/&gt;
        ///            &lt;/a:pPr&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string empty_bubbleChart {
            get {
                return ResourceManager.GetString("empty_bubbleChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;xdr:wsDr xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot; xmlns:xdr=&quot;http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing&quot;&gt;
        ///  &lt;xdr:twoCellAnchor editAs=&quot;oneCell&quot;&gt;
        ///    &lt;xdr:from&gt;
        ///      &lt;xdr:col&gt;0&lt;/xdr:col&gt;
        ///      &lt;xdr:colOff&gt;0&lt;/xdr:colOff&gt;
        ///      &lt;xdr:row&gt;0&lt;/xdr:row&gt;
        ///      &lt;xdr:rowOff&gt;0&lt;/xdr:rowOff&gt;
        ///    &lt;/xdr:from&gt;
        ///    &lt;xdr:to&gt;
        ///      &lt;xdr:col&gt;0&lt;/xd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string empty_chartDrawing {
            get {
                return ResourceManager.GetString("empty_chartDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot; ?&gt;
        ///&lt;c:seriesItem xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; xmlns:c=&quot;http://schemas.openxmlformats.org/drawingml/2006/chart&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot;&gt;
        ///  &lt;c:pt idx=&quot;0&quot;&gt;
        ///    &lt;c:v&gt;0&lt;/c:v&gt;
        ///  &lt;/c:pt&gt;
        ///&lt;/c:seriesItem&gt;
        ///.
        /// </summary>
        internal static string empty_chartSeriesItem {
            get {
                return ResourceManager.GetString("empty_chartSeriesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;c:chartSpace xmlns:c=&quot;http://schemas.openxmlformats.org/drawingml/2006/chart&quot; xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot;&gt;
        ///  &lt;c:date1904 val=&quot;0&quot;/&gt;
        ///  &lt;c:lang val=&quot;en-US&quot;/&gt;
        ///  &lt;c:roundedCorners val=&quot;0&quot;/&gt;
        ///  &lt;mc:AlternateContent xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;&gt;
        ///    &lt;mc:Choice Requires=&quot;c14&quot; xmlns:c14=&quot;http://schemas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string empty_doughnutChart {
            get {
                return ResourceManager.GetString("empty_doughnutChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot; ?&gt;
        ///  &lt;xdr:wsDr xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot; xmlns:xdr=&quot;http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing&quot;&gt;
        ///    &lt;xdr:twoCellAnchor editAs=&quot;oneCell&quot;&gt;
        ///      &lt;xdr:from&gt;
        ///      &lt;xdr:col&gt;0&lt;/xdr:col&gt;
        ///      &lt;xdr:colOff&gt;0&lt;/xdr:colOff&gt;
        ///      &lt;xdr:row&gt;0&lt;/xdr:row&gt;
        ///      &lt;xdr:rowOff&gt;0&lt;/xdr:rowOff&gt;
        ///    &lt;/xdr:from&gt;
        ///      &lt;xdr:to&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string empty_imageDrawing {
            get {
                return ResourceManager.GetString("empty_imageDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;c:chartSpace xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; xmlns:c=&quot;http://schemas.openxmlformats.org/drawingml/2006/chart&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot;&gt;
        ///  &lt;c:lang val=&quot;en-US&quot;/&gt;
        ///  &lt;c:chart&gt;
        ///    &lt;c:title&gt;
        ///      &lt;c:layout/&gt;
        ///      &lt;c:tx&gt;
        ///        &lt;c:rich&gt;
        ///          &lt;a:bodyPr/&gt;
        ///          &lt;a:lstStyle/&gt;
        ///          &lt;a:p&gt;
        ///            &lt;a:pPr&gt;
        ///              &lt;a:defRPr/&gt;
        ///            &lt;/a:pPr&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string empty_lineChart {
            get {
                return ResourceManager.GetString("empty_lineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;c:chartSpace xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; xmlns:c=&quot;http://schemas.openxmlformats.org/drawingml/2006/chart&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot;&gt;
        ///  &lt;c:lang val=&quot;en-US&quot;/&gt;
        ///  &lt;c:chart&gt;
        ///    &lt;c:title&gt;
        ///      &lt;c:layout/&gt;
        ///      &lt;c:tx&gt;
        ///        &lt;c:rich&gt;
        ///          &lt;a:bodyPr/&gt;
        ///          &lt;a:lstStyle/&gt;
        ///          &lt;a:p&gt;
        ///            &lt;a:pPr&gt;
        ///              &lt;a:defRPr/&gt;
        ///            &lt;/a:pPr&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string empty_pieChart {
            get {
                return ResourceManager.GetString("empty_pieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;c:chartSpace xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; xmlns:c=&quot;http://schemas.openxmlformats.org/drawingml/2006/chart&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot;&gt;
        ///  &lt;c:lang val=&quot;en-US&quot;/&gt;
        ///  &lt;c:chart&gt;
        ///    &lt;c:title&gt;
        ///      &lt;c:layout/&gt;
        ///      &lt;c:tx&gt;
        ///        &lt;c:rich&gt;
        ///          &lt;a:bodyPr/&gt;
        ///          &lt;a:lstStyle/&gt;
        ///          &lt;a:p&gt;
        ///            &lt;a:pPr&gt;
        ///              &lt;a:defRPr/&gt;
        ///            &lt;/a:pPr&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string empty_radarChart {
            get {
                return ResourceManager.GetString("empty_radarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;c:chartSpace xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; xmlns:c=&quot;http://schemas.openxmlformats.org/drawingml/2006/chart&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot;&gt;
        ///  &lt;c:lang val=&quot;en-US&quot;/&gt;
        ///  &lt;c:chart&gt;
        ///    &lt;c:title&gt;
        ///      &lt;c:layout/&gt;
        ///      &lt;c:tx&gt;
        ///        &lt;c:rich&gt;
        ///          &lt;a:bodyPr/&gt;
        ///          &lt;a:lstStyle/&gt;
        ///          &lt;a:p&gt;
        ///            &lt;a:pPr&gt;
        ///              &lt;a:defRPr/&gt;
        ///            &lt;/a:pPr&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string empty_scatterChart {
            get {
                return ResourceManager.GetString("empty_scatterChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;worksheet xmlns=&quot;http://schemas.openxmlformats.org/spreadsheetml/2006/main&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot;&gt;
        ///	&lt;dimension ref=&quot;A1&quot;/&gt;
        ///	&lt;sheetViews&gt;
        ///		&lt;sheetView workbookViewId=&quot;0&quot;/&gt;
        ///	&lt;/sheetViews&gt;
        ///	&lt;sheetFormatPr defaultRowHeight=&quot;15&quot;/&gt;
        ///	&lt;sheetData/&gt;
        ///	&lt;pageMargins left=&quot;0.7&quot; right=&quot;0.7&quot; top=&quot;0.75&quot; bottom=&quot;0.75&quot; header=&quot;0.3&quot; footer=&quot;0.3&quot;/&gt;
        ///&lt;/worksheet&gt;
        ///.
        /// </summary>
        internal static string empty_sheet {
            get {
                return ResourceManager.GetString("empty_sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;c:chartSpace xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; xmlns:c=&quot;http://schemas.openxmlformats.org/drawingml/2006/chart&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot;&gt;
        ///  &lt;c:lang val=&quot;en-US&quot;/&gt;
        ///  &lt;c:chart&gt;
        ///    &lt;c:title&gt;
        ///      &lt;c:layout/&gt;
        ///      &lt;c:tx&gt;
        ///        &lt;c:rich&gt;
        ///          &lt;a:bodyPr/&gt;
        ///          &lt;a:lstStyle/&gt;
        ///          &lt;a:p&gt;
        ///            &lt;a:pPr&gt;
        ///              &lt;a:defRPr/&gt;
        ///            &lt;/a:pPr&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string empty_stockChart {
            get {
                return ResourceManager.GetString("empty_stockChart", resourceCulture);
            }
        }
    }
}
