/*
 * (c) Copyright Ascensio System SIA 2010-2019
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation. In accordance with
 * Section 7(a) of the GNU AGPL its Section 15 shall be amended to the effect
 * that Ascensio System SIA expressly excludes the warranty of non-infringement
 * of any third-party rights.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For
 * details, see the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA at 20A-12 Ernesta Birznieka-Upisha
 * street, Riga, Latvia, EU, LV-1050.
 *
 * The  interactive user interfaces in modified source and object code versions
 * of the Program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU AGPL version 3.
 *
 * Pursuant to Section 7(b) of the License you must retain the original Product
 * logo when distributing the program. Pursuant to Section 7(e) we decline to
 * grant you any rights under trademark law for use of our trademarks.
 *
 * All the Product's GUI elements, including illustrations and icon sets, as
 * well as technical writing content are licensed under the terms of the
 * Creative Commons Attribution-ShareAlike 4.0 International. See the License
 * terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 */
#pragma once

#include <string>


namespace PPT {

enum RecordType : unsigned short
{
    RT_NONE,
    RT_Document                             = 0x03E8,
    RT_DocumentAtom,
    RT_EndDocumentAtom,
    RT_Slide                                = 0x03EE,
    RT_SlideAtom,
    RT_Notes,
    RT_NotesAtom,
    RT_Environment,
    RT_SlidePersistAtom,
    RT_MainMaster                           = 0x03F8,
    RT_SlideShowSlideInfoAtom,
    RT_SlideViewInfo,
    RT_GuideAtom,
    RT_ViewInfoAtom                         = 0x03FD,
    RT_SlideViewInfoAtom,
    RT_VbaInfo,
    RT_VbaInfoAtom,
    RT_SlideShowDocInfoAtom,
    RT_Summary,
    RT_DocRoutingSlipAtom                   = 0x0406,
    RT_OutlineViewInfo,
    RT_SorterViewInfo,
    RT_ExternalObjectList,
    RT_ExternalObjectListAtom,
    RT_DrawingGroup,
    RT_Drawing,
    RT_GridSpacing10Atom,
    RT_RoundTripTheme12Atom,
    RT_RoundTripColorMapping12Atom,
    RT_NamedShows,
    RT_NamedShow,
    RT_NamedShowSlidesAtom,
    RT_NotesTextViewInfo9,
    RT_NormalViewSetInfo9,
    RT_NormalViewSetInfo9Atom,
    RT_RoundTripOriginalMainMasterId12Atom  = 0x041C,
    RT_RoundTripCompositeMasterId12Atom,
    RT_RoundTripContentMasterInfo12Atom,
    RT_RoundTripShapeId12Atom,
    RT_RoundTripHFPlaceholder12Atom,
    RT_RoundTripContentMasterId12Atom       = 0x0422,
    RT_RoundTripOArtTextStyles12Atom,
    RT_RoundTripHeaderFooterDefaults12Atom,
    RT_RoundTripDocFlags12Atom,
    RT_RoundTripShapeCheckSumForCL12Atom,
    RT_RoundTripNotesMasterTextStyles12Atom,
    RT_RoundTripCustomTableStyles12Atom,
    RT_List                                 = 0x07D0,
    RT_FontCollection                       = 0x07D5,
    RT_FontCollection10,
    RT_BookmarkCollection                   = 0x07E3,
    RT_SoundCollection,
    RT_SoundCollectionAtom,
    RT_Sound,
    RT_SoundDataBlob,
    RT_BookmarkSeedAtom                     = 0x07E9,
    RT_ColorSchemeAtom                      = 0x07F0,
    RT_BlipCollection9                      = 0x07F8,
    RT_BlipEntity9Atom,
    RT_ExternalObjectRefAtom                = 0x0BC1,
    RT_PlaceholderAtom                      = 0x0BC3,
    RT_ShapeAtom                            = 0x0BDB,
    RT_ShapeFlags10Atom,
    RT_RoundTripNewPlaceholderId12Atom,
    RT_OutlineTextRefAtom                   = 0x0F9E,
    RT_TextHeaderAtom,
    RT_TextCharsAtom,
    RT_StyleTextPropAtom,
    RT_MasterTextPropAtom,
    RT_TextMasterStyleAtom,
    RT_TextCharFormatExceptionAtom,
    RT_TextParagraphFormatExceptionAtom,
    RT_TextRulerAtom,
    RT_TextBookmarkAtom,
    RT_TextBytesAtom,
    RT_TextSpecialInfoDefaultAtom,
    RT_TextSpecialInfoAtom,
    RT_DefaultRulerAtom,
    RT_StyleTextProp9Atom,
    RT_TextMasterStyle9Atom,
    RT_OutlineTextProps9,
    RT_OutlineTextPropsHeader9Atom,
    RT_TextDefaults9Atom,
    RT_StyleTextProp10Atom,
    RT_TextMasterStyle10Atom,
    RT_OutlineTextProps10,
    RT_TextDefaults10Atom,
    RT_OutlineTextProps11,
    RT_StyleTextProp11Atom,
    RT_FontEntityAtom,
    RT_FontEmbedDataBlob,
    RT_CString                              = 0x0FBA,
    RT_MetaFile                             = 0x0FC1,
    RT_ExternalOleObjectAtom                = 0x0FC3,
    RT_Kinsoku                              = 0x0FC8,
    RT_Handout,
    RT_ExternalOleEmbed                     = 0x0FCC,
    RT_ExternalOleEmbedAtom,
    RT_ExternalOleLink,
    RT_BookmarkEntityAtom                   = 0x0FD0,
    RT_ExternalOleLinkAtom,
    RT_KinsokuAtom,
    RT_ExternalHyperlinkAtom,
    RT_ExternalHyperlink                    = 0x0FD7,
    RT_SlideNumberMetaCharAtom,
    RT_HeadersFooters,
    RT_HeadersFootersAtom,
    RT_TextInteractiveInfoAtom              = 0x0FDF,
    RT_ExternalHyperlink9                   = 0x0FE4,
    RT_RecolorInfoAtom                      = 0x0FE7,
    RT_ExternalOleControl                   = 0x0FEE,
    RT_SlideListWithText                    = 0x0FF0,
    RT_AnimationInfoAtom,
    RT_InteractiveInfo,
    RT_InteractiveInfoAtom,
    RT_UserEditAtom                         = 0x0FF5,
    RT_CurrentUserAtom,
    RT_DateTimeMetaCharAtom,
    RT_GenericDateMetaCharAtom,
    RT_HeaderMetaCharAtom,
    RT_FooterMetaCharAtom,
    RT_ExternalOleControlAtom,
    RT_ExternalMediaAtom                    = 0x1004,
    RT_ExternalVideo,
    RT_ExternalAviMovie,
    RT_ExternalMciMovie,
    RT_ExternalMidiAudio                    = 0x100D,
    RT_ExternalCdAudio,
    RT_ExternalWavAudioEmbedded,
    RT_ExternalWavAudioLink,
    RT_ExternalOleObjectStg,
    RT_ExternalCdAudioAtom,
    RT_ExternalWavAudioEmbeddedAtom,
    RT_AnimationInfo,
    RT_RtfDateTimeMetaCharAtom,
    RT_ExternalHyperlinkFlagsAtom           = 0x1018,
    RT_ProgTags                             = 0x1388,
    RT_ProgStringTag,
    RT_ProgBinaryTag,
    RT_BinaryTagDataBlob,
    RT_PrintOptionsAtom                     = 0x1770,
    RT_PersistDirectoryAtom                 = 0x1772,
    RT_PresentationAdvisorFlags9Atom        = 0x177A,
    RT_HtmlDocInfo9Atom,
    RT_HtmlPublishInfoAtom,
    RT_HtmlPublishInfo9,
    RT_BroadcastDocInfo9,
    RT_BroadcastDocInfo9Atom,
    RT_EnvelopeFlags9Atom                   = 0x1784,
    RT_EnvelopeData9Atom,
    RT_VisualShapeAtom                      = 0x2AFB,
    RT_HashCodeAtom                         = 0x2B00,
    RT_VisualPageAtom,
    RT_BuildList,
    RT_BuildAtom,
    RT_ChartBuild,
    RT_ChartBuildAtom,
    RT_DiagramBuild,
    RT_DiagramBuildAtom,
    RT_ParaBuild,
    RT_ParaBuildAtom,
    RT_LevelInfoAtom,
    RT_RoundTripAnimationAtom12Atom,
    RT_RoundTripAnimationHashAtom12Atom     = 0x2B0D,
    RT_Comment10                            = 0x2EE0,
    RT_Comment10Atom,
    RT_CommentIndex10                       = 0x2EE4,
    RT_CommentIndex10Atom,
    RT_LinkedShape10Atom,
    RT_LinkedSlide10Atom,
    RT_SlideFlags10Atom                     = 0x2EEA,
    RT_SlideTime10Atom,
    RT_DiffTree10,
    RT_Diff10,
    RT_Diff10Atom,
    RT_SlideListTableSize10Atom,
    RT_SlideListEntry10Atom,
    RT_SlideListTable10,
    RT_CryptSession10Container              = 0x2F14,
    RT_FontEmbedFlags10Atom                 = 0x32C8,
    RT_FilterPrivacyFlags10Atom             = 0x36B0,
    RT_DocToolbarStates10Atom,
    RT_PhotoAlbumInfo10Atom,
    RT_SmartTagStore11Container,
    RT_RoundTripSlideSyncInfo12             = 0x3714,
    RT_RoundTripSlideSyncInfoAtom12,


    RTE_DGG_CONTAINER =         0xF000,
    RTE_BSTORE_CONTAINER =      0xF001,
    RTE_DG_CONTAINER =          0xF002,
    RTE_SPGR_CONTAINER =        0xF003,
    RTE_SP_CONTAINER =          0xF004,
    RTE_SOLVERCONTAINER =       0xF005,
    RTE_DGG =                   0xF006,
    RTE_BSE =                   0xF007,
    RTE_DG =                    0xF008,
    RTE_SPGR =                  0xF009,
    RTE_SP =                    0xF00A,
    RTE_OPT =                   0xF00B,
    RTE_TEXTBOX =               0xF00C,
    RTE_CLIENTTEXTBOX =         0xF00D,
    RTE_ANCHOR =                0xF00E,
    RTE_CHILDANCHOR =           0xF00F,
    RTE_CLIENTANCHOR =          0xF010,
    RTE_CLIENTDATA =            0xF011,
    RTE_CONNECTORRULE =         0xF012,
    RTE_ALIGNRULE =             0xF013,
    RTE_ARCRULE =               0xF014,
    RTE_CLIENTRULE =            0xF015,
    RTE_CLSID =                 0xF016,
    RTE_CALLOUTRULE =           0xF017,
    RTE_BLIP_START =            0xF018,


    RTE_BLIP_EMF =              0xF01A,
    RTE_BLIP_WMF =              0xF01B,
    RTE_BLIP_PICT =             0xF01C,
    RTE_BLIP_JPEG =             0xF01D,
    RTE_BLIP_PNG =              0xF01E,
    RTE_BLIP_DIB =              0xF01F,


    RTE_BLIP_END =              0xF117,
    RTE_REGROUPITEMS =          0xF118,
    RTE_SELECTION =             0xF119,


    RTE_COLORMRU =              0xF11A,
    RTE_DELETEDPSPL =           0xF11D,
    RTE_SPLITMENUCOLORS =       0xF11E,
    RTE_OLEOBJECT =             0xF11F,
    RTE_COLORSCHEME =           0xF120,
    RTE_SECONDARY_OPT =         0xF121,
    RTE_TETRIARY_OPT =          0xF122,
    RTE_BLIP_TIFF =             0xF029,




    RT_TimeConditionContainer               = 0xF125,
    RT_TimeNode                             = 0xF127,
    RT_TimeCondition,
    RT_TimeModifier,
    RT_TimeBehaviorContainer,
    RT_TimeAnimateBehaviorContainer,
    RT_TimeColorBehaviorContainer,
    RT_TimeEffectBehaviorContainer,
    RT_TimeMotionBehaviorContainer,
    RT_TimeRotationBehaviorContainer,
    RT_TimeScaleBehaviorContainer,
    RT_TimeSetBehaviorContainer,
    RT_TimeCommandBehaviorContainer,
    RT_TimeBehavior,
    RT_TimeAnimateBehavior,
    RT_TimeColorBehavior,
    RT_TimeEffectBehavior,
    RT_TimeMotionBehavior,
    RT_TimeRotationBehavior,
    RT_TimeScaleBehavior,
    RT_TimeSetBehavior,
    RT_TimeCommandBehavior,
    RT_TimeClientVisualElement,
    RT_TimePropertyList,
    RT_TimeVariantList,
    RT_TimeAnimationValueList,
    RT_TimeIterateData,
    RT_TimeSequenceData,
    RT_TimeVariant,
    RT_TimeAnimationValue,
    RT_TimeExtTimeNodeContainer,
    RT_TimeSubEffectContainer
};


//std::string GetRecordName(RecordType dwType);
}
