// Add C includes here

#if defined __cplusplus

// Add C++ includes here


#include <string>
#include <vector>
#include <sstream>
#include <map>
#include <iostream>
#include <list>
#include <iosfwd>
#include <algorithm>
#include <stack>
#include <memory>
#include <cassert>
#include <fstream>
#include <queue>
#include <locale>
#include <functional>
#include <bitset>
#include <ostream>
#include <boost/shared_ptr.hpp>
#include "../XlsFormat/Logic/Biff_records/AreaFormat.h"
#include "../XlsFormat/Logic/Biff_records/Axis.h"
#include "../XlsFormat/Logic/Biff_records/Begin.h"
#include "../XlsFormat/Logic/Biff_records/BiffRecord.h"
#include "../XlsFormat/Logic/Biff_records/BiffRecordContinued.h"
#include "../XlsFormat/Logic/Biff_records/BOF.h"
#include "../XlsFormat/Logic/Biff_records/CatSerRange.h"
#include "../XlsFormat/Logic/Biff_records/CFEx.h"
#include "../XlsFormat/Logic/Biff_records/CodeName.h"
#include "../XlsFormat/Logic/Biff_records/Continue.h"
#include "../XlsFormat/Logic/Biff_records/ContinueFrt.h"
#include "../XlsFormat/Logic/Biff_records/ContinueFrt12.h"
#include "../XlsFormat/Logic/Biff_records/DataLabExtContents.h"
#include "../XlsFormat/Logic/Biff_records/End.h"
#include "../XlsFormat/Logic/Biff_records/EndObject.h"
#include "../XlsFormat/Logic/Biff_records/EOF.h"
#include "../XlsFormat/Logic/Biff_records/ExternSheet.h"
#include "../XlsFormat/Logic/Biff_records/Font.h"
#include "../XlsFormat/Logic/Biff_records/FontX.h"
#include "../XlsFormat/Logic/Biff_records/Format.h"
#include "../XlsFormat/Logic/Biff_records/HeaderFooter.h"
#include "../XlsFormat/Logic/Biff_records/HFPicture.h"
#include "../XlsFormat/Logic/Biff_records/Label.h"
#include "../XlsFormat/Logic/Biff_records/LineFormat.h"
#include "../XlsFormat/Logic/Biff_records/MsoDrawing.h"
#include "../XlsFormat/Logic/Biff_records/Pos.h"
#include "../XlsFormat/Logic/Biff_records/SheetExt.h"
#include "../XlsFormat/Logic/Biff_records/StartObject.h"
#include "../XlsFormat/Logic/Biff_records/SXAddl.h"
#include "../XlsFormat/Logic/Biff_records/SXStreamID.h"
#include "../XlsFormat/Logic/Biff_records/SXString.h"
#include "../XlsFormat/Logic/Biff_records/TextPropsStream.h"
#include "../XlsFormat/Logic/Biff_records/Theme.h"
#include "../XlsFormat/Logic/Biff_records/WsBool.h"
#include "../XlsFormat/Binary/BinSmartPointers.h"
#include "../XlsFormat/Binary/CFRecord.h"
#include "../XlsFormat/Binary/CFRecordType.h"
#include "../XlsFormat/Binary/CFStream.h"
#include "../XlsFormat/Binary/CFStreamCacheReader.h"
#include "../XlsFormat/Crypt/Decryptor.h"
#include "../XlsFormat/Logic/Biff_structures/BiffAttribute.h"
#include "../XlsFormat/Logic/Biff_structures/BiffString.h"
#include "../XlsFormat/Logic/Biff_structures/BiffStructure.h"
#include "../XlsFormat/Logic/Biff_structures/BitMarkedStructs.h"
#include "../XlsFormat/Logic/Biff_structures/Boolean.h"
#include "../XlsFormat/Logic/Biff_structures/Cell.h"
#include "../XlsFormat/Logic/Biff_structures/CellOffsetResender.h"
#include "../XlsFormat/Logic/Biff_structures/CellRangeRef.h"
#include "../XlsFormat/Logic/Biff_structures/CellRef.h"
#include "../XlsFormat/Logic/Biff_structures/DXFN.h"
#include "../XlsFormat/Logic/Biff_structures/DXFN12List.h"
#include "../XlsFormat/Logic/Biff_structures/ExtProp.h"
#include "../XlsFormat/Logic/Biff_structures/FixedPoint.h"
#include "../XlsFormat/Logic/Biff_structures/FontIndex.h"
#include "../XlsFormat/Logic/Biff_structures/FrtHeader.h"
#include "../XlsFormat/Logic/Biff_structures/FrtHeaderOld.h"
#include "../XlsFormat/Logic/Biff_structures/FrtRefHeaderU.h"
#include "../XlsFormat/Logic/Biff_structures/LongRGB.h"
#include "../XlsFormat/Logic/Biff_structures/ObjFmla.h"
#include "../XlsFormat/Logic/Biff_structures/OperandPtg.h"
#include "../XlsFormat/Logic/Biff_structures/ParsedFormula.h"
#include "../XlsFormat/Logic/Biff_structures/Ptg.h"
#include "../XlsFormat/Logic/Biff_structures/PtgArea3d.h"
#include "../XlsFormat/Logic/Biff_structures/PtgRef3d.h"
#include "../XlsFormat/Logic/Biff_structures/RC4EncryptionHeader.h"
#include "../XlsFormat/Logic/Biff_structures/RevExtern.h"
#include "../XlsFormat/Logic/Biff_structures/SerAr.h"
#include "../XlsFormat/Logic/Biff_structures/XFPropColor.h"
#include "../XlsFormat/Logic/Biff_structures/SxAxis.h"
#include "../XlsFormat/Logic/Biff_structures/Xnum.h"
#include "../XlsFormat/Logic/Biff_structures/ODRAW/OfficeArtBlip.h"
#include "../XlsFormat/Logic/Biff_structures/ODRAW/OfficeArtCOLORREF.h"
#include "../XlsFormat/Logic/Biff_structures/ODRAW/OfficeArtDgContainer.h"
#include "../XlsFormat/Logic/Biff_structures/ODRAW/OfficeArtFOPT.h"
#include "../XlsFormat/Logic/Biff_structures/ODRAW/OfficeArtRecord.h"
#include "../XlsFormat/Logic/Biff_structures/ODRAW/SimpleOfficeArtContainers.h"
#include "../XlsFormat/Logic/Biff_unions/ATTACHEDLABEL.h"
#include "../XlsFormat/Logic/Biff_unions/AXS.h"
#include "../XlsFormat/Logic/Biff_unions/BACKGROUND.h"
#include "../XlsFormat/Logic/Biff_unions/CRTMLFRT.h"
#include "../XlsFormat/Logic/Biff_unions/DBQUERY.h"
#include "../XlsFormat/Logic/Biff_unions/FRAME.h"
#include "../XlsFormat/Logic/Biff_unions/GELFRAME.h"
#include "../XlsFormat/Logic/Biff_unions/GLOBALS.h"
#include "../XlsFormat/Logic/Biff_unions/OBJECTS.h"
#include "../XlsFormat/Logic/Biff_unions/PIVOTRULE.h"
#include "../XlsFormat/Logic/Biff_unions/SHAPEPROPS.h"
#include "../XlsFormat/Logic/Biff_unions/SORTDATA12.h"
#include "../XlsFormat/Logic/Biff_unions/SS.h"
#include "../XlsFormat/Logic/Biff_unions/TEXTPROPS.h"
#include "../Common/common.h"
#include "../Common/simple_xml_writer.h"
#include "../Common/utils.h"
#include "../XlsXlsxConverter/external_items.h"
#include "../XlsXlsxConverter/mediaitems_utils.h"
#include "../XlsXlsxConverter/oox_package.h"
#include "../XlsXlsxConverter/oox_rels.h"
#include "../XlsXlsxConverter/XlsConverter.h"
#include "../XlsXlsxConverter/xlsx_conversion_context.h"
#include "../XlsFormat/Logic/BaseObject.h"
#include "../XlsFormat/Logic/BinProcessor.h"
#include "../XlsFormat/Logic/CompositeObject.h"
#include "../XlsFormat/Logic/GlobalWorkbookInfo.h"
#include "../XlsFormat/Auxiliary/HelpFunc.h"
#include "../XlsXlsxConverter/ConvertShapes/FormulaShape.h"
#include "../XlsXlsxConverter/ConvertShapes/CustomShape.h"

#endif
