#-------------------------------------------------
#
# Project created by QtCreator 2015-06-07T13:03:16
#
#-------------------------------------------------

QT       -= core gui

TARGET = OdfFileWriterLib
TEMPLATE = lib
CONFIG += staticlib

QMAKE_CXXFLAGS += -std=c++11 -Wall -Wno-ignored-qualifiers

DEFINES +=  UNICODE \
            _UNICODE \
            _LINUX_QT \
            LINUX \
            _USE_LIBXML2_READER_ \
            _USE_XMLLITE_READER_ \
            USE_LITE_READER

INCLUDEPATH += /usr/include/libxml2
INCLUDEPATH += ../../DesktopEditor/freetype-2.5.2/include
INCLUDEPATH += ../../ASCOfficeOdfFile/include
INCLUDEPATH += ../../ASCOfficeOdfFile/src/odf/datatypes


CONFIG(debug, debug|release){
DEFINES +=  _DEBUG
}


SOURCES += \
    ../source/OdfFormat/abstract_xml.cpp \
    ../source/OdfFormat/calcext_elements.cpp \
    ../source/OdfFormat/draw_base.cpp \
    ../source/OdfFormat/draw_frame.cpp \
    ../source/OdfFormat/draw_shapes.cpp \
    ../source/OdfFormat/header_footer.cpp \
    ../source/OdfFormat/list.cpp \
    ../source/OdfFormat/mediaitems.cpp \
    ../source/OdfFormat/mediaitems_utils.cpp \
    ../source/OdfFormat/number_style.cpp \
    ../source/OdfFormat/object_package.cpp \
    ../source/OdfFormat/odf_chart_context.cpp \
    ../source/OdfFormat/odf_comment_context.cpp \
    ../source/OdfFormat/odf_conversion_context.cpp \
    ../source/OdfFormat/odf_drawing_context.cpp \
    ../source/OdfFormat/odf_lists_styles_context.cpp \
    ../source/OdfFormat/odf_number_styles_context.cpp \
    ../source/OdfFormat/odf_page_layout_context.cpp \
    ../source/OdfFormat/odf_page_layout_state.cpp \
    ../source/OdfFormat/odf_rels.cpp \
    ../source/OdfFormat/odf_style_context.cpp \
    ../source/OdfFormat/odf_style_state.cpp \
    ../source/OdfFormat/odf_table_context.cpp \
    ../source/OdfFormat/odf_table_styles_context.cpp \
    ../source/OdfFormat/odf_text_context.cpp \
    ../source/OdfFormat/ods_conversion_context.cpp \
    ../source/OdfFormat/ods_table_context.cpp \
    ../source/OdfFormat/ods_table_state.cpp \
    ../source/OdfFormat/odt_conversion_context.cpp \
    ../source/OdfFormat/office_annotation.cpp \
    ../source/OdfFormat/office_body.cpp \
    ../source/OdfFormat/office_chart.cpp \
    ../source/OdfFormat/office_elements_create.cpp \
    ../source/OdfFormat/office_spreadsheet.cpp \
    ../source/OdfFormat/office_text.cpp \
    ../source/OdfFormat/oox_shape_defines.cpp \
    ../source/OdfFormat/paragraph_elements.cpp \
    ../source/OdfFormat/style_chart_properties.cpp \
    ../source/OdfFormat/style_graphic_properties.cpp \
    ../source/OdfFormat/style_map.cpp \
    ../source/OdfFormat/style_page_layout_properties.cpp \
    ../source/OdfFormat/style_paragraph_properties.cpp \
    ../source/OdfFormat/styles.cpp \
    ../source/OdfFormat/style_section_properties.cpp \
    ../source/OdfFormat/styles_list.cpp \
    ../source/OdfFormat/styles_lite_container.cpp \
    ../source/OdfFormat/style_table_properties.cpp \
    ../source/OdfFormat/style_text_properties.cpp \
    ../source/OdfFormat/svg_creator.cpp \
    ../source/OdfFormat/table.cpp \
    ../source/OdfFormat/table_database_ranges.cpp \
    ../source/OdfFormat/table_named_expressions.cpp \
    ../source/OdfFormat/text_elements.cpp \
    ../source/Oox2OdfConverter/ConvertDiagram.cpp \
    ../source/Oox2OdfConverter/Converter.cpp \
    ../source/Oox2OdfConverter/ConverterChart.cpp \
    ../source/Oox2OdfConverter/ConvertVml.cpp \
    ../source/Oox2OdfConverter/DocxConverter.cpp \
    ../source/Oox2OdfConverter/XlsxConverter.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/anchortype.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/backgroundcolor.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/bool.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/bordermodel.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/borderstyle.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/borderwidths.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/calcext_type.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/chartdatalabelnumber.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/charterrorcategory.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/chartinterpolation.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/chartlabelarrangement.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/chartregressiontype.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/chartseriessource.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/chartsolidtype.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/chartsymbol.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/clockvalue.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/color.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/common_attlists.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/direction.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/drawfill.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/dropcaplength.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fillimagerefpoint.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fobreak.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontfamilygeneric.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontpitch.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontrelief.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontsize.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontstretch.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontstyle.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontvariant.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontweight.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/gradientstyle.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/hatchstyle.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/hyphenationkeep.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/hyphenationladdercount.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/iconset_type.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/keeptogether.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/layoutgridmode.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/length.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/lengthorpercent.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/letterspacing.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/linebreak.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/linemode.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/linestyle.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/linetype.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/linewidth.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/markerstyle.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/noteclass.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/officevaluetype.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/pageusage.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/percent.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/percentorscale.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/presentationclass.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/punctuationwrap.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/rotationalign.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/runthrough.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/scripttype.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/shadowtype.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/smil_transitiontype.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/stylefamily.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/stylehorizontalpos.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/stylehorizontalrel.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/styleleadercolor.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/styleposition.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/style_ref.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/stylerepeat.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/styletype.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/styleverticalpos.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/styleverticalrel.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/stylewrap.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/stylewrapcontourmode.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/tablealign.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/tablecentering.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/tablemode.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/tablevisibility.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/targetframename.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textalign.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textalignsource.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textautospace.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textcombine.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textdisplay.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textemphasize.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textposition.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textrotationscale.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/texttransform.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/underlinecolor.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/verticalalign.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/wrapoption.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/writingmode.cpp \
    ../../ASCOfficeOdfFile/src/odf/datatypes/xlink.cpp

HEADERS += \
    ../source/OdfFormat/abstract_xml.h \
    ../source/OdfFormat/calcext_elements.h \
    ../source/OdfFormat/draw_base.h \
    ../source/OdfFormat/draw_frame.h \
    ../source/OdfFormat/draw_shapes.h \
    ../source/OdfFormat/header_footer.h \
    ../source/OdfFormat/list.h \
    ../source/OdfFormat/mediaitems.h \
    ../source/OdfFormat/mediaitems_utils.h \
    ../source/OdfFormat/number_style.h \
    ../source/OdfFormat/object_package.h \
    ../source/OdfFormat/odf_chart_context.h \
    ../source/OdfFormat/odf_comment_context.h \
    ../source/OdfFormat/odf_conversion_context.h \
    ../source/OdfFormat/odf_drawing_context.h \
    ../source/OdfFormat/odf_lists_styles_context.h \
    ../source/OdfFormat/odf_number_styles_context.h \
    ../source/OdfFormat/odf_page_layout_context.h \
    ../source/OdfFormat/odf_page_layout_state.h \
    ../source/OdfFormat/odf_rels.h \
    ../source/OdfFormat/odf_style_context.h \
    ../source/OdfFormat/odf_style_state.h \
    ../source/OdfFormat/odf_table_context.h \
    ../source/OdfFormat/odf_table_styles_context.h \
    ../source/OdfFormat/odf_text_context.h \
    ../source/OdfFormat/ods_conversion_context.h \
    ../source/OdfFormat/ods_table_context.h \
    ../source/OdfFormat/ods_table_state.h \
    ../source/OdfFormat/odt_conversion_context.h \
    ../source/OdfFormat/office_annotation.h \
    ../source/OdfFormat/office_body.h \
    ../source/OdfFormat/office_chart.h \
    ../source/OdfFormat/office_elements.h \
    ../source/OdfFormat/office_elements_create.h \
    ../source/OdfFormat/office_elements_type.h \
    ../source/OdfFormat/office_spreadsheet.h \
    ../source/OdfFormat/office_text.h \
    ../source/OdfFormat/oox_shape_defines.h \
    ../source/OdfFormat/paragraph_elements.h \
    ../source/OdfFormat/style_chart_properties.h \
    ../source/OdfFormat/style_graphic_properties.h \
    ../source/OdfFormat/style_map.h \
    ../source/OdfFormat/style_page_layout_properties.h \
    ../source/OdfFormat/style_paragraph_properties.h \
    ../source/OdfFormat/styles.h \
    ../source/OdfFormat/style_section_properties.h \
    ../source/OdfFormat/styles_list.h \
    ../source/OdfFormat/styles_lite_container.h \
    ../source/OdfFormat/style_table_properties.h \
    ../source/OdfFormat/style_text_properties.h \
    ../source/OdfFormat/svg_creator.h \
    ../source/OdfFormat/table.h \
    ../source/OdfFormat/table_database_ranges.h \
    ../source/OdfFormat/table_named_expressions.h \
    ../source/OdfFormat/text_elements.h \
    ../source/OdfFormat/visitor.h \
    ../source/Oox2OdfConverter/Converter.h \
    ../source/Oox2OdfConverter/DocxConverter.h \
    ../source/Oox2OdfConverter/Oox2OdfConverter.h \
    ../source/Oox2OdfConverter/VmlShapeTypes2Oox.h \
    ../source/Oox2OdfConverter/XlsxConverter.h \
    ../source/OdfFormat/Shapes/odf_shape_mapping.h \
    ../source/OdfFormat/Shapes/oox_shapeAccentCallouts.h \
    ../source/OdfFormat/Shapes/oox_shapeActionButtons.h \
    ../source/OdfFormat/Shapes/oox_shapeArrows.h \
    ../source/OdfFormat/Shapes/oox_shapeBents.h \
    ../source/OdfFormat/Shapes/oox_shapeCallouts.h \
    ../source/OdfFormat/Shapes/oox_shapeCharts.h \
    ../source/OdfFormat/Shapes/oox_shapeConnectors.h \
    ../source/OdfFormat/Shapes/oox_shapeCurvedArrows.h \
    ../source/OdfFormat/Shapes/oox_shapeCurvedConnectors.h \
    ../source/OdfFormat/Shapes/oox_shapeCustoms.h \
    ../source/OdfFormat/Shapes/oox_shapeMaths.h \
    ../source/OdfFormat/Shapes/oox_shapePrimitives.h \
    ../source/OdfFormat/Shapes/oox_shapeRibbons.h \
    ../source/OdfFormat/Shapes/oox_shapeSnipRoundRects.h \
    ../source/OdfFormat/Shapes/oox_shapeStars.h \
    ../source/OdfFormat/Shapes/oox_shapeWordArt.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/anchortype.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/backgroundcolor.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/bool.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/bordermodel.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/borderstyle.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/borderwidths.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/calcext_type.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/chartdatalabelnumber.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/charterrorcategory.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/chartinterpolation.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/chartlabelarrangement.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/chartregressiontype.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/chartseriessource.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/chartsolidtype.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/chartsymbol.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/clockvalue.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/color.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/common_attlists.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/custom_shape_types_convert.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/direction.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/drawfill.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/dropcaplength.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/errors.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fillimagerefpoint.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fobreak.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontfamilygeneric.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontpitch.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontrelief.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontsize.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontstretch.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontstyle.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontvariant.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/fontweight.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/gradientstyle.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/hatchstyle.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/hyphenationkeep.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/hyphenationladdercount.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/iconset_type.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/keeptogether.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/layoutgridmode.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/length.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/lengthorpercent.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/letterspacing.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/linebreak.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/linemode.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/linestyle.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/linetype.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/linewidth.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/markerstyle.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/noteclass.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/odfattributes.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/officevaluetype.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/pageusage.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/percent.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/percentorscale.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/presentationclass.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/punctuationwrap.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/rotationalign.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/runthrough.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/scripttype.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/shadowtype.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/smil_transitiontype.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/stylefamily.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/stylehorizontalpos.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/stylehorizontalrel.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/styleleadercolor.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/styleposition.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/style_ref.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/stylerepeat.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/styletype.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/styleverticalpos.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/styleverticalrel.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/stylewrap.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/stylewrapcontourmode.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/tablealign.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/tablecentering.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/tablemode.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/tablevisibility.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/targetframename.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textalign.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textalignsource.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textautospace.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textcombine.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textdisplay.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textemphasize.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textposition.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/textrotationscale.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/texttransform.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/underlinecolor.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/verticalalign.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/wrapoption.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/writingmode.h \
    ../../ASCOfficeOdfFile/src/odf/datatypes/xlink.h
unix {
    target.path = /usr/lib
    INSTALLS += target
}
