#pragma once

#include "PPTAutoShapes\AccentBorderCallout90Type.h"
#include "PPTAutoShapes\AccentBorderCallout1Type.h"
#include "PPTAutoShapes\AccentBorderCallout2Type.h"
#include "PPTAutoShapes\AccentBorderCallout3Type.h"

#include "PPTAutoShapes\AccentCallout90Type.h"
#include "PPTAutoShapes\AccentCallout1Type.h"
#include "PPTAutoShapes\AccentCallout2Type.h"
#include "PPTAutoShapes\AccentCallout3Type.h"

#include "PPTAutoShapes\BorderCallout90Type.h"
#include "PPTAutoShapes\BorderCallout1Type.h"
#include "PPTAutoShapes\BorderCallout2Type.h"
#include "PPTAutoShapes\BorderCallout3Type.h"

#include "PPTAutoShapes\Callout90Type.h"
#include "PPTAutoShapes\Callout1Type.h"
#include "PPTAutoShapes\Callout2Type.h"
#include "PPTAutoShapes\Callout3Type.h"

#include "PPTAutoShapes\BentConnector.h"
#include "PPTAutoShapes\CurvedConnector.h"

#include "PPTAutoShapes\ActionButtonBlank.h"
#include "PPTAutoShapes\ActionButtonHome.h"
#include "PPTAutoShapes\ActionButtonHelp.h"
#include "PPTAutoShapes\ActionButtonInfo.h"
#include "PPTAutoShapes\ActionButtonBack.h"
#include "PPTAutoShapes\ActionButtonNext.h"
#include "PPTAutoShapes\ActionButtonBeginning.h"
#include "PPTAutoShapes\ActionButtonEnd.h"
#include "PPTAutoShapes\ActionButtonReturn.h"
#include "PPTAutoShapes\ActionButtonDocument.h"
#include "PPTAutoShapes\ActionButtonSound.h"
#include "PPTAutoShapes\ActionButtonMovie.h"

#include "PPTAutoShapes\ArcType.h"
#include "PPTAutoShapes\LineType.h"

#include "PPTAutoShapes\BentArrowType.h"
#include "PPTAutoShapes\BentUpArrowType.h"
#include "PPTAutoShapes\BevelType.h"
#include "PPTAutoShapes\BlockArcType.h"
#include "PPTAutoShapes\BracePairType.h"
#include "PPTAutoShapes\BracketPairType.h"

#include "PPTAutoShapes\CanType.h"
#include "PPTAutoShapes\ChevronType.h"
#include "PPTAutoShapes\CircularArrowType.h"
#include "PPTAutoShapes\CloudCalloutType.h"
#include "PPTAutoShapes\CubeType.h"
#include "PPTAutoShapes\CurvedDownArrowType.h"
#include "PPTAutoShapes\CurvedLeftArrowType.h"
#include "PPTAutoShapes\CurvedRightArrowType.h"
#include "PPTAutoShapes\CurvedUpArrowType.h"

#include "PPTAutoShapes\DiamondType.h"
#include "PPTAutoShapes\DonutType.h"
#include "PPTAutoShapes\DownArrowCalloutType.h"
#include "PPTAutoShapes\DownArrowType.h"

#include "PPTAutoShapes\EllipseType.h"
#include "PPTAutoShapes\EllipseRibbon2Type.h"
#include "PPTAutoShapes\EllipseRibbonType.h"

#include "PPTAutoShapes\FlowChartAlternateProcessType.h"
#include "PPTAutoShapes\FlowChartCollateType.h"
#include "PPTAutoShapes\FlowChartConnectorType.h"
#include "PPTAutoShapes\FlowChartDecisionType.h"
#include "PPTAutoShapes\FlowChartDelayType.h"
#include "PPTAutoShapes\FlowChartDisplayType.h"
#include "PPTAutoShapes\FlowChartDocumentType.h"
#include "PPTAutoShapes\FlowChartExtractType.h"
#include "PPTAutoShapes\FlowChartInputOutputType.h"
#include "PPTAutoShapes\FlowChartInternalStorageType.h"
#include "PPTAutoShapes\FlowChartMagneticDiskType.h"
#include "PPTAutoShapes\FlowChartMagneticDrumType.h"
#include "PPTAutoShapes\FlowChartMagneticTapeType.h"
#include "PPTAutoShapes\FlowChartManualInputType.h"
#include "PPTAutoShapes\FlowChartManualOperationType.h"
#include "PPTAutoShapes\FlowChartMergeType.h"
#include "PPTAutoShapes\FlowChartMultidocumentType.h"
#include "PPTAutoShapes\FlowChartOffpageConnectorType.h"
#include "PPTAutoShapes\FlowChartOnlineStorageType.h"
#include "PPTAutoShapes\FlowChartOrType.h"
#include "PPTAutoShapes\FlowChartPredefinedProcessType.h"
#include "PPTAutoShapes\FlowChartPreparationType.h"
#include "PPTAutoShapes\FlowChartProcessType.h"
#include "PPTAutoShapes\FlowChartPunchedCardType.h"
#include "PPTAutoShapes\FlowChartPunchedTapeType.h"
#include "PPTAutoShapes\FlowChartSortType.h"
#include "PPTAutoShapes\FlowChartSummingJunctionType.h"
#include "PPTAutoShapes\FlowChartTerminatorType.h"
#include "PPTAutoShapes\FoldedCornerType.h"

#include "PPTAutoShapes\HeartType.h"
#include "PPTAutoShapes\HexagonType.h"
#include "PPTAutoShapes\HomePlateType.h"

#include "PPTAutoShapes\IrregularSealOneType.h"
#include "PPTAutoShapes\IrregularSealTwo.h"
#include "PPTAutoShapes\IsoscelesTriangleType.h"

#include "PPTAutoShapes\LeftArrowCalloutType.h"
#include "PPTAutoShapes\LeftArrowType.h"
#include "PPTAutoShapes\LeftBraceType.h"
#include "PPTAutoShapes\LeftBracketType.h"
#include "PPTAutoShapes\LeftRightArrowCalloutType.h"
#include "PPTAutoShapes\LeftRightArrowType.h"
#include "PPTAutoShapes\LeftRightUpArrow.h"
#include "PPTAutoShapes\LeftUpArrowType.h"
#include "PPTAutoShapes\LightningBoltType.h"

#include "PPTAutoShapes\MoonType.h"

#include "PPTAutoShapes\NoSmokingType.h"
#include "PPTAutoShapes\NotchedRightArrowType.h"

#include "PPTAutoShapes\OctagonType.h"

#include "PPTAutoShapes\ParallelogramType.h"
#include "PPTAutoShapes\PentagonType.h"
#include "PPTAutoShapes\PlaqueType.h"
#include "PPTAutoShapes\PlusType.h"

#include "PPTAutoShapes\QuadArrowCalloutType.h"
#include "PPTAutoShapes\QuadArrowType.h"

#include "PPTAutoShapes\RectangleType.h"
#include "PPTAutoShapes\RibbonDownType.h"
#include "PPTAutoShapes\RibbonUpType.h"
#include "PPTAutoShapes\RightArrowCalloutType.h"
#include "PPTAutoShapes\RightArrowType.h"
#include "PPTAutoShapes\RightBracetype.h"
#include "PPTAutoShapes\RightBracketType.h"
#include "PPTAutoShapes\RightTriangleType.h"
#include "PPTAutoShapes\RoundedRectangleType.h"

#include "PPTAutoShapes\Seal16Type.h"
#include "PPTAutoShapes\Seal24Type.h"
#include "PPTAutoShapes\Seal32Type.h"
#include "PPTAutoShapes\Seal4Type.h"
#include "PPTAutoShapes\Seal8Type.h"
#include "PPTAutoShapes\SmileyFaceType.h"
#include "PPTAutoShapes\Startype.h"
#include "PPTAutoShapes\StraightConnectorType.h"
#include "PPTAutoShapes\StripedRightArrowType.h"
#include "PPTAutoShapes\SunType.h"

#include "PPTAutoShapes\TextboxType.h"
#include "PPTAutoShapes\TrapezoidType.h"

#include "PPTAutoShapes\UpArrowCalloutType.h"
#include "PPTAutoShapes\UpArrowType.h"
#include "PPTAutoShapes\UpDownArrowCalloutType.h"
#include "PPTAutoShapes\UpDownArrowType.h"
#include "PPTAutoShapes\UturnArrowType.h"

#include "PPTAutoShapes\VerticalScrollType.h"
#include "PPTAutoShapes\HorisontalScrollType.h"

#include "PPTAutoShapes\WedgeEllipseCalloutType.h"
#include "PPTAutoShapes\WedgeRectCalloutType.h"
#include "PPTAutoShapes\WedgeRoundedRectCalloutType.h"

#include "PPTAutoShapes\WaveType.h"
#include "PPTAutoShapes\WaveDoubleType.h"