#-------------------------------------------------
#
# Project created by QtCreator 2ChartSheetStream014-07-03T15:22:54
#
#-------------------------------------------------

QT       -= core gui

TARGET = XlsbFormatLib
TEMPLATE = lib
CONFIG += staticlib

CORE_ROOT_DIR = $$PWD/../../..
PWD_ROOT_DIR = $$PWD

CONFIG += core_x2t
include(../../../Common/base.pri)

DEFINES +=  UNICODE _UNICODE
DEFINES +=  DONT_WRITE_EMBEDDED_FONTS

#BOOST
include($$PWD/../../3dParty/boost/boost.pri)

core_release {
SOURCES += \
    xlsbformatlib_logic.cpp
}

core_debug {
SOURCES += \
    ../Source/XlsbFormat/Biff12_unions/COMMENTS_bu.cpp \
    ../Source/XlsbFormat/Xlsb.cpp \
    ../Source/XlsbFormat/WorkBookStream.cpp \
    ../Source/XlsbFormat/WorkSheetStream.cpp \
    ../Source/XlsbFormat/SharedStringsStream.cpp \
    ../Source/XlsbFormat/StylesStream.cpp \
    ../Source/XlsbFormat/CommentsStream.cpp \
    ../Source/XlsbFormat/TableStream.cpp \
    ../Source/XlsbFormat/QueryTableStream.cpp \
    ../Source/XlsbFormat/ConnectionsStream.cpp \
    ../Source/XlsbFormat/SlicersStream.cpp \
    ../Source/XlsbFormat/SlicerCachesStream.cpp \
    ../Source/XlsbFormat/ChartSheetStream.cpp \
### Biff12_records
    ../Source/XlsbFormat/Biff12_records/BeginBook.cpp \
    ../Source/XlsbFormat/Biff12_records/FRTBegin.cpp \
    ../Source/XlsbFormat/Biff12_records/FRTEnd.cpp \
    ../Source/XlsbFormat/Biff12_records/Uid.cpp \
    ../Source/XlsbFormat/Biff12_records/FileVersion.cpp \
    ../Source/XlsbFormat/Biff12_records/FileSharingIso.cpp \
    ../Source/XlsbFormat/Biff12_records/WbProp.cpp \
    ../Source/XlsbFormat/Biff12_records/ACBegin.cpp \
    ../Source/XlsbFormat/Biff12_records/AbsPath15.cpp \
    ../Source/XlsbFormat/Biff12_records/ACEnd.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginBookViews.cpp \
    ../Source/XlsbFormat/Biff12_records/EndBookViews.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginBundleShs.cpp \
    ../Source/XlsbFormat/Biff12_records/BundleSh.cpp \
    ../Source/XlsbFormat/Biff12_records/EndBundleShs.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginFnGroup.cpp \
    ../Source/XlsbFormat/Biff12_records/FnGroup.cpp \
    ../Source/XlsbFormat/Biff12_records/EndFnGroup.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginExternals.cpp \
    ../Source/XlsbFormat/Biff12_records/EndExternals.cpp \
    ../Source/XlsbFormat/Biff12_records/SupSelf.cpp \
    ../Source/XlsbFormat/Biff12_records/SupBookSrc.cpp \
    ../Source/XlsbFormat/Biff12_records/SupSame.cpp \
    ../Source/XlsbFormat/Biff12_records/PlaceholderName.cpp \
    ../Source/XlsbFormat/Biff12_records/SupAddin.cpp \
    ../Source/XlsbFormat/Biff12_records/CalcProp.cpp \
    ../Source/XlsbFormat/Biff12_records/OleSize.cpp \
    ../Source/XlsbFormat/Biff12_records/EndBook.cpp \
    ../Source/XlsbFormat/Biff12_records/BookProtectionIso.cpp \
    ../Source/XlsbFormat/Biff12_records/BookProtection.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSheet.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginColInfos.cpp \
    ../Source/XlsbFormat/Biff12_records/EndColInfos.cpp \
    ../Source/XlsbFormat/Biff12_records/WsDim.cpp \
    ../Source/XlsbFormat/Biff12_records/Drawing.cpp \
    ../Source/XlsbFormat/Biff12_records/LegacyDrawing.cpp \
    ../Source/XlsbFormat/Biff12_records/LegacyDrawingHF.cpp \
    ../Source/XlsbFormat/Biff12_records/HLink.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginMergeCells.cpp \
    ../Source/XlsbFormat/Biff12_records/MergeCell.cpp \
    ../Source/XlsbFormat/Biff12_records/EndMergeCells.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSheetData.cpp \
    ../Source/XlsbFormat/Biff12_records/RwDescent.cpp \
    ../Source/XlsbFormat/Biff12_records/CellMeta.cpp \
    ../Source/XlsbFormat/Biff12_records/ValueMeta.cpp \
    ../Source/XlsbFormat/Biff12_records/WsFmtInfo.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSheetData.cpp \
    ../Source/XlsbFormat/Biff12_records/EndWsView.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginWsViews.cpp \
    ../Source/XlsbFormat/Biff12_records/EndWsViews.cpp \
    ../Source/XlsbFormat/Biff12_records/SheetProtectionIso.cpp \
    ../Source/XlsbFormat/Biff12_records/SheetProtection.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginListParts.cpp \
    ../Source/XlsbFormat/Biff12_records/ListPart.cpp \
    ../Source/XlsbFormat/Biff12_records/EndListParts.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSortCond.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSortCond.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSortCond14.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSortCond14.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginRichSortCondition.cpp \
    ../Source/XlsbFormat/Biff12_records/EndRichSortCondition.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSortState.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginConditionalFormatting.cpp \
    ../Source/XlsbFormat/Biff12_records/EndConditionalFormatting.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginCFRule.cpp \
    ../Source/XlsbFormat/Biff12_records/EndCFRule.cpp \
    ../Source/XlsbFormat/Biff12_records/CFVO.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginIconSet.cpp \
    ../Source/XlsbFormat/Biff12_records/EndIconSet.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginDatabar.cpp \
    ../Source/XlsbFormat/Biff12_records/EndDatabar.cpp \
    ../Source/XlsbFormat/Biff12_records/Color.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginColorScale.cpp \
    ../Source/XlsbFormat/Biff12_records/EndColorScale.cpp \
    ../Source/XlsbFormat/Biff12_records/CFRuleExt.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginCFRule14.cpp \
    ../Source/XlsbFormat/Biff12_records/EndCFRule14.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginConditionalFormatting14.cpp \
    ../Source/XlsbFormat/Biff12_records/EndConditionalFormatting14.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginColorScale14.cpp \
    ../Source/XlsbFormat/Biff12_records/Color14.cpp \
    ../Source/XlsbFormat/Biff12_records/EndColorScale14.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginDatabar14.cpp \
    ../Source/XlsbFormat/Biff12_records/EndDatabar14.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginIconSet14.cpp \
    ../Source/XlsbFormat/Biff12_records/CFIcon.cpp \
    ../Source/XlsbFormat/Biff12_records/EndIconSet14.cpp \
    ../Source/XlsbFormat/Biff12_records/CFVO14.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSheet.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSst.cpp \
    ../Source/XlsbFormat/Biff12_records/SSTItem.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSst.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginStyleSheet.cpp \
    ../Source/XlsbFormat/Biff12_records/Fmt.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginFmts.cpp \
    ../Source/XlsbFormat/Biff12_records/EndFmts.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginFonts.cpp \
    ../Source/XlsbFormat/Biff12_records/KnownFonts.cpp \
    ../Source/XlsbFormat/Biff12_records/EndFonts.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginFills.cpp \
    ../Source/XlsbFormat/Biff12_records/Fill.cpp \
    ../Source/XlsbFormat/Biff12_records/EndFills.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginBorders.cpp \
    ../Source/XlsbFormat/Biff12_records/Border.cpp \
    ../Source/XlsbFormat/Biff12_records/EndBorders.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginCellStyleXFs.cpp \
    ../Source/XlsbFormat/Biff12_records/EndCellStyleXFs.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginCellXFs.cpp \
    ../Source/XlsbFormat/Biff12_records/EndCellXFs.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginStyles.cpp \
    ../Source/XlsbFormat/Biff12_records/Style.cpp \
    ../Source/XlsbFormat/Biff12_records/EndStyles.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginDXFs.cpp \
    ../Source/XlsbFormat/Biff12_records/EndDXFs.cpp \
    ../Source/XlsbFormat/Biff12_records/EndTableStyles.cpp \
    ../Source/XlsbFormat/Biff12_records/EndTableStyle.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginColorPalette.cpp \
    ../Source/XlsbFormat/Biff12_records/EndColorPalette.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginIndexedColors.cpp \
    ../Source/XlsbFormat/Biff12_records/IndexedColor.cpp \
    ../Source/XlsbFormat/Biff12_records/EndIndexedColors.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginMRUColors.cpp \
    ../Source/XlsbFormat/Biff12_records/MRUColor.cpp \
    ../Source/XlsbFormat/Biff12_records/EndMRUColors.cpp \
    ../Source/XlsbFormat/Biff12_records/EndStyleSheet.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginConditionalFormattings.cpp \
    ../Source/XlsbFormat/Biff12_records/EndConditionalFormattings.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginDXF14s.cpp \
    ../Source/XlsbFormat/Biff12_records/EndDXF14s.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginDXFs15.cpp \
    ../Source/XlsbFormat/Biff12_records/EndDXFs15.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginTimelineStyle.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginTimelineStyleElements.cpp \
    ../Source/XlsbFormat/Biff12_records/TimelineStyleElement.cpp \
    ../Source/XlsbFormat/Biff12_records/EndTimelineStyleElements.cpp \
    ../Source/XlsbFormat/Biff12_records/EndTimelineStyle.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginTimelineStyles.cpp \
    ../Source/XlsbFormat/Biff12_records/EndTimelineStyles.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginTimelineStyleSheetExt15.cpp \
    ../Source/XlsbFormat/Biff12_records/EndTimelineStyleSheetExt15.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerStyle.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerStyleElements.cpp \
    ../Source/XlsbFormat/Biff12_records/SlicerStyleElement.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerStyleElements.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerStyle.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerStyles.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerStyles.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginStyleSheetExt14.cpp \
    ../Source/XlsbFormat/Biff12_records/EndStyleSheetExt14.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginComment.cpp \
    ../Source/XlsbFormat/Biff12_records/CommentText.cpp \
    ../Source/XlsbFormat/Biff12_records/EndComment.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginCommentList.cpp \
    ../Source/XlsbFormat/Biff12_records/EndCommentList.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginCommentAuthors.cpp \
    ../Source/XlsbFormat/Biff12_records/CommentAuthor.cpp \
    ../Source/XlsbFormat/Biff12_records/EndCommentAuthors.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginComments.cpp \
    ../Source/XlsbFormat/Biff12_records/EndComments.cpp \
    ../Source/XlsbFormat/Biff12_records/TableStyleClient.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginList.cpp \
    ../Source/XlsbFormat/Biff12_records/EndList.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginListCols.cpp \
    ../Source/XlsbFormat/Biff12_records/ListCCFmla.cpp \
    ../Source/XlsbFormat/Biff12_records/ListTrFmla.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginListXmlCPr.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginListCol.cpp \
    ../Source/XlsbFormat/Biff12_records/EndListCols.cpp \
    ../Source/XlsbFormat/Biff12_records/EndListCol.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginAFilter.cpp \
    ../Source/XlsbFormat/Biff12_records/EndListXmlCPr.cpp \
    ../Source/XlsbFormat/Biff12_records/List14.cpp \
    ../Source/XlsbFormat/Biff12_records/Top10Filter.cpp \
    ../Source/XlsbFormat/Biff12_records/Top10RichFilter.cpp \
    ../Source/XlsbFormat/Biff12_records/EndAFilter.cpp \
    ../Source/XlsbFormat/Biff12_records/EndFilterColumn.cpp \
    ../Source/XlsbFormat/Biff12_records/IconFilter.cpp \
    ../Source/XlsbFormat/Biff12_records/IconFilter14.cpp \
    ../Source/XlsbFormat/Biff12_records/ColorFilter.cpp \
    ../Source/XlsbFormat/Biff12_records/DynamicFilter.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginFilterColumn.cpp \
    ../Source/XlsbFormat/Biff12_records/AFilterDateGroupItem.cpp \
    ../Source/XlsbFormat/Biff12_records/RichFilterDateGroupItem.cpp \
    ../Source/XlsbFormat/Biff12_records/Filter.cpp \
    ../Source/XlsbFormat/Biff12_records/CustomFilter.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginCustomFilters.cpp \
    ../Source/XlsbFormat/Biff12_records/CustomFilter14.cpp \
    ../Source/XlsbFormat/Biff12_records/EndCustomFilters.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginCustomFilters14.cpp \
    ../Source/XlsbFormat/Biff12_records/Filter14.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginFilters.cpp \
    ../Source/XlsbFormat/Biff12_records/EndFilters.cpp \
    ../Source/XlsbFormat/Biff12_records/DynamicRichFilter.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginRichFilterColumn.cpp \
    ../Source/XlsbFormat/Biff12_records/EndRichFilterColumn.cpp \
    ../Source/XlsbFormat/Biff12_records/RichFilter.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginRichFilters.cpp \
    ../Source/XlsbFormat/Biff12_records/EndRichFilters.cpp \
    ../Source/XlsbFormat/Biff12_records/CustomRichFilter.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginCustomRichFilters.cpp \
    ../Source/XlsbFormat/Biff12_records/EndCustomRichFilters.cpp \
    ../Source/XlsbFormat/Biff12_records/Margins.cpp \
    ../Source/XlsbFormat/Biff12_records/PrintOptions.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginHeaderFooter.cpp \
    ../Source/XlsbFormat/Biff12_records/EndHeaderFooter.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginDVals.cpp \
    ../Source/XlsbFormat/Biff12_records/EndDVals.cpp \
    ../Source/XlsbFormat/Biff12_records/DValList.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginDVals14.cpp \
    ../Source/XlsbFormat/Biff12_records/EndDVals14.cpp \
    ../Source/XlsbFormat/Biff12_records/EndQSI.cpp \
    ../Source/XlsbFormat/Biff12_records/EndQSIR.cpp \
    ../Source/XlsbFormat/Biff12_records/EndQSIF.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginQSIFs.cpp \
    ../Source/XlsbFormat/Biff12_records/EndQSIFs.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginDeletedNames.cpp \
    ../Source/XlsbFormat/Biff12_records/EndDeletedNames.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginDeletedName.cpp \
    ../Source/XlsbFormat/Biff12_records/EndDeletedName.cpp \
    ../Source/XlsbFormat/Biff12_records/Qsi15.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginExtConnections.cpp \
    ../Source/XlsbFormat/Biff12_records/EndExtConnections.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginExtConnection.cpp \
    ../Source/XlsbFormat/Biff12_records/EndExtConnection.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginECDbProps.cpp \
    ../Source/XlsbFormat/Biff12_records/EndECDbProps.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginECOlapProps.cpp \
    ../Source/XlsbFormat/Biff12_records/EndECOlapProps.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginECWebProps.cpp \
    ../Source/XlsbFormat/Biff12_records/EndECWebProps.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginEcWpTables.cpp \
    ../Source/XlsbFormat/Biff12_records/EndECWPTables.cpp \
    ../Source/XlsbFormat/Biff12_records/PCDIMissing.cpp \
    ../Source/XlsbFormat/Biff12_records/PCDIIndex.cpp \
    ../Source/XlsbFormat/Biff12_records/PCDIString.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginECTxtWiz.cpp \
    ../Source/XlsbFormat/Biff12_records/EndECTxtWiz.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginECTWFldInfoLst.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginECTwFldInfo.cpp \
    ../Source/XlsbFormat/Biff12_records/EndECTWFldInfoLst.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginECParams.cpp \
    ../Source/XlsbFormat/Biff12_records/EndECParams.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginECParam.cpp \
    ../Source/XlsbFormat/Biff12_records/EndECParam.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginPCDCalcMemsExt.cpp \
    ../Source/XlsbFormat/Biff12_records/EndPCDCalcMemsExt.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginPCDCalcMem14.cpp \
    ../Source/XlsbFormat/Biff12_records/EndPCDCalcMem14.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginPCDCalcMemExt.cpp \
    ../Source/XlsbFormat/Biff12_records/EndPCDCalcMemExt.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSXTupleSet.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSXTupleSet.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSXTupleSetHeader.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSXTupleSetHeader.cpp \
    ../Source/XlsbFormat/Biff12_records/SXTupleSetHeaderItem.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSXTupleSetData.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSXTupleSetData.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSXTupleSetRow.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSXTupleSetData.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSXTupleSetRow.cpp \
    ../Source/XlsbFormat/Biff12_records/SXTupleSetRowItem.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSXTupleSetRow.cpp \
    ../Source/XlsbFormat/Biff12_records/PCDCalcMem15.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginExtConn14.cpp \
    ../Source/XlsbFormat/Biff12_records/EndExtConn14.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginExtConn15.cpp \
    ../Source/XlsbFormat/Biff12_records/RangePr15.cpp \
    ../Source/XlsbFormat/Biff12_records/EndExtConn15.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginOledbPr15.cpp \
    ../Source/XlsbFormat/Biff12_records/DbCommand15.cpp \
    ../Source/XlsbFormat/Biff12_records/EndOledbPr15.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginDbTables15.cpp \
    ../Source/XlsbFormat/Biff12_records/DbTable15.cpp \
    ../Source/XlsbFormat/Biff12_records/EndDbTables15.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginDataFeedPr15.cpp \
    ../Source/XlsbFormat/Biff12_records/EndDataFeedPr15.cpp \
    ../Source/XlsbFormat/Biff12_records/TextPr15.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginECTxtWiz15.cpp \
    ../Source/XlsbFormat/Biff12_records/EndECTxtWiz15.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginECTWFldInfoLst15.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginECTwFldInfo15.cpp \
    ../Source/XlsbFormat/Biff12_records/EndECTWFldInfoLst15.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSparklineGroups.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSparklineGroups.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSparklineGroup.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSparklineGroup.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSparklines.cpp \
    ../Source/XlsbFormat/Biff12_records/Sparkline.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSparklines.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicers.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicers.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicer.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicer.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCache.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheDef.cpp \
    ../Source/XlsbFormat/Biff12_records/SlicerCachePivotTables.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheDef.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCache.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheOlapImpl.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheOlapImpl.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheLevelsData.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheLevelsData.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheLevelData.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheLevelData.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheSiRanges.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheSiRanges.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheSiRange.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheSiRange.cpp \
    ../Source/XlsbFormat/Biff12_records/SlicerCacheOlapItem.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheSelections.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheSelections.cpp \
    ../Source/XlsbFormat/Biff12_records/SlicerCacheSelection.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheNative.cpp \
    ../Source/XlsbFormat/Biff12_records/SlicerCacheNativeItem.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheNative.cpp \
    ../Source/XlsbFormat/Biff12_records/SlicerCacheBookPivotTables.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginTableSlicerCache.cpp \
    ../Source/XlsbFormat/Biff12_records/EndTableSlicerCache.cpp \
    ../Source/XlsbFormat/Biff12_records/SlicerCacheHideItemsWithNoData.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicersEx.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicersEx.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerEx.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerEx.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCachesPivotCacheIDs.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCachesPivotCacheIDs.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCachesPivotCacheID.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCachesPivotCacheID.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheIDs.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheIDs.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheID.cpp \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheID.cpp \
    ../Source/XlsbFormat/Biff12_records/TableSlicerCacheIDs.cpp \
    ../Source/XlsbFormat/Biff12_records/TableSlicerCacheID.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginOleObjects.cpp \
    ../Source/XlsbFormat/Biff12_records/OleObject.cpp \
    ../Source/XlsbFormat/Biff12_records/EndOleObjects.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginActiveXControls.cpp \
    ../Source/XlsbFormat/Biff12_records/ActiveX_br.cpp \
    ../Source/XlsbFormat/Biff12_records/EndActiveXControls.cpp \
    ../Source/XlsbFormat/Biff12_records/WsProp.cpp \
    ../Source/XlsbFormat/Biff12_records/BkHim.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginRwBrk.cpp \
    ../Source/XlsbFormat/Biff12_records/Brk.cpp \
    ../Source/XlsbFormat/Biff12_records/EndRwBrk.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginColBrk.cpp \
    ../Source/XlsbFormat/Biff12_records/EndColBrk.cpp \
    ../Source/XlsbFormat/Biff12_records/RangeProtection.cpp \
    ../Source/XlsbFormat/Biff12_records/RangeProtectionIso.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginDCon.cpp \
    ../Source/XlsbFormat/Biff12_records/EndDCon.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginDRefs.cpp \
    ../Source/XlsbFormat/Biff12_records/DRef.cpp \
    ../Source/XlsbFormat/Biff12_records/EndDRefs.cpp \
    ../Source/XlsbFormat/Biff12_records/CsProp.cpp \
    ../Source/XlsbFormat/Biff12_records/CsProtection.cpp \
    ../Source/XlsbFormat/Biff12_records/CsProtectionIso.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginCsViews.cpp \
    ../Source/XlsbFormat/Biff12_records/EndCsViews.cpp \
    ../Source/XlsbFormat/Biff12_records/EndCsView.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginUserCsViews.cpp \
    ../Source/XlsbFormat/Biff12_records/EndUserCsViews.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginUserCsView.cpp \
    ../Source/XlsbFormat/Biff12_records/EndUserCsView.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginWebPubItems.cpp \
    ../Source/XlsbFormat/Biff12_records/EndWebPubItems.cpp \
    ../Source/XlsbFormat/Biff12_records/BeginWebPubItem.cpp \
    ../Source/XlsbFormat/Biff12_records/EndWebPubItem.cpp \
### Biff12_structures
    ../Source/XlsbFormat/Biff12_structures/LPByteBuf.cpp \
    ../Source/XlsbFormat/Biff12_structures/IsoPasswordData.cpp \
    ../Source/XlsbFormat/Biff12_structures/CodeName.cpp \
    ../Source/XlsbFormat/Biff12_structures/ACProductVersion.cpp \
    ../Source/XlsbFormat/Biff12_structures/FRTProductVersion.cpp \
    ../Source/XlsbFormat/Biff12_structures/RelID.cpp \
    ../Source/XlsbFormat/Biff12_structures/BookProtectionFlags.cpp \
    ../Source/XlsbFormat/Biff12_structures/ColSpan.cpp \
    ../Source/XlsbFormat/Biff12_structures/Cell.cpp \
    ../Source/XlsbFormat/Biff12_structures/GrbitFmla.cpp \
    ../Source/XlsbFormat/Biff12_structures/SxOs.cpp \
    ../Source/XlsbFormat/Biff12_structures/SxSu.cpp \
    ../Source/XlsbFormat/Biff12_structures/UncheckedSqRfX.cpp \
    ../Source/XlsbFormat/Biff12_structures/CFType.cpp \
    ../Source/XlsbFormat/Biff12_structures/CFTemp.cpp \
    ../Source/XlsbFormat/Biff12_structures/CFOper.cpp \
    ../Source/XlsbFormat/Biff12_structures/CFTextOper.cpp \
    ../Source/XlsbFormat/Biff12_structures/CFDateOper.cpp \
    ../Source/XlsbFormat/Biff12_structures/CFVOtype.cpp \
    ../Source/XlsbFormat/Biff12_structures/CFVOType14.cpp \
    ../Source/XlsbFormat/Biff12_structures/FRTBlank.cpp \
    ../Source/XlsbFormat/Biff12_structures/RichStr.cpp \
    ../Source/XlsbFormat/Biff12_structures/StrRun.cpp \
    ../Source/XlsbFormat/Biff12_structures/PhRun.cpp \
    ../Source/XlsbFormat/Biff12_structures/GradientStop.cpp \
    ../Source/XlsbFormat/Biff12_structures/Blxf.cpp \
    ../Source/XlsbFormat/Biff12_structures/FRTHeader.cpp \
    ../Source/XlsbFormat/Biff12_structures/FRTRefs.cpp \
    ../Source/XlsbFormat/Biff12_structures/FRTRef.cpp \
    ../Source/XlsbFormat/Biff12_structures/FRTSqrefs.cpp \
    ../Source/XlsbFormat/Biff12_structures/FRTSqref.cpp \
    ../Source/XlsbFormat/Biff12_structures/FRTFormulas.cpp \
    ../Source/XlsbFormat/Biff12_structures/FRTFormula.cpp \
    ../Source/XlsbFormat/Biff12_structures/FRTParsedFormula.cpp \
    ../Source/XlsbFormat/Biff12_structures/FRTRelID.cpp \
    ../Source/XlsbFormat/Biff12_structures/ListType.cpp \
    ../Source/XlsbFormat/Biff12_structures/XmlDataType.cpp \
    ../Source/XlsbFormat/Biff12_structures/ListTotalRowFunction.cpp \
    ../Source/XlsbFormat/Biff12_structures/DValStrings.cpp \
    ../Source/XlsbFormat/Biff12_structures/DBType.cpp \
    ../Source/XlsbFormat/Biff12_structures/CmdType.cpp \
    ../Source/XlsbFormat/Biff12_structures/PCDISrvFmt.cpp \
    ../Source/XlsbFormat/Biff12_structures/SrvFmtCV.cpp \
    ../Source/XlsbFormat/Biff12_structures/ECTxtWizData.cpp \
    ../Source/XlsbFormat/Biff12_structures/ECTwFldInfoData.cpp \
    ../Source/XlsbFormat/Biff12_structures/PCDCalcMemCommon.cpp \
    ../Source/XlsbFormat/Biff12_structures/IIFtab.cpp \
    ../Source/XlsbFormat/Biff12_structures/ParameterParsedFormula.cpp \
    ../Source/XlsbFormat/Biff12_structures/SlicerCachePivotTable.cpp \
    ../Source/XlsbFormat/Biff12_structures/SlicerCacheNativeItemStruct.cpp \
    ../Source/XlsbFormat/Biff12_structures/SlicerCacheLevelData.cpp \
    ../Source/XlsbFormat/Biff12_structures/RangeProtectionTitleSDRel.cpp \
    ../Source/XlsbFormat/Biff12_structures/Tws.cpp \
### Biff12_unions
    ../Source/XlsbFormat/Biff12_unions/FRT.cpp \
    ../Source/XlsbFormat/Biff12_unions/ACUID.cpp \
    ../Source/XlsbFormat/Biff12_unions/ACABSPATH.cpp \
    ../Source/XlsbFormat/Biff12_unions/BOOKVIEWS_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/BUNDLESHS.cpp \
    ../Source/XlsbFormat/Biff12_unions/FNGROUP_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/EXTERNALS.cpp \
    ../Source/XlsbFormat/Biff12_unions/SUP.cpp \
    ../Source/XlsbFormat/Biff12_unions/SUPSAME_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/SUPADDIN_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/COLINFOS.cpp \
    ../Source/XlsbFormat/Biff12_unions/HLINKS.cpp \
    ../Source/XlsbFormat/Biff12_unions/MERGECELLS.cpp \
    ../Source/XlsbFormat/Biff12_unions/CELLTABLE.cpp \
    ../Source/XlsbFormat/Biff12_unions/ACCELLTABLE.cpp \
    ../Source/XlsbFormat/Biff12_unions/CELL_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/DATACELL.cpp \
    ../Source/XlsbFormat/Biff12_unions/FMLACELL.cpp \
    ../Source/XlsbFormat/Biff12_unions/SHRFMLACELL.cpp \
    ../Source/XlsbFormat/Biff12_unions/TABLECELL.cpp \
    ../Source/XlsbFormat/Biff12_unions/CELLMETA_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/WSVIEW2.cpp \
    ../Source/XlsbFormat/Biff12_unions/WSVIEWS2.cpp \
    ../Source/XlsbFormat/Biff12_unions/LISTPARTS.cpp \
    ../Source/XlsbFormat/Biff12_unions/RICHSORTCONDITION.cpp \
    ../Source/XlsbFormat/Biff12_unions/SORTCOND14.cpp \
    ../Source/XlsbFormat/Biff12_unions/ACSORTCONDS.cpp \
    ../Source/XlsbFormat/Biff12_unions/SORTCOND.cpp \
    ../Source/XlsbFormat/Biff12_unions/SORTCONDS.cpp \
    ../Source/XlsbFormat/Biff12_unions/SORTSTATE.cpp \
    ../Source/XlsbFormat/Biff12_unions/uCFVO.cpp \
    ../Source/XlsbFormat/Biff12_unions/ICONSET.cpp \
    ../Source/XlsbFormat/Biff12_unions/DATABAR.cpp \
    ../Source/XlsbFormat/Biff12_unions/COLORSCALE.cpp \
    ../Source/XlsbFormat/Biff12_unions/FRTCFRULE.cpp \
    ../Source/XlsbFormat/Biff12_unions/CFRULE.cpp \
    ../Source/XlsbFormat/Biff12_unions/CONDITIONALFORMATTING_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/CFRULE14.cpp \
    ../Source/XlsbFormat/Biff12_unions/CONDITIONALFORMATTING14.cpp \
    ../Source/XlsbFormat/Biff12_unions/COLORSCALE14.cpp \
    ../Source/XlsbFormat/Biff12_unions/DATABAR14.cpp \
    ../Source/XlsbFormat/Biff12_unions/ICONSET14.cpp \
    ../Source/XlsbFormat/Biff12_unions/uCFVO14.cpp \
    ../Source/XlsbFormat/Biff12_unions/CONDITIONALFORMATTINGS.cpp \
    ../Source/XlsbFormat/Biff12_unions/FRTWORKSHEET.cpp \
    ../Source/XlsbFormat/Biff12_unions/SHAREDSTRINGS.cpp \
    ../Source/XlsbFormat/Biff12_unions/ACFMT.cpp \
    ../Source/XlsbFormat/Biff12_unions/FMTS.cpp \
    ../Source/XlsbFormat/Biff12_unions/FONTS.cpp \
    ../Source/XlsbFormat/Biff12_unions/ACFONTS.cpp \
    ../Source/XlsbFormat/Biff12_unions/FILLS.cpp \
    ../Source/XlsbFormat/Biff12_unions/BORDERS.cpp \
    ../Source/XlsbFormat/Biff12_unions/CELLSTYLEXFS.cpp \
    ../Source/XlsbFormat/Biff12_unions/CELLXFS.cpp \
    ../Source/XlsbFormat/Biff12_unions/STYLES.cpp \
    ../Source/XlsbFormat/Biff12_unions/DXFS.cpp \
    ../Source/XlsbFormat/Biff12_unions/DXF.cpp \
    ../Source/XlsbFormat/Biff12_unions/FRTDXF.cpp \
    ../Source/XlsbFormat/Biff12_unions/TABLESTYLES.cpp \
    ../Source/XlsbFormat/Biff12_unions/TABLESTYLE.cpp \
    ../Source/XlsbFormat/Biff12_unions/MRUCOLORS.cpp \
    ../Source/XlsbFormat/Biff12_unions/INDEXEDCOLORS.cpp \
    ../Source/XlsbFormat/Biff12_unions/COLORPALETTE.cpp \
    ../Source/XlsbFormat/Biff12_unions/DXF14S.cpp \
    ../Source/XlsbFormat/Biff12_unions/DXFS15.cpp \
    ../Source/XlsbFormat/Biff12_unions/TIMELINESTYLE.cpp \
    ../Source/XlsbFormat/Biff12_unions/TIMELINESTYLES.cpp \
    ../Source/XlsbFormat/Biff12_unions/STYLESHEET15.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERSTYLE.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERSTYLES.cpp \
    ../Source/XlsbFormat/Biff12_unions/STYLESHEET14.cpp \
    ../Source/XlsbFormat/Biff12_unions/FRTSTYLESHEET.cpp \
    ../Source/XlsbFormat/Biff12_unions/COMMENT.cpp \
    ../Source/XlsbFormat/Biff12_unions/COMMENTLIST.cpp \
    ../Source/XlsbFormat/Biff12_unions/COMMENTAUTHORS.cpp \
    ../Source/XlsbFormat/Biff12_unions/FRTTABLE.cpp \
    ../Source/XlsbFormat/Biff12_unions/TABLE_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/LISTCOLS.cpp \
    ../Source/XlsbFormat/Biff12_unions/LISTCOL.cpp \
    ../Source/XlsbFormat/Biff12_unions/LISTXMLCPR.cpp \
    ../Source/XlsbFormat/Biff12_unions/AUTOFILTER.cpp \
    ../Source/XlsbFormat/Biff12_unions/FILTERCOLUMN.cpp \
    ../Source/XlsbFormat/Biff12_unions/ACICONFILTER.cpp \
    ../Source/XlsbFormat/Biff12_unions/ACFILTERCONTENT.cpp \
    ../Source/XlsbFormat/Biff12_unions/FILTERS.cpp \
    ../Source/XlsbFormat/Biff12_unions/CUSTOMFILTERS.cpp \
    ../Source/XlsbFormat/Biff12_unions/ACCUSTOMFILTER.cpp \
    ../Source/XlsbFormat/Biff12_unions/ACFILTERS.cpp \
    ../Source/XlsbFormat/Biff12_unions/RICHFILTERCONTENT.cpp \
    ../Source/XlsbFormat/Biff12_unions/RICHFILTERS.cpp \
    ../Source/XlsbFormat/Biff12_unions/CUSTOMRICHFILTERS.cpp \
    ../Source/XlsbFormat/Biff12_unions/HEADERFOOTER.cpp \
    ../Source/XlsbFormat/Biff12_unions/ACDVALLIST.cpp \
    ../Source/XlsbFormat/Biff12_unions/DVALS.cpp \
    ../Source/XlsbFormat/Biff12_unions/DVALS14.cpp \    
    ../Source/XlsbFormat/Biff12_unions/QSI.cpp \
    ../Source/XlsbFormat/Biff12_unions/QSIR.cpp \
    ../Source/XlsbFormat/Biff12_unions/QSIFS.cpp \
    ../Source/XlsbFormat/Biff12_unions/QSIF.cpp \
    ../Source/XlsbFormat/Biff12_unions/DELETEDNAMES.cpp \
    ../Source/XlsbFormat/Biff12_unions/DELETEDNAME.cpp \
    ../Source/XlsbFormat/Biff12_unions/FRTQSI.cpp \
    ../Source/XlsbFormat/Biff12_unions/EXTCONNECTIONS.cpp \
    ../Source/XlsbFormat/Biff12_unions/EXTCONNECTION.cpp \
    ../Source/XlsbFormat/Biff12_unions/ECDBPROPS.cpp \
    ../Source/XlsbFormat/Biff12_unions/ECOLAPPROPS.cpp \
    ../Source/XlsbFormat/Biff12_unions/ECWEBPROPS.cpp \
    ../Source/XlsbFormat/Biff12_unions/ECWPTABLES.cpp \
    ../Source/XlsbFormat/Biff12_unions/PCDI.cpp \
    ../Source/XlsbFormat/Biff12_unions/ECTXTWIZ.cpp \
    ../Source/XlsbFormat/Biff12_unions/ECTWFLDINFOLST.cpp \
    ../Source/XlsbFormat/Biff12_unions/ECPARAMS.cpp \
    ../Source/XlsbFormat/Biff12_unions/ECPARAM.cpp \
    ../Source/XlsbFormat/Biff12_unions/PCDCALCMEMSEXT.cpp \
    ../Source/XlsbFormat/Biff12_unions/PCDCALCMEM14.cpp \
    ../Source/XlsbFormat/Biff12_unions/PCDCALCMEMEXT.cpp \
    ../Source/XlsbFormat/Biff12_unions/SXTUPLESET.cpp \
    ../Source/XlsbFormat/Biff12_unions/SXTUPLESETHEADER.cpp \
    ../Source/XlsbFormat/Biff12_unions/SXTUPLESETDATA.cpp \
    ../Source/XlsbFormat/Biff12_unions/SXTUPLESETROW.cpp \
    ../Source/XlsbFormat/Biff12_unions/PCDCALCMEM15_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/FRTEXTCONNECTIONS.cpp \
    ../Source/XlsbFormat/Biff12_unions/EXTCONN14.cpp \
    ../Source/XlsbFormat/Biff12_unions/EXTCONN15.cpp \
    ../Source/XlsbFormat/Biff12_unions/OLEDBPR15.cpp \
    ../Source/XlsbFormat/Biff12_unions/DBTABLES15.cpp \
    ../Source/XlsbFormat/Biff12_unions/DATAFEEDPR15.cpp \
    ../Source/XlsbFormat/Biff12_unions/TEXTPR15_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/ECTXTWIZ15.cpp \
    ../Source/XlsbFormat/Biff12_unions/ECTWFLDINFOLST15.cpp \
    ../Source/XlsbFormat/Biff12_unions/SPARKLINEGROUP.cpp \
    ../Source/XlsbFormat/Biff12_unions/SPARKLINEGROUPS.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERS.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICER_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHECROSSFILTEREXT.cpp \
    ../Source/XlsbFormat/Biff12_unions/TABLESLICERCACHE.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHEBOOKPIVOTTABLES_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/FRTSLICERCACHE.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHENATIVEITEMS.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHESELECTIONS.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHESIRANGE.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHESIRANGES.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHELEVELDATA_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHELEVELSDATA.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHEOLAPIMPL.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHE_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/TABLESLICEREX.cpp \
    ../Source/XlsbFormat/Biff12_unions/TABLESLICERSEX.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICEREX.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERSEX.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHESPIVOTCACHEIDS.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHESPIVOTCACHEID.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHEIDS.cpp \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHEID.cpp \
    ../Source/XlsbFormat/Biff12_unions/TABLESLICERCACHEIDS_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/TABLESLICERCACHEID_bu.cpp \
    ../Source/XlsbFormat/Biff12_unions/FRTWORKBOOK.cpp \
    ../Source/XlsbFormat/Biff12_unions/OLEOBJECTS.cpp \
    ../Source/XlsbFormat/Biff12_unions/ACTIVEXCONTROLS.cpp \
    ../Source/XlsbFormat/Biff12_unions/RWBRK.cpp \
    ../Source/XlsbFormat/Biff12_unions/COLBRK.cpp \
    ../Source/XlsbFormat/Biff12_unions/DCON.cpp \
    ../Source/XlsbFormat/Biff12_unions/DREFS.cpp \
    ../Source/XlsbFormat/Biff12_unions/CSVIEWS.cpp \
    ../Source/XlsbFormat/Biff12_unions/CSVIEW.cpp \
    ../Source/XlsbFormat/Biff12_unions/USERCSVIEWS.cpp \
    ../Source/XlsbFormat/Biff12_unions/USERCSVIEW.cpp \
    ../Source/XlsbFormat/Biff12_unions/WEBPUBITEMS.cpp \
    ../Source/XlsbFormat/Biff12_unions/WEBPUBITEM.cpp \
}
HEADERS += \
    ../Source/XlsbFormat/Biff12_unions/COMMENTS.h \
    ../Source/XlsbFormat/CommentsStream.h \
    ../Source/XlsbFormat/SharedStringsStream.h \
    ../Source/XlsbFormat/StylesStream.h \
    ../Source/XlsbFormat/WorkBookStream.h \
    ../Source/XlsbFormat/WorkSheetStream.h \
    ../Source/XlsbFormat/TableStream.h \
    ../Source/XlsbFormat/QueryTableStream.h \
    ../Source/XlsbFormat/ConnectionsStream.h \
    ../Source/XlsbFormat/SlicersStream.h \
    ../Source/XlsbFormat/SlicerCachesStream.h \
    ../Source/XlsbFormat/ChartSheetStream.h \
    ../Source/XlsbFormat/Xlsb.h \
    ../Source/XlsbFormat/XlsbElementsType.h \
### Biff12_records
    ../Source/XlsbFormat/Biff12_records/ACBegin.h \
    ../Source/XlsbFormat/Biff12_records/ACEnd.h \
    ../Source/XlsbFormat/Biff12_records/AbsPath15.h \
    ../Source/XlsbFormat/Biff12_records/BeginBook.h \
    ../Source/XlsbFormat/Biff12_records/BeginBookViews.h \
    ../Source/XlsbFormat/Biff12_records/BeginBorders.h \
    ../Source/XlsbFormat/Biff12_records/BeginBundleShs.h \
    ../Source/XlsbFormat/Biff12_records/BeginCFRule.h \
    ../Source/XlsbFormat/Biff12_records/BeginCFRule14.h \
    ../Source/XlsbFormat/Biff12_records/BeginCellStyleXFs.h \
    ../Source/XlsbFormat/Biff12_records/BeginCellXFs.h \
    ../Source/XlsbFormat/Biff12_records/BeginColInfos.h \
    ../Source/XlsbFormat/Biff12_records/BeginColorPalette.h \
    ../Source/XlsbFormat/Biff12_records/BeginColorScale.h \
    ../Source/XlsbFormat/Biff12_records/BeginColorScale14.h \
    ../Source/XlsbFormat/Biff12_records/BeginComment.h \
    ../Source/XlsbFormat/Biff12_records/BeginCommentAuthors.h \
    ../Source/XlsbFormat/Biff12_records/BeginCommentList.h \
    ../Source/XlsbFormat/Biff12_records/BeginComments.h \
    ../Source/XlsbFormat/Biff12_records/BeginConditionalFormatting.h \
    ../Source/XlsbFormat/Biff12_records/BeginConditionalFormatting14.h \
    ../Source/XlsbFormat/Biff12_records/BeginConditionalFormattings.h \
    ../Source/XlsbFormat/Biff12_records/BeginDXF14s.h \
    ../Source/XlsbFormat/Biff12_records/BeginDXFs.h \
    ../Source/XlsbFormat/Biff12_records/BeginDXFs15.h \
    ../Source/XlsbFormat/Biff12_records/BeginDatabar.h \
    ../Source/XlsbFormat/Biff12_records/BeginDatabar14.h \
    ../Source/XlsbFormat/Biff12_records/BeginExternals.h \
    ../Source/XlsbFormat/Biff12_records/BeginFills.h \
    ../Source/XlsbFormat/Biff12_records/BeginFmts.h \
    ../Source/XlsbFormat/Biff12_records/BeginFnGroup.h \
    ../Source/XlsbFormat/Biff12_records/BeginFonts.h \
    ../Source/XlsbFormat/Biff12_records/BeginIconSet.h \
    ../Source/XlsbFormat/Biff12_records/BeginIconSet14.h \
    ../Source/XlsbFormat/Biff12_records/BeginIndexedColors.h \
    ../Source/XlsbFormat/Biff12_records/BeginListParts.h \
    ../Source/XlsbFormat/Biff12_records/BeginMRUColors.h \
    ../Source/XlsbFormat/Biff12_records/BeginMergeCells.h \
    ../Source/XlsbFormat/Biff12_records/BeginRichSortCondition.h \
    ../Source/XlsbFormat/Biff12_records/BeginSheet.h \
    ../Source/XlsbFormat/Biff12_records/BeginSheetData.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerStyle.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerStyleElements.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerStyles.h \
    ../Source/XlsbFormat/Biff12_records/BeginSortCond.h \
    ../Source/XlsbFormat/Biff12_records/BeginSortCond14.h \
    ../Source/XlsbFormat/Biff12_records/BeginSst.h \
    ../Source/XlsbFormat/Biff12_records/BeginStyleSheet.h \
    ../Source/XlsbFormat/Biff12_records/BeginStyleSheetExt14.h \
    ../Source/XlsbFormat/Biff12_records/BeginStyles.h \
    ../Source/XlsbFormat/Biff12_records/BeginTimelineStyle.h \
    ../Source/XlsbFormat/Biff12_records/BeginTimelineStyleElements.h \
    ../Source/XlsbFormat/Biff12_records/BeginTimelineStyleSheetExt15.h \
    ../Source/XlsbFormat/Biff12_records/BeginTimelineStyles.h \
    ../Source/XlsbFormat/Biff12_records/BeginWsViews.h \
    ../Source/XlsbFormat/Biff12_records/BookProtection.h \
    ../Source/XlsbFormat/Biff12_records/BookProtectionIso.h \
    ../Source/XlsbFormat/Biff12_records/BookView.h \
    ../Source/XlsbFormat/Biff12_records/Border.h \
    ../Source/XlsbFormat/Biff12_records/BundleSh.h \
    ../Source/XlsbFormat/Biff12_records/CFIcon.h \
    ../Source/XlsbFormat/Biff12_records/CFRuleExt.h \
    ../Source/XlsbFormat/Biff12_records/CFVO.h \
    ../Source/XlsbFormat/Biff12_records/CFVO14.h \
    ../Source/XlsbFormat/Biff12_records/CalcProp.h \
    ../Source/XlsbFormat/Biff12_records/Cell.h \
    ../Source/XlsbFormat/Biff12_records/CellMeta.h \
    ../Source/XlsbFormat/Biff12_records/Color.h \
    ../Source/XlsbFormat/Biff12_records/Color14.h \
    ../Source/XlsbFormat/Biff12_records/CommentAuthor.h \
    ../Source/XlsbFormat/Biff12_records/CommentText.h \
    ../Source/XlsbFormat/Biff12_records/CommonRecords.h \
    ../Source/XlsbFormat/Biff12_records/Drawing.h \
    ../Source/XlsbFormat/Biff12_records/EndBook.h \
    ../Source/XlsbFormat/Biff12_records/EndBookViews.h \
    ../Source/XlsbFormat/Biff12_records/EndBorders.h \
    ../Source/XlsbFormat/Biff12_records/EndBundleShs.h \
    ../Source/XlsbFormat/Biff12_records/EndCFRule.h \
    ../Source/XlsbFormat/Biff12_records/EndCFRule14.h \
    ../Source/XlsbFormat/Biff12_records/EndCellStyleXFs.h \
    ../Source/XlsbFormat/Biff12_records/EndCellXFs.h \
    ../Source/XlsbFormat/Biff12_records/EndColInfos.h \
    ../Source/XlsbFormat/Biff12_records/EndColorPalette.h \
    ../Source/XlsbFormat/Biff12_records/EndColorScale.h \
    ../Source/XlsbFormat/Biff12_records/EndColorScale14.h \
    ../Source/XlsbFormat/Biff12_records/EndComment.h \
    ../Source/XlsbFormat/Biff12_records/EndCommentAuthors.h \
    ../Source/XlsbFormat/Biff12_records/EndCommentList.h \
    ../Source/XlsbFormat/Biff12_records/EndComments.h \
    ../Source/XlsbFormat/Biff12_records/EndConditionalFormatting.h \
    ../Source/XlsbFormat/Biff12_records/EndConditionalFormatting14.h \
    ../Source/XlsbFormat/Biff12_records/EndConditionalFormattings.h \
    ../Source/XlsbFormat/Biff12_records/EndDXF14s.h \
    ../Source/XlsbFormat/Biff12_records/EndDXFs.h \
    ../Source/XlsbFormat/Biff12_records/EndDXFs15.h \
    ../Source/XlsbFormat/Biff12_records/EndDatabar.h \
    ../Source/XlsbFormat/Biff12_records/EndDatabar14.h \
    ../Source/XlsbFormat/Biff12_records/EndExternals.h \
    ../Source/XlsbFormat/Biff12_records/EndFills.h \
    ../Source/XlsbFormat/Biff12_records/EndFmts.h \
    ../Source/XlsbFormat/Biff12_records/EndFnGroup.h \
    ../Source/XlsbFormat/Biff12_records/EndFonts.h \
    ../Source/XlsbFormat/Biff12_records/EndIconSet.h \
    ../Source/XlsbFormat/Biff12_records/EndIconSet14.h \
    ../Source/XlsbFormat/Biff12_records/EndIndexedColors.h \
    ../Source/XlsbFormat/Biff12_records/EndListParts.h \
    ../Source/XlsbFormat/Biff12_records/EndMRUColors.h \
    ../Source/XlsbFormat/Biff12_records/EndMergeCells.h \
    ../Source/XlsbFormat/Biff12_records/EndRichSortCondition.h \
    ../Source/XlsbFormat/Biff12_records/EndSheet.h \
    ../Source/XlsbFormat/Biff12_records/EndSheetData.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerStyle.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerStyleElements.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerStyles.h \
    ../Source/XlsbFormat/Biff12_records/EndSortCond.h \
    ../Source/XlsbFormat/Biff12_records/EndSortCond14.h \
    ../Source/XlsbFormat/Biff12_records/EndSortState.h \
    ../Source/XlsbFormat/Biff12_records/EndSst.h \
    ../Source/XlsbFormat/Biff12_records/EndStyleSheet.h \
    ../Source/XlsbFormat/Biff12_records/EndStyleSheetExt14.h \
    ../Source/XlsbFormat/Biff12_records/EndStyles.h \
    ../Source/XlsbFormat/Biff12_records/EndTableStyle.h \
    ../Source/XlsbFormat/Biff12_records/EndTableStyles.h \
    ../Source/XlsbFormat/Biff12_records/EndTimelineStyle.h \
    ../Source/XlsbFormat/Biff12_records/EndTimelineStyleElements.h \
    ../Source/XlsbFormat/Biff12_records/EndTimelineStyleSheetExt15.h \
    ../Source/XlsbFormat/Biff12_records/EndTimelineStyles.h \
    ../Source/XlsbFormat/Biff12_records/EndWsView.h \
    ../Source/XlsbFormat/Biff12_records/EndWsViews.h \
    ../Source/XlsbFormat/Biff12_records/FRTBegin.h \
    ../Source/XlsbFormat/Biff12_records/FRTEnd.h \
    ../Source/XlsbFormat/Biff12_records/FileSharingIso.h \
    ../Source/XlsbFormat/Biff12_records/FileVersion.h \
    ../Source/XlsbFormat/Biff12_records/Fill.h \
    ../Source/XlsbFormat/Biff12_records/Fmla.h \
    ../Source/XlsbFormat/Biff12_records/Fmt.h \
    ../Source/XlsbFormat/Biff12_records/FnGroup.h \
    ../Source/XlsbFormat/Biff12_records/HLink.h \
    ../Source/XlsbFormat/Biff12_records/IndexedColor.h \
    ../Source/XlsbFormat/Biff12_records/KnownFonts.h \
    ../Source/XlsbFormat/Biff12_records/LegacyDrawing.h \
    ../Source/XlsbFormat/Biff12_records/LegacyDrawingHF.h \
    ../Source/XlsbFormat/Biff12_records/ListPart.h \
    ../Source/XlsbFormat/Biff12_records/MRUColor.h \
    ../Source/XlsbFormat/Biff12_records/MergeCell.h \
    ../Source/XlsbFormat/Biff12_records/OleSize.h \
    ../Source/XlsbFormat/Biff12_records/PlaceholderName.h \
    ../Source/XlsbFormat/Biff12_records/RwDescent.h \
    ../Source/XlsbFormat/Biff12_records/SSTItem.h \
    ../Source/XlsbFormat/Biff12_records/SheetProtection.h \
    ../Source/XlsbFormat/Biff12_records/SheetProtectionIso.h \
    ../Source/XlsbFormat/Biff12_records/SlicerStyleElement.h \
    ../Source/XlsbFormat/Biff12_records/Style.h \
    ../Source/XlsbFormat/Biff12_records/SupAddin.h \
    ../Source/XlsbFormat/Biff12_records/SupBookSrc.h \
    ../Source/XlsbFormat/Biff12_records/SupSame.h \
    ../Source/XlsbFormat/Biff12_records/SupSelf.h \
    ../Source/XlsbFormat/Biff12_records/TimelineStyleElement.h \
    ../Source/XlsbFormat/Biff12_records/Uid.h \
    ../Source/XlsbFormat/Biff12_records/ValueMeta.h \
    ../Source/XlsbFormat/Biff12_records/WbProp.h \
    ../Source/XlsbFormat/Biff12_records/WsDim.h \
    ../Source/XlsbFormat/Biff12_records/WsFmtInfo.h \
    ../Source/XlsbFormat/Biff12_records/TableStyleClient.h \
    ../Source/XlsbFormat/Biff12_records/BeginList.h \
    ../Source/XlsbFormat/Biff12_records/EndList.h \
    ../Source/XlsbFormat/Biff12_records/BeginListCols.h \
    ../Source/XlsbFormat/Biff12_records/ListCCFmla.h \
    ../Source/XlsbFormat/Biff12_records/ListTrFmla.h \
    ../Source/XlsbFormat/Biff12_records/BeginListXmlCPr.h \
    ../Source/XlsbFormat/Biff12_records/BeginListCol.h \
    ../Source/XlsbFormat/Biff12_records/EndListCols.h \
    ../Source/XlsbFormat/Biff12_records/EndListCol.h \
    ../Source/XlsbFormat/Biff12_records/BeginAFilter.h \
    ../Source/XlsbFormat/Biff12_records/EndListXmlCPr.h \
    ../Source/XlsbFormat/Biff12_records/List14.h \
    ../Source/XlsbFormat/Biff12_records/Top10Filter.h \
    ../Source/XlsbFormat/Biff12_records/Top10RichFilter.h \
    ../Source/XlsbFormat/Biff12_records/EndAFilter.h \
    ../Source/XlsbFormat/Biff12_records/EndFilterColumn.h \
    ../Source/XlsbFormat/Biff12_records/IconFilter.h \
    ../Source/XlsbFormat/Biff12_records/IconFilter14.h \
    ../Source/XlsbFormat/Biff12_records/ColorFilter.h \
    ../Source/XlsbFormat/Biff12_records/DynamicFilter.h \
    ../Source/XlsbFormat/Biff12_records/BeginFilterColumn.h \
    ../Source/XlsbFormat/Biff12_records/AFilterDateGroupItem.h \
    ../Source/XlsbFormat/Biff12_records/RichFilterDateGroupItem.h \
    ../Source/XlsbFormat/Biff12_records/Filter.h \
    ../Source/XlsbFormat/Biff12_records/CustomFilter.h \
    ../Source/XlsbFormat/Biff12_records/BeginCustomFilters.h \
    ../Source/XlsbFormat/Biff12_records/CustomFilter14.h \
    ../Source/XlsbFormat/Biff12_records/EndCustomFilters.h \
    ../Source/XlsbFormat/Biff12_records/BeginCustomFilters14.h \
    ../Source/XlsbFormat/Biff12_records/Filter14.h \
    ../Source/XlsbFormat/Biff12_records/BeginFilters.h \
    ../Source/XlsbFormat/Biff12_records/EndFilters.h \
    ../Source/XlsbFormat/Biff12_records/DynamicRichFilter.h \
    ../Source/XlsbFormat/Biff12_records/BeginRichFilterColumn.h \
    ../Source/XlsbFormat/Biff12_records/EndRichFilterColumn.h \
    ../Source/XlsbFormat/Biff12_records/RichFilter.h \
    ../Source/XlsbFormat/Biff12_records/BeginRichFilters.h \
    ../Source/XlsbFormat/Biff12_records/EndRichFilters.h \
    ../Source/XlsbFormat/Biff12_records/CustomRichFilter.h \
    ../Source/XlsbFormat/Biff12_records/BeginCustomRichFilters.h \
    ../Source/XlsbFormat/Biff12_records/EndCustomRichFilters.h \
    ../Source/XlsbFormat/Biff12_records/Margins.h \
    ../Source/XlsbFormat/Biff12_records/PrintOptions.h \
    ../Source/XlsbFormat/Biff12_records/BeginHeaderFooter.h \
    ../Source/XlsbFormat/Biff12_records/EndHeaderFooter.h \
    ../Source/XlsbFormat/Biff12_records/BeginDVals.h \
    ../Source/XlsbFormat/Biff12_records/EndDVals.h \
    ../Source/XlsbFormat/Biff12_records/DValList.h \
    ../Source/XlsbFormat/Biff12_records/BeginDVals14.h \
    ../Source/XlsbFormat/Biff12_records/EndDVals14.h \
    ../Source/XlsbFormat/Biff12_records/EndQSI.h \
    ../Source/XlsbFormat/Biff12_records/EndQSIF.h \
    ../Source/XlsbFormat/Biff12_records/EndQSIR.h \
    ../Source/XlsbFormat/Biff12_records/BeginQSIFs.h \
    ../Source/XlsbFormat/Biff12_records/EndQSIFs.h \
    ../Source/XlsbFormat/Biff12_records/BeginDeletedNames.h \
    ../Source/XlsbFormat/Biff12_records/EndDeletedNames.h \
    ../Source/XlsbFormat/Biff12_records/BeginDeletedName.h \
    ../Source/XlsbFormat/Biff12_records/EndDeletedName.h \
    ../Source/XlsbFormat/Biff12_records/Qsi15.h \
    ../Source/XlsbFormat/Biff12_records/BeginExtConnections.h \
    ../Source/XlsbFormat/Biff12_records/EndExtConnections.h \
    ../Source/XlsbFormat/Biff12_records/BeginExtConnection.h \
    ../Source/XlsbFormat/Biff12_records/EndExtConnection.h \
    ../Source/XlsbFormat/Biff12_records/BeginECDbProps.h \
    ../Source/XlsbFormat/Biff12_records/EndECDbProps.h \
    ../Source/XlsbFormat/Biff12_records/BeginECOlapProps.h \
    ../Source/XlsbFormat/Biff12_records/EndECOlapProps.h \
    ../Source/XlsbFormat/Biff12_records/BeginECWebProps.h \
    ../Source/XlsbFormat/Biff12_records/EndECWebProps.h \
    ../Source/XlsbFormat/Biff12_records/BeginEcWpTables.h \
    ../Source/XlsbFormat/Biff12_records/EndECWPTables.h \
    ../Source/XlsbFormat/Biff12_records/PCDIMissing.h \
    ../Source/XlsbFormat/Biff12_records/PCDIIndex.h \
    ../Source/XlsbFormat/Biff12_records/PCDIString.h \
    ../Source/XlsbFormat/Biff12_records/BeginECTxtWiz.h \
    ../Source/XlsbFormat/Biff12_records/EndECTxtWiz.h \
    ../Source/XlsbFormat/Biff12_records/BeginECTWFldInfoLst.h \
    ../Source/XlsbFormat/Biff12_records/BeginECTwFldInfo.h \
    ../Source/XlsbFormat/Biff12_records/EndECTWFldInfoLst.h \
    ../Source/XlsbFormat/Biff12_records/BeginECParams.h \
    ../Source/XlsbFormat/Biff12_records/EndECParams.h \
    ../Source/XlsbFormat/Biff12_records/BeginECParam.h \
    ../Source/XlsbFormat/Biff12_records/EndECParam.h \
    ../Source/XlsbFormat/Biff12_records/BeginPCDCalcMemsExt.h \
    ../Source/XlsbFormat/Biff12_records/EndPCDCalcMemsExt.h \
    ../Source/XlsbFormat/Biff12_records/BeginPCDCalcMem14.h \
    ../Source/XlsbFormat/Biff12_records/EndPCDCalcMem14.h \
    ../Source/XlsbFormat/Biff12_records/BeginPCDCalcMemExt.h \
    ../Source/XlsbFormat/Biff12_records/EndPCDCalcMemExt.h \
    ../Source/XlsbFormat/Biff12_records/BeginSXTupleSet.h \
    ../Source/XlsbFormat/Biff12_records/EndSXTupleSet.h \
    ../Source/XlsbFormat/Biff12_records/BeginSXTupleSetHeader.h \
    ../Source/XlsbFormat/Biff12_records/EndSXTupleSetHeader.h \
    ../Source/XlsbFormat/Biff12_records/SXTupleSetHeaderItem.h \
    ../Source/XlsbFormat/Biff12_records/BeginSXTupleSetData.h \
    ../Source/XlsbFormat/Biff12_records/EndSXTupleSetData.h \
    ../Source/XlsbFormat/Biff12_records/BeginSXTupleSetRow.h \
    ../Source/XlsbFormat/Biff12_records/EndSXTupleSetData.h \
    ../Source/XlsbFormat/Biff12_records/BeginSXTupleSetRow.h \
    ../Source/XlsbFormat/Biff12_records/SXTupleSetRowItem.h \
    ../Source/XlsbFormat/Biff12_records/EndSXTupleSetRow.h \
    ../Source/XlsbFormat/Biff12_records/PCDCalcMem15.h \
    ../Source/XlsbFormat/Biff12_records/BeginExtConn14.h \
    ../Source/XlsbFormat/Biff12_records/EndExtConn14.h \
    ../Source/XlsbFormat/Biff12_records/BeginExtConn15.h \
    ../Source/XlsbFormat/Biff12_records/RangePr15.h \
    ../Source/XlsbFormat/Biff12_records/EndExtConn15.h \
    ../Source/XlsbFormat/Biff12_records/BeginOledbPr15.h \
    ../Source/XlsbFormat/Biff12_records/DbCommand15.h \
    ../Source/XlsbFormat/Biff12_records/EndOledbPr15.h \
    ../Source/XlsbFormat/Biff12_records/BeginDbTables15.h \
    ../Source/XlsbFormat/Biff12_records/DbTable15.h \
    ../Source/XlsbFormat/Biff12_records/EndDbTables15.h \
    ../Source/XlsbFormat/Biff12_records/BeginDataFeedPr15.h \
    ../Source/XlsbFormat/Biff12_records/EndDataFeedPr15.h \
    ../Source/XlsbFormat/Biff12_records/TextPr15.h \
    ../Source/XlsbFormat/Biff12_records/BeginECTxtWiz15.h \
    ../Source/XlsbFormat/Biff12_records/EndECTxtWiz15.h \
    ../Source/XlsbFormat/Biff12_records/BeginECTWFldInfoLst15.h \
    ../Source/XlsbFormat/Biff12_records/BeginECTwFldInfo15.h \
    ../Source/XlsbFormat/Biff12_records/EndECTWFldInfoLst15.h \
    ../Source/XlsbFormat/Biff12_records/BeginSparklineGroups.h \
    ../Source/XlsbFormat/Biff12_records/EndSparklineGroups.h \
    ../Source/XlsbFormat/Biff12_records/BeginSparklineGroup.h \
    ../Source/XlsbFormat/Biff12_records/EndSparklineGroup.h \
    ../Source/XlsbFormat/Biff12_records/BeginSparklines.h \
    ../Source/XlsbFormat/Biff12_records/Sparkline.h \
    ../Source/XlsbFormat/Biff12_records/EndSparklines.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicers.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicers.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicer.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicer.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCache.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheDef.h \
    ../Source/XlsbFormat/Biff12_records/SlicerCachePivotTables.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheDef.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCache.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheOlapImpl.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheOlapImpl.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheLevelsData.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheLevelsData.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheLevelData.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheLevelData.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheSiRanges.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheSiRanges.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheSiRange.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheSiRange.h \
    ../Source/XlsbFormat/Biff12_records/SlicerCacheOlapItem.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheSelections.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheSelections.h \
    ../Source/XlsbFormat/Biff12_records/SlicerCacheSelection.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheNative.h \
    ../Source/XlsbFormat/Biff12_records/SlicerCacheNativeItem.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheNative.h \
    ../Source/XlsbFormat/Biff12_records/SlicerCacheBookPivotTables.h \
    ../Source/XlsbFormat/Biff12_records/BeginTableSlicerCache.h \
    ../Source/XlsbFormat/Biff12_records/EndTableSlicerCache.h \
    ../Source/XlsbFormat/Biff12_records/SlicerCacheHideItemsWithNoData.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicersEx.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicersEx.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerEx.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerEx.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCachesPivotCacheIDs.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCachesPivotCacheIDs.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCachesPivotCacheID.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCachesPivotCacheID.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheIDs.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheIDs.h \
    ../Source/XlsbFormat/Biff12_records/BeginSlicerCacheID.h \
    ../Source/XlsbFormat/Biff12_records/EndSlicerCacheID.h \
    ../Source/XlsbFormat/Biff12_records/TableSlicerCacheIDs.h \
    ../Source/XlsbFormat/Biff12_records/TableSlicerCacheID.h \
    ../Source/XlsbFormat/Biff12_records/BeginOleObjects.h \
    ../Source/XlsbFormat/Biff12_records/OleObject.h \
    ../Source/XlsbFormat/Biff12_records/EndOleObjects.h \
    ../Source/XlsbFormat/Biff12_records/BeginActiveXControls.h \
    ../Source/XlsbFormat/Biff12_records/ActiveX.h \
    ../Source/XlsbFormat/Biff12_records/EndActiveXControls.h \
    ../Source/XlsbFormat/Biff12_records/WsProp.h \
    ../Source/XlsbFormat/Biff12_records/BkHim.h \
    ../Source/XlsbFormat/Biff12_records/BeginRwBrk.h \
    ../Source/XlsbFormat/Biff12_records/Brk.h \
    ../Source/XlsbFormat/Biff12_records/EndRwBrk.h \
    ../Source/XlsbFormat/Biff12_records/BeginColBrk.h \
    ../Source/XlsbFormat/Biff12_records/EndColBrk.h \
    ../Source/XlsbFormat/Biff12_records/RangeProtection.h \
    ../Source/XlsbFormat/Biff12_records/RangeProtectionIso.h \
    ../Source/XlsbFormat/Biff12_records/BeginDCon.h \
    ../Source/XlsbFormat/Biff12_records/EndDCon.h \
    ../Source/XlsbFormat/Biff12_records/BeginDRefs.h \
    ../Source/XlsbFormat/Biff12_records/DRef.h \
    ../Source/XlsbFormat/Biff12_records/EndDRefs.h \
    ../Source/XlsbFormat/Biff12_records/CsProp.h \
    ../Source/XlsbFormat/Biff12_records/CsProtection.h \
    ../Source/XlsbFormat/Biff12_records/CsProtectionIso.h \
    ../Source/XlsbFormat/Biff12_records/BeginCsViews.h \
    ../Source/XlsbFormat/Biff12_records/EndCsViews.h \
    ../Source/XlsbFormat/Biff12_records/EndCsView.h \
    ../Source/XlsbFormat/Biff12_records/BeginUserCsViews.h \
    ../Source/XlsbFormat/Biff12_records/EndUserCsViews.h \
    ../Source/XlsbFormat/Biff12_records/BeginUserCsView.h \
    ../Source/XlsbFormat/Biff12_records/EndUserCsView.h \
    ../Source/XlsbFormat/Biff12_records/BeginWebPubItems.h \
    ../Source/XlsbFormat/Biff12_records/EndWebPubItems.h \
    ../Source/XlsbFormat/Biff12_records/BeginWebPubItem.h \
    ../Source/XlsbFormat/Biff12_records/EndWebPubItem.h \
### Biff12_structures
    ../Source/XlsbFormat/Biff12_structures/ACProductVersion.h \
    ../Source/XlsbFormat/Biff12_structures/Blxf.h \
    ../Source/XlsbFormat/Biff12_structures/BookProtectionFlags.h \
    ../Source/XlsbFormat/Biff12_structures/CFDateOper.h \
    ../Source/XlsbFormat/Biff12_structures/CFOper.h \
    ../Source/XlsbFormat/Biff12_structures/CFTemp.h \
    ../Source/XlsbFormat/Biff12_structures/CFTextOper.h \
    ../Source/XlsbFormat/Biff12_structures/CFType.h \
    ../Source/XlsbFormat/Biff12_structures/CFVOType14.h \
    ../Source/XlsbFormat/Biff12_structures/CFVOtype.h \
    ../Source/XlsbFormat/Biff12_structures/Cell.h \
    ../Source/XlsbFormat/Biff12_structures/CellRangeRef.h \
    ../Source/XlsbFormat/Biff12_structures/CellRef.h \
    ../Source/XlsbFormat/Biff12_structures/CodeName.h \
    ../Source/XlsbFormat/Biff12_structures/ColSpan.h \
    ../Source/XlsbFormat/Biff12_structures/FRTBlank.h \
    ../Source/XlsbFormat/Biff12_structures/FRTFormula.h \
    ../Source/XlsbFormat/Biff12_structures/FRTFormulas.h \
    ../Source/XlsbFormat/Biff12_structures/FRTHeader.h \
    ../Source/XlsbFormat/Biff12_structures/FRTParsedFormula.h \
    ../Source/XlsbFormat/Biff12_structures/FRTProductVersion.h \
    ../Source/XlsbFormat/Biff12_structures/FRTRef.h \
    ../Source/XlsbFormat/Biff12_structures/FRTRefs.h \
    ../Source/XlsbFormat/Biff12_structures/FRTRelID.h \
    ../Source/XlsbFormat/Biff12_structures/FRTSqref.h \
    ../Source/XlsbFormat/Biff12_structures/FRTSqrefs.h \
    ../Source/XlsbFormat/Biff12_structures/GradientStop.h \
    ../Source/XlsbFormat/Biff12_structures/GrbitFmla.h \
    ../Source/XlsbFormat/Biff12_structures/IsoPasswordData.h \
    ../Source/XlsbFormat/Biff12_structures/LPByteBuf.h \
    ../Source/XlsbFormat/Biff12_structures/PhRun.h \
    ../Source/XlsbFormat/Biff12_structures/RelID.h \
    ../Source/XlsbFormat/Biff12_structures/RichStr.h \
    ../Source/XlsbFormat/Biff12_structures/StrRun.h \
    ../Source/XlsbFormat/Biff12_structures/SxOs.h \
    ../Source/XlsbFormat/Biff12_structures/SxSu.h \
    ../Source/XlsbFormat/Biff12_structures/UncheckedSqRfX.h \
    ../Source/XlsbFormat/Biff12_structures/XLWideString.h \
    ../Source/XlsbFormat/Biff12_structures/ListType.h \
    ../Source/XlsbFormat/Biff12_structures/XmlDataType.h \
    ../Source/XlsbFormat/Biff12_structures/ListTotalRowFunction.h \
    ../Source/XlsbFormat/Biff12_structures/DValStrings.h \
    ../Source/XlsbFormat/Biff12_structures/DBType.h \
    ../Source/XlsbFormat/Biff12_structures/CmdType.h \
    ../Source/XlsbFormat/Biff12_structures/PCDISrvFmt.h \
    ../Source/XlsbFormat/Biff12_structures/SrvFmtCV.h \
    ../Source/XlsbFormat/Biff12_structures/ECTxtWizData.h \
    ../Source/XlsbFormat/Biff12_structures/ECTwFldInfoData.h \
    ../Source/XlsbFormat/Biff12_structures/PCDCalcMemCommon.h \
    ../Source/XlsbFormat/Biff12_structures/IIFtab.h \
    ../Source/XlsbFormat/Biff12_structures/ParameterParsedFormula.h \
    ../Source/XlsbFormat/Biff12_structures/SlicerCachePivotTable.h \
    ../Source/XlsbFormat/Biff12_structures/SlicerCacheNativeItemStruct.h \
    ../Source/XlsbFormat/Biff12_structures/SlicerCacheLevelData.h \
    ../Source/XlsbFormat/Biff12_structures/RangeProtectionTitleSDRel.h \
    ../Source/XlsbFormat/Biff12_structures/Tws.h \
### Biff12_unions
    ../Source/XlsbFormat/Biff12_unions/ACABSPATH.h \
    ../Source/XlsbFormat/Biff12_unions/ACCELLTABLE.h \
    ../Source/XlsbFormat/Biff12_unions/ACFMT.h \
    ../Source/XlsbFormat/Biff12_unions/ACFONTS.h \
    ../Source/XlsbFormat/Biff12_unions/ACSORTCONDS.h \
    ../Source/XlsbFormat/Biff12_unions/ACUID.h \
    ../Source/XlsbFormat/Biff12_unions/BOOKVIEWS.h \
    ../Source/XlsbFormat/Biff12_unions/BORDERS.h \
    ../Source/XlsbFormat/Biff12_unions/BUNDLESHS.h \
    ../Source/XlsbFormat/Biff12_unions/CELL.h \
    ../Source/XlsbFormat/Biff12_unions/CELLMETA.h \
    ../Source/XlsbFormat/Biff12_unions/CELLSTYLEXFS.h \
    ../Source/XlsbFormat/Biff12_unions/CELLTABLE.h \
    ../Source/XlsbFormat/Biff12_unions/CELLXFS.h \
    ../Source/XlsbFormat/Biff12_unions/CFRULE.h \
    ../Source/XlsbFormat/Biff12_unions/CFRULE14.h \
    ../Source/XlsbFormat/Biff12_unions/COLINFOS.h \
    ../Source/XlsbFormat/Biff12_unions/COLORPALETTE.h \
    ../Source/XlsbFormat/Biff12_unions/COLORSCALE.h \
    ../Source/XlsbFormat/Biff12_unions/COLORSCALE14.h \
    ../Source/XlsbFormat/Biff12_unions/COMMENT.h \
    ../Source/XlsbFormat/Biff12_unions/COMMENTAUTHORS.h \
    ../Source/XlsbFormat/Biff12_unions/COMMENTLIST.h \
    ../Source/XlsbFormat/Biff12_unions/CONDITIONALFORMATTING.h \
    ../Source/XlsbFormat/Biff12_unions/CONDITIONALFORMATTING14.h \
    ../Source/XlsbFormat/Biff12_unions/CONDITIONALFORMATTINGS.h \
    ../Source/XlsbFormat/Biff12_unions/DATABAR.h \
    ../Source/XlsbFormat/Biff12_unions/DATABAR14.h \
    ../Source/XlsbFormat/Biff12_unions/DATACELL.h \
    ../Source/XlsbFormat/Biff12_unions/DXF.h \
    ../Source/XlsbFormat/Biff12_unions/DXF14S.h \
    ../Source/XlsbFormat/Biff12_unions/DXFS.h \
    ../Source/XlsbFormat/Biff12_unions/DXFS15.h \
    ../Source/XlsbFormat/Biff12_unions/EXTERNALS.h \
    ../Source/XlsbFormat/Biff12_unions/FILLS.h \
    ../Source/XlsbFormat/Biff12_unions/FMLACELL.h \
    ../Source/XlsbFormat/Biff12_unions/FMTS.h \
    ../Source/XlsbFormat/Biff12_unions/FNGROUP.h \
    ../Source/XlsbFormat/Biff12_unions/FONTS.h \
    ../Source/XlsbFormat/Biff12_unions/FRT.h \
    ../Source/XlsbFormat/Biff12_unions/FRTCFRULE.h \
    ../Source/XlsbFormat/Biff12_unions/FRTDXF.h \
    ../Source/XlsbFormat/Biff12_unions/FRTSTYLESHEET.h \
    ../Source/XlsbFormat/Biff12_unions/FRTWORKSHEET.h \
    ../Source/XlsbFormat/Biff12_unions/HLINKS.h \
    ../Source/XlsbFormat/Biff12_unions/ICONSET.h \
    ../Source/XlsbFormat/Biff12_unions/ICONSET14.h \
    ../Source/XlsbFormat/Biff12_unions/INDEXEDCOLORS.h \
    ../Source/XlsbFormat/Biff12_unions/LISTPARTS.h \
    ../Source/XlsbFormat/Biff12_unions/MERGECELLS.h \
    ../Source/XlsbFormat/Biff12_unions/MRUCOLORS.h \
    ../Source/XlsbFormat/Biff12_unions/RICHSORTCONDITION.h \
    ../Source/XlsbFormat/Biff12_unions/SHAREDSTRINGS.h \
    ../Source/XlsbFormat/Biff12_unions/SHRFMLACELL.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERSTYLE.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERSTYLES.h \
    ../Source/XlsbFormat/Biff12_unions/SORTCOND.h \
    ../Source/XlsbFormat/Biff12_unions/SORTCOND14.h \
    ../Source/XlsbFormat/Biff12_unions/SORTCONDS.h \
    ../Source/XlsbFormat/Biff12_unions/SORTSTATE.h \
    ../Source/XlsbFormat/Biff12_unions/STYLES.h \
    ../Source/XlsbFormat/Biff12_unions/STYLESHEET14.h \
    ../Source/XlsbFormat/Biff12_unions/STYLESHEET15.h \
    ../Source/XlsbFormat/Biff12_unions/SUP.h \
    ../Source/XlsbFormat/Biff12_unions/SUPADDIN.h \
    ../Source/XlsbFormat/Biff12_unions/SUPSAME.h \
    ../Source/XlsbFormat/Biff12_unions/TABLECELL.h \
    ../Source/XlsbFormat/Biff12_unions/TABLESTYLE.h \
    ../Source/XlsbFormat/Biff12_unions/TABLESTYLES.h \
    ../Source/XlsbFormat/Biff12_unions/TIMELINESTYLE.h \
    ../Source/XlsbFormat/Biff12_unions/TIMELINESTYLES.h \
    ../Source/XlsbFormat/Biff12_unions/WSVIEW2.h \
    ../Source/XlsbFormat/Biff12_unions/WSVIEWS2.h \
    ../Source/XlsbFormat/Biff12_unions/uCFVO.h \
    ../Source/XlsbFormat/Biff12_unions/uCFVO14.h \
    ../Source/XlsbFormat/Biff12_unions/FRTTABLE.h \
    ../Source/XlsbFormat/Biff12_unions/TABLE.h \
    ../Source/XlsbFormat/Biff12_unions/LISTCOLS.h \
    ../Source/XlsbFormat/Biff12_unions/LISTCOL.h \
    ../Source/XlsbFormat/Biff12_unions/LISTXMLCPR.h \
    ../Source/XlsbFormat/Biff12_unions/AUTOFILTER.h \
    ../Source/XlsbFormat/Biff12_unions/FILTERCOLUMN.h \
    ../Source/XlsbFormat/Biff12_unions/ACICONFILTER.h \
    ../Source/XlsbFormat/Biff12_unions/ACFILTERCONTENT.h \
    ../Source/XlsbFormat/Biff12_unions/FILTERS.h \
    ../Source/XlsbFormat/Biff12_unions/CUSTOMFILTERS.h \
    ../Source/XlsbFormat/Biff12_unions/ACCUSTOMFILTER.h \
    ../Source/XlsbFormat/Biff12_unions/ACFILTERS.h \
    ../Source/XlsbFormat/Biff12_unions/RICHFILTERCONTENT.h \
    ../Source/XlsbFormat/Biff12_unions/RICHFILTERS.h \
    ../Source/XlsbFormat/Biff12_unions/CUSTOMRICHFILTERS.h \
    ../Source/XlsbFormat/Biff12_unions/HEADERFOOTER.h \
    ../Source/XlsbFormat/Biff12_unions/ACDVALLIST.h \
    ../Source/XlsbFormat/Biff12_unions/DVALS.h \
    ../Source/XlsbFormat/Biff12_unions/DVALS14.h \
    ../Source/XlsbFormat/Biff12_unions/QSI.h \
    ../Source/XlsbFormat/Biff12_unions/QSIR.h \
    ../Source/XlsbFormat/Biff12_unions/QSIFS.h \
    ../Source/XlsbFormat/Biff12_unions/QSIF.h \
    ../Source/XlsbFormat/Biff12_unions/DELETEDNAMES.h \
    ../Source/XlsbFormat/Biff12_unions/DELETEDNAME.h \
    ../Source/XlsbFormat/Biff12_unions/FRTQSI.h \
    ../Source/XlsbFormat/Biff12_unions/EXTCONNECTIONS.h \
    ../Source/XlsbFormat/Biff12_unions/EXTCONNECTION.h \
    ../Source/XlsbFormat/Biff12_unions/ECDBPROPS.h \
    ../Source/XlsbFormat/Biff12_unions/ECOLAPPROPS.h \
    ../Source/XlsbFormat/Biff12_unions/ECWEBPROPS.h \
    ../Source/XlsbFormat/Biff12_unions/ECWPTABLES.h \
    ../Source/XlsbFormat/Biff12_unions/PCDI.h \
    ../Source/XlsbFormat/Biff12_unions/ECTXTWIZ.h \
    ../Source/XlsbFormat/Biff12_unions/ECTWFLDINFOLST.h \
    ../Source/XlsbFormat/Biff12_unions/ECPARAMS.h \
    ../Source/XlsbFormat/Biff12_unions/ECPARAM.h \
    ../Source/XlsbFormat/Biff12_unions/PCDCALCMEMSEXT.h \
    ../Source/XlsbFormat/Biff12_unions/PCDCALCMEM14.h \
    ../Source/XlsbFormat/Biff12_unions/PCDCALCMEMEXT.h \
    ../Source/XlsbFormat/Biff12_unions/SXTUPLESET.h \
    ../Source/XlsbFormat/Biff12_unions/SXTUPLESETHEADER.h \
    ../Source/XlsbFormat/Biff12_unions/SXTUPLESETDATA.h \
    ../Source/XlsbFormat/Biff12_unions/SXTUPLESETROW.h \
    ../Source/XlsbFormat/Biff12_unions/PCDCALCMEM15.h \
    ../Source/XlsbFormat/Biff12_unions/FRTEXTCONNECTIONS.h \
    ../Source/XlsbFormat/Biff12_unions/EXTCONN14.h \
    ../Source/XlsbFormat/Biff12_unions/EXTCONN15.h \
    ../Source/XlsbFormat/Biff12_unions/OLEDBPR15.h \
    ../Source/XlsbFormat/Biff12_unions/DBTABLES15.h \
    ../Source/XlsbFormat/Biff12_unions/DATAFEEDPR15.h \
    ../Source/XlsbFormat/Biff12_unions/TEXTPR15.h \
    ../Source/XlsbFormat/Biff12_unions/ECTXTWIZ15.h \
    ../Source/XlsbFormat/Biff12_unions/ECTWFLDINFOLST15.h \
    ../Source/XlsbFormat/Biff12_unions/SPARKLINEGROUP.h \
    ../Source/XlsbFormat/Biff12_unions/SPARKLINEGROUPS.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERS.h \
    ../Source/XlsbFormat/Biff12_unions/SLICER.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHECROSSFILTEREXT.h \
    ../Source/XlsbFormat/Biff12_unions/TABLESLICERCACHE.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHEBOOKPIVOTTABLES.h \
    ../Source/XlsbFormat/Biff12_unions/FRTSLICERCACHE.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHENATIVEITEMS.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHESELECTIONS.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHESIRANGE.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHESIRANGES.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHELEVELDATA.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHELEVELSDATA.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHEOLAPIMPL.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHE.h \
    ../Source/XlsbFormat/Biff12_unions/TABLESLICEREX.h \
    ../Source/XlsbFormat/Biff12_unions/TABLESLICERSEX.h \
    ../Source/XlsbFormat/Biff12_unions/SLICEREX.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERSEX.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHESPIVOTCACHEIDS.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHESPIVOTCACHEID.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHEIDS.h \
    ../Source/XlsbFormat/Biff12_unions/SLICERCACHEID.h \
    ../Source/XlsbFormat/Biff12_unions/TABLESLICERCACHEIDS.h \
    ../Source/XlsbFormat/Biff12_unions/TABLESLICERCACHEID.h \
    ../Source/XlsbFormat/Biff12_unions/FRTWORKBOOK.h \
    ../Source/XlsbFormat/Biff12_unions/OLEOBJECTS.h \
    ../Source/XlsbFormat/Biff12_unions/ACTIVEXCONTROLS.h \
    ../Source/XlsbFormat/Biff12_unions/RWBRK.h \
    ../Source/XlsbFormat/Biff12_unions/COLBRK.h \
    ../Source/XlsbFormat/Biff12_unions/DCON.h \
    ../Source/XlsbFormat/Biff12_unions/DREFS.h \
    ../Source/XlsbFormat/Biff12_unions/CSVIEWS.h \
    ../Source/XlsbFormat/Biff12_unions/CSVIEW.h \
    ../Source/XlsbFormat/Biff12_unions/USERCSVIEWS.h \
    ../Source/XlsbFormat/Biff12_unions/USERCSVIEW.h \
    ../Source/XlsbFormat/Biff12_unions/WEBPUBITEMS.h \
    ../Source/XlsbFormat/Biff12_unions/WEBPUBITEM.h \
