//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVSOfficeEWSEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceExcelDefaultStyles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceExcelDefaultStyles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVSOfficeEWSEditor.ResourceExcelDefaultStyles", typeof(ResourceExcelDefaultStyles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleDark1&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#404040&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;1&quot; Color=&quot;#FFFFFF&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleDark1 {
            get {
                return ResourceManager.GetString("TableStyleDark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleDark10&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Table [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleDark10 {
            get {
                return ResourceManager.GetString("TableStyleDark10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleDark11&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Table [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleDark11 {
            get {
                return ResourceManager.GetString("TableStyleDark11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleDark2&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#366092&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;1&quot; Color=&quot;#FFFFFF&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleDark2 {
            get {
                return ResourceManager.GetString("TableStyleDark2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleDark3&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#963634&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;1&quot; Color=&quot;#FFFFFF&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleDark3 {
            get {
                return ResourceManager.GetString("TableStyleDark3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleDark4&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#76933C&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;1&quot; Color=&quot;#FFFFFF&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleDark4 {
            get {
                return ResourceManager.GetString("TableStyleDark4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleDark5&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#60497A&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;1&quot; Color=&quot;#FFFFFF&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleDark5 {
            get {
                return ResourceManager.GetString("TableStyleDark5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleDark6&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#31869B&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;1&quot; Color=&quot;#FFFFFF&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleDark6 {
            get {
                return ResourceManager.GetString("TableStyleDark6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleDark7&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#E26B0A&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;1&quot; Color=&quot;#FFFFFF&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleDark7 {
            get {
                return ResourceManager.GetString("TableStyleDark7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleDark8&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/TableS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleDark8 {
            get {
                return ResourceManager.GetString("TableStyleDark8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleDark9&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/TableS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleDark9 {
            get {
                return ResourceManager.GetString("TableStyleDark9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight1&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Table [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight1 {
            get {
                return ResourceManager.GetString("TableStyleLight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight10&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight10 {
            get {
                return ResourceManager.GetString("TableStyleLight10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight11&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight11 {
            get {
                return ResourceManager.GetString("TableStyleLight11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight12&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight12 {
            get {
                return ResourceManager.GetString("TableStyleLight12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight13&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight13 {
            get {
                return ResourceManager.GetString("TableStyleLight13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight14&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight14 {
            get {
                return ResourceManager.GetString("TableStyleLight14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight15&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight15 {
            get {
                return ResourceManager.GetString("TableStyleLight15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight16&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight16 {
            get {
                return ResourceManager.GetString("TableStyleLight16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight17&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight17 {
            get {
                return ResourceManager.GetString("TableStyleLight17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight18&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight18 {
            get {
                return ResourceManager.GetString("TableStyleLight18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight19&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight19 {
            get {
                return ResourceManager.GetString("TableStyleLight19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight2&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#366092&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Table [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight2 {
            get {
                return ResourceManager.GetString("TableStyleLight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight20&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight20 {
            get {
                return ResourceManager.GetString("TableStyleLight20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight21&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight21 {
            get {
                return ResourceManager.GetString("TableStyleLight21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight3&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#963634&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Table [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight3 {
            get {
                return ResourceManager.GetString("TableStyleLight3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight4&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#76933C&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Table [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight4 {
            get {
                return ResourceManager.GetString("TableStyleLight4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight5&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#60497A&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Table [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight5 {
            get {
                return ResourceManager.GetString("TableStyleLight5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight6&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#31869B&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Table [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight6 {
            get {
                return ResourceManager.GetString("TableStyleLight6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight7&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#E26B0A&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Table [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight7 {
            get {
                return ResourceManager.GetString("TableStyleLight7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight8&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Table [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight8 {
            get {
                return ResourceManager.GetString("TableStyleLight8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleLight9&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Table [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleLight9 {
            get {
                return ResourceManager.GetString("TableStyleLight9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium1&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium1 {
            get {
                return ResourceManager.GetString("TableStyleMedium1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium10&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#C0504D&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium10 {
            get {
                return ResourceManager.GetString("TableStyleMedium10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium11&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#9BBB59&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium11 {
            get {
                return ResourceManager.GetString("TableStyleMedium11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium12&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#8064A2&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium12 {
            get {
                return ResourceManager.GetString("TableStyleMedium12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium13&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#4BACC6&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium13 {
            get {
                return ResourceManager.GetString("TableStyleMedium13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium14&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#F79646&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium14 {
            get {
                return ResourceManager.GetString("TableStyleMedium14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium15&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium15 {
            get {
                return ResourceManager.GetString("TableStyleMedium15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium16&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#4F81BD&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium16 {
            get {
                return ResourceManager.GetString("TableStyleMedium16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium17&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#C0504D&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium17 {
            get {
                return ResourceManager.GetString("TableStyleMedium17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium18&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#9BBB59&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium18 {
            get {
                return ResourceManager.GetString("TableStyleMedium18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium19&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#8064A2&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium19 {
            get {
                return ResourceManager.GetString("TableStyleMedium19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium2&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium2 {
            get {
                return ResourceManager.GetString("TableStyleMedium2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium20&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#4BACC6&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium20 {
            get {
                return ResourceManager.GetString("TableStyleMedium20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium21&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#F79646&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium21 {
            get {
                return ResourceManager.GetString("TableStyleMedium21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium22&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium22 {
            get {
                return ResourceManager.GetString("TableStyleMedium22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium23&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium23 {
            get {
                return ResourceManager.GetString("TableStyleMedium23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium24&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium24 {
            get {
                return ResourceManager.GetString("TableStyleMedium24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium25&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium25 {
            get {
                return ResourceManager.GetString("TableStyleMedium25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium26&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium26 {
            get {
                return ResourceManager.GetString("TableStyleMedium26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium27&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium27 {
            get {
                return ResourceManager.GetString("TableStyleMedium27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium28&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium28 {
            get {
                return ResourceManager.GetString("TableStyleMedium28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium3&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium3 {
            get {
                return ResourceManager.GetString("TableStyleMedium3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium4&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium4 {
            get {
                return ResourceManager.GetString("TableStyleMedium4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium5&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium5 {
            get {
                return ResourceManager.GetString("TableStyleMedium5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium6&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium6 {
            get {
                return ResourceManager.GetString("TableStyleMedium6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium7&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#000000&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium7 {
            get {
                return ResourceManager.GetString("TableStyleMedium7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium8&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#000000&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium8 {
            get {
                return ResourceManager.GetString("TableStyleMedium8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;TableStyle name=&quot;TableStyleMedium9&quot;&gt;&lt;TableStyleElement name=&quot;blankRow&quot; /&gt;&lt;TableStyleElement name=&quot;firstColumn&quot; Bold=&quot;true&quot; Italic=&quot;false&quot; Underline=&quot;false&quot; Color=&quot;#FFFFFF&quot; BgColor=&quot;#4F81BD&quot; StripeSize=&quot;1&quot;&gt;&lt;DiagonalDown LineStyle=&quot;-4142&quot; /&gt;&lt;DiagonalUp LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeLeft LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeTop LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeBottom LineStyle=&quot;-4142&quot; /&gt;&lt;EdgeRight LineStyle=&quot;-4142&quot; /&gt;&lt;InsideVertical LineStyle=&quot;-4142&quot; /&gt;&lt;InsideHorizontal LineStyle=&quot;-4142&quot; /&gt;&lt;/Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableStyleMedium9 {
            get {
                return ResourceManager.GetString("TableStyleMedium9", resourceCulture);
            }
        }
    }
}
