#pragma once
#ifndef PPTX_INCLUDE_H_
#define PPTX_INCLUDE_H_

//#include "FileFactory.h"
#include "Folder.h"
#include "Presentation.h"
#include "Slide.h"
#include "SlideLayout.h"
#include "SlideMaster.h"
#include "NotesMaster.h"
#include "App.h"
#include "Core.h"
#include "ViewProps.h"
#include "PresProps.h"
#include "TableStyles.h"

#include "Logic/Bg.h"
#include "Logic/Shape.h"
#include "Logic/Pic.h"
#include "Logic/CxnSp.h"
#include "Logic/GraphicFrame.h"
#include "Logic/TxBody.h"
#include "Logic/ShapeProperties.h"
#include "Logic/SpTree.h"
#include "Logic/UniFill.h"
#include "Logic/UniColor.h"
#include "Logic/Ln.h"
#include "Logic/LineJoin.h"
#include "Logic/Transitions/Transition.h"
#include "Logic/Timing/Timing.h"
#include "Logic/Timing/TnLst.h"
#include "Logic/Timing/TimeNodeBase.h"
#include "Logic/Timing/CTn.h"
#include "Logic/Timing/CBhvr.h"
#include "Logic/Timing/CondLst.h"
#include "Logic/Table/Table.h"
#include "Logic/TableStyle.h"
#include "Logic/Runs/Run.h"
#include "Logic/Runs/Fld.h"
#include "Logic/Runs/Br.h"
#include "Logic/XmlId.h"

#endif // PPTX_INCLUDE_H_