#if defined __cplusplus

#include <string>
#include <iosfwd>
#include <boost/algorithm/string.hpp>
#include <ostream>
#include <vector>
#include <iostream>
#include <sstream>
#include <map>
#include <boost/lexical_cast.hpp>
#include <boost/regex.hpp>
#include <boost/noncopyable.hpp>
#include <boost/make_shared.hpp>
#include <list>
#include <boost/functional.hpp>
#include <boost/regex.h>
#include <boost/shared_ptr.hpp>
#include <boost/unordered_map.hpp>
#include <boost/ref.hpp>
#include <boost/unordered_set.hpp>
#include <algorithm>
#include <utf8cpp/utf8.h>
#include <boost/function.hpp>
#include <boost/foreach.hpp>
#include <boost/optional.hpp>
#include <exception>
#include <set>
#include <fstream>
#include <random>
#include <boost/date_time.hpp>
#include <boost/optional/optional_io.hpp>

//#include "../../DataTypes/backgroundcolor.h"
//#include "../../DataTypes/bool.h"
//#include "../../DataTypes/borderstyle.h"
//#include "../../DataTypes/borderwidths.h"
//#include "../../DataTypes/color.h"
//#include "../../DataTypes/common_attlists.h"
//#include "../../DataTypes/custom_shape_types_convert.h"
//#include "../../DataTypes/direction.h"
//#include "../../DataTypes/fobreak.h"
//#include "../../DataTypes/fontfamilygeneric.h"
//#include "../../DataTypes/fontpitch.h"
//#include "../../DataTypes/fontsize.h"
//#include "../../DataTypes/fontstyle.h"
//#include "../../DataTypes/fontvariant.h"
//#include "../../DataTypes/fontweight.h"
//#include "../../DataTypes/gradientstyle.h"
//#include "../../DataTypes/hyphenationladdercount.h"
//#include "../../DataTypes/length.h"
//#include "../../DataTypes/lengthorpercent.h"
//#include "../../DataTypes/linestyle.h"
//#include "../../DataTypes/linetype.h"
//#include "../../DataTypes/linewidth.h"
//#include "../../DataTypes/noteclass.h"
//#include "../../DataTypes/odfattributes.h"
//#include "../../DataTypes/officevaluetype.h"
//#include "../../DataTypes/percent.h"
//#include "../../DataTypes/presentationclass.h"
//#include "../../DataTypes/shadowtype.h"
//#include "../../DataTypes/stylefamily.h"
//#include "../../DataTypes/styletype.h"
//#include "../../DataTypes/styleverticalpos.h"
//#include "../../DataTypes/styleverticalrel.h"
//#include "../../DataTypes/tablecentering.h"
//#include "../../DataTypes/targetframename.h"
//#include "../../DataTypes/textalign.h"
//#include "../../DataTypes/textdisplay.h"
//#include "../../DataTypes/verticalalign.h"
//#include "../../DataTypes/wrapoption.h"

//#include "../../Formulas/formulasconvert.h"

//#include "../../Common/errors.h"
//#include "../../Common/logging.h"
//#include "../../Common/CPNoncopyable.h"
//#include "../../Common/CPOptional.h"
//#include "../../Common/CPScopedPtr.h"
//#include "../../Common/CPSharedPtr.h"
//#include "../../Common/CPWeakPtr.h"

//#include "../../Common/xml/nodetype.h"
//#include "../../Common/xml/sax.h"
//#include "../../Common/xml/utils.h"
//#include "../../Common/xml/xmlelement.h"
//#include "../../Common/xml/simple_xml_writer.h"
//#include "../../Common/xml/xmlchar.h"
//#include "../../Common/xml/attributes.h"

#endif
