/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class docbuilder_CDocBuilder */

#ifndef _Included_docbuilder_CDocBuilder
#define _Included_docbuilder_CDocBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_Create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilder_c_1Create
  (JNIEnv *, jclass);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_OpenFile
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_docbuilder_CDocBuilder_c_1OpenFile
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_CreateFileByType
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilder_c_1CreateFileByType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_CreateFileByExtension
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilder_c_1CreateFileByExtension
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_SetTmpFolder
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1SetTmpFolder
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_SaveFileByType
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_docbuilder_CDocBuilder_c_1SaveFileByType
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_SaveFileByTypeWithParams
 * Signature: (JILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_docbuilder_CDocBuilder_c_1SaveFileByTypeWithParams
  (JNIEnv *, jclass, jlong, jint, jstring, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_SaveFileByExtension
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_docbuilder_CDocBuilder_c_1SaveFileByExtension
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_SaveFileByExtensionWithParams
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_docbuilder_CDocBuilder_c_1SaveFileByExtensionWithParams
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_CloseFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1CloseFile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_ExecuteCommand
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilder_c_1ExecuteCommand
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_ExecuteCommandWithRetValue
 * Signature: (JLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilder_c_1ExecuteCommandWithRetValue
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_Run
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilder_c_1Run
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_RunText
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilder_c_1RunText
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_SetProperty
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1SetProperty
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_WriteData
 * Signature: (JLjava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1WriteData
  (JNIEnv *, jclass, jlong, jstring, jstring, jboolean);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_IsSaveWithDoctrendererMode
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilder_c_1IsSaveWithDoctrendererMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_GetVersion
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_docbuilder_CDocBuilder_c_1GetVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_GetContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilder_c_1GetContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_Initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1Initialize
  (JNIEnv *, jclass);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_InitializeWithDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1InitializeWithDirectory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1Dispose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
