/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class docbuilder_CDocBuilderValue */

#ifndef _Included_docbuilder_CDocBuilderValue
#define _Included_docbuilder_CDocBuilderValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_Create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1Create
  (JNIEnv *, jclass);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_Copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1Copy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilderValue_c_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_IsEmpty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilderValue_c_1IsEmpty
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_Clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilderValue_c_1Clear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_IsNull
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilderValue_c_1IsNull
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_IsUndefined
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilderValue_c_1IsUndefined
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_IsBool
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilderValue_c_1IsBool
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_IsInt
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilderValue_c_1IsInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_IsDouble
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilderValue_c_1IsDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_IsString
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilderValue_c_1IsString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_IsFunction
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilderValue_c_1IsFunction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_IsObject
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilderValue_c_1IsObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_IsArray
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilderValue_c_1IsArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_GetLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_docbuilder_CDocBuilderValue_c_1GetLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_ToBool
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilderValue_c_1ToBool
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_ToInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_docbuilder_CDocBuilderValue_c_1ToInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_ToDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_docbuilder_CDocBuilderValue_c_1ToDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_ToString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_docbuilder_CDocBuilderValue_c_1ToString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_GetProperty
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1GetProperty
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_GetByIndex
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1GetByIndex
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_SetProperty
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilderValue_c_1SetProperty
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_SetByIndex
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilderValue_c_1SetByIndex
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_CreateWithBool
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1CreateWithBool
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_CreateWithInt
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1CreateWithInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_CreateWithDouble
 * Signature: (D)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1CreateWithDouble
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_CreateWithString
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1CreateWithString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_CreateUndefined
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1CreateUndefined
  (JNIEnv *, jclass);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_CreateNull
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1CreateNull
  (JNIEnv *, jclass);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_CreateArray
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1CreateArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_Call0
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1Call0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_Call1
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1Call1
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_Call2
 * Signature: (JLjava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1Call2
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_Call3
 * Signature: (JLjava/lang/String;JJJ)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1Call3
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_Call4
 * Signature: (JLjava/lang/String;JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1Call4
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong, jlong, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_Call5
 * Signature: (JLjava/lang/String;JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1Call5
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     docbuilder_CDocBuilderValue
 * Method:    c_Call6
 * Signature: (JLjava/lang/String;JJJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderValue_c_1Call6
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
