/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class docbuilder_CDocBuilderContextScope */

#ifndef _Included_docbuilder_CDocBuilderContextScope
#define _Included_docbuilder_CDocBuilderContextScope
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     docbuilder_CDocBuilderContextScope
 * Method:    c_Create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderContextScope_c_1Create
  (JNIEnv *, jclass);

/*
 * Class:     docbuilder_CDocBuilderContextScope
 * Method:    c_Copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilderContextScope_c_1Copy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderContextScope
 * Method:    c_Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilderContextScope_c_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilderContextScope
 * Method:    c_Close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilderContextScope_c_1Close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
