CORE_GTEST_PATH=$$PWD/googletest/googletest

CONFIG += c++14

CORE_GTEST_PATH_INCLUDE = $$CORE_GTEST_PATH/include
CORE_GTEST_PATH_LIBS    = $$CORE_GTEST_PATH/../build/$$CORE_BUILDS_PLATFORM_PREFIX/lib

INCLUDEPATH += $$CORE_GTEST_PATH
INCLUDEPATH += $$CORE_GTEST_PATH_INCLUDE
LIBS += -L$$CORE_GTEST_PATH_LIBS -lgtest -lgtest_main
