#pragma once

const long g_cdMaxPercent = 1000000;

#define PROP_DEF INT_MIN

#define RTF_MAX 1
#define RTF_MID 2
#define RTF_LOW 3

//#define RTF_MATH_OOX

#define ELEMENT_UNDEFINED  0x001;

#define ELEMENT_OOXFIELD  0x010;


#define TYPE_UNKNOWN			0
#define TYPE_RTF_DOCUMENT		1
#define TYPE_RTF_PARAGRAPH		2
#define TYPE_RTF_BOOKMARKSTART		3
#define TYPE_RTF_BOOKMARKEND		4
#define TYPE_RTF_CHAR		5
#define TYPE_RTF_FIELD		6
#define TYPE_RTF_MATH		7
#define TYPE_RTF_PICTURE		8
#define TYPE_RTF_PROPERTY_DOCUMENT	9
#define TYPE_RTF_PROPERTY_SECTION		10
#define TYPE_RTF_FONT		11
#define TYPE_RTF_PROPERTY_SHADING		13
#define TYPE_RTF_PROPERTY_SHADING_PARAGRAPH		14
#define TYPE_RTF_PROPERTY_SHADING_CHAR		15
#define TYPE_RTF_PROPERTY_SHADING_CELL		16
#define TYPE_RTF_PROPERTY_SHADING_ROW		17
#define TYPE_RTF_PROPERTY_SHADING_TABLESTYLE		18
#define TYPE_RTF_PROPERTY_BORDER		19
#define TYPE_RTF_PROPERTY_STYLE_CHAR		21
#define TYPE_RTF_PROPERTY_STYLE_PARAGRAPH		22
#define TYPE_RTF_PROPERTY_STYLE_TABLE		22
#define TYPE_RTF_SECTION		23
#define TYPE_RTF_TABLE		24
#define TYPE_RTF_TABLE_CELL		25
#define TYPE_RTF_PROPERTY_CHAR		26
#define TYPE_RTF_PROPERTY_STYLE		27
#define TYPE_RTF_TABLE_ROW		28
#define TYPE_RTF_OLE		29

#define TYPE_OOX_FIELD		29
#define TYPE_RTF_FOOTNOTE		30

#define RENDER_TO_OOX_PARAM_UNKNOWN 0
#define RENDER_TO_OOX_PARAM_LAST    1
#define RENDER_TO_OOX_PARAM_RUN    2
#define RENDER_TO_OOX_PARAM_PLAIN    3
#define RENDER_TO_OOX_PARAM_TEXT    4
#define RENDER_TO_OOX_PARAM_MATH    5
#define RENDER_TO_OOX_PARAM_NESTED    6
#define RENDER_TO_OOX_PARAM_FONTTABLE   7
#define RENDER_TO_OOX_PARAM_MAJOR_FONT   10
#define RENDER_TO_OOX_PARAM_MINOR_FONT   11
#define RENDER_TO_OOX_PARAM_CORE   12
#define RENDER_TO_OOX_PARAM_APP   13
#define RENDER_TO_OOX_PARAM_COLOR_VALUE   14
#define RENDER_TO_OOX_PARAM_COLOR_ATTRIBUTE   15
#define RENDER_TO_OOX_PARAM_COLOR_TAG   16
#define RENDER_TO_OOX_PARAM_NUMBERING   17
#define RENDER_TO_OOX_PARAM_STYLES   18
#define RENDER_TO_OOX_PARAM_BORDER_ATTRIBUTE   19
#define RENDER_TO_OOX_PARAM_BORDER_TAG   20
#define RENDER_TO_OOX_PARAM_SHAPE_WSHAPE   22
#define RENDER_TO_OOX_PARAM_SHAPE_WSHAPE2   23
#define RENDER_TO_OOX_PARAM_FIRST_SECTION   24
#define RENDER_TO_OOX_PARAM_OLE_ONLY   25
#define RENDER_TO_OOX_PARAM_OLDLIST_ABS   26
#define RENDER_TO_OOX_PARAM_OLDLIST_OVR   27

#define RENDER_TO_RTF_PARAM_UNKNOWN 0
#define RENDER_TO_RTF_PARAM_CHAR   1
#define RENDER_TO_RTF_PARAM_NO_PAR   2
#define RENDER_TO_RTF_PARAM_PAR   3
#define RENDER_TO_RTF_PARAM_NESTED   4
#define RENDER_TO_RTF_PARAM_PLAIN   5
#define RENDER_TO_RTF_PARAM_NO_SECT   6
#define RENDER_TO_RTF_PARAM_FONT_TBL  7
#define RENDER_TO_RTF_PARAM_COLOR_TBL  8
#define RENDER_TO_RTF_PARAM_NO_WROWD  9




















































































