#ifdef _MSC_VER
	#pragma once			// for MSVS
#endif	// #ifdef _MSC_VER

#ifndef _INTERNALCODECTYPES_H_	// For Borland compiler
#define _INTERNALCODECTYPES_H_



#define NONE_INTERNALCODEC				0

#define XVID_INTERNALCODEC				1
#define H263_INTERNALCODEC				4
	#define H263_INTERNALENCODER		4	//not use
	#define H263_INTERNALDECODER		5	//not use
#define H264_INTERNALCODEC				8
#define MPEG2_INTERNALCODEC				21
//#define IPPMPEG2_INTERNALCODEC			22
//	#define IPPMPEG2_INTERNALENCODER	22	//not use
//	#define IPPMPEG2_INTERNALDECODER	23	//not use

#define UNCOMPRESSEDVIDEO_INTERNALCODEC 24
#define VP8_INTERNALCODEC				25
#define QT_INTERNALCODEC				26

// Intel Media SDK:
#define INTELMEDIA_H264_INTERNALCODEC	27
#define INTELMEDIA_MPEG2_INTERNALCODEC	28
#define INTELMEDIA_VC1_INTERNALCODEC	29

// ffmpeg codecs
#define FF_H263_INTERNALCODEC			256
#define FF_H263P_INTERNALCODEC			269
#define FF_FLV_INTERNALCODEC			270

#define FF_H264_INTERNALCODEC			257
#define FF_SVQ1_INTERNALCODEC			258
#define FF_SVQ3_INTERNALCODEC			259
#define FF_DV_INTERNALCODEC				260

#define FF_MJPEG_INTERNALCODEC			261
#define FF_MJPEGB_INTERNALCODEC			272
#define FF_SP5X_INTERNALCODEC			273
#define FF_LJPEG_INTERNALCODEC			274

#define FF_MSMPEG4_INTERNALCODEC		262
#define FF_MSMPEG4V1_INTERNALCODEC		263
#define FF_MSMPEG4V2_INTERNALCODEC		264
#define FF_MSMPEG4V3_INTERNALCODEC		265
#define FF_CINEPAK_INTERNALCODEC		266
#define FF_INDEO2_INTERNALCODEC			267
#define FF_INDEO3_INTERNALCODEC			268

#define FF_HUFFMAN_INTERNALCODEC		275
#define FF_8BPS_INTERNALCODEC			276
#define FF_VC1_INTERNALCODEC			277

#define FF_RLE_INTERNALCODEC			278
#define FF_SMC_INTERNALCODEC			279
#define FF_RPZA_INTERNALCODEC			280
#define FF_QDRW_INTERNALCODEC			281
#define FF_CYUV_INTERNALCODEC			282

#define FF_H261_INTERNALCODEC			283
#define FF_ASUSV1_INTERNALCODEC			284
#define FF_ASUSV2_INTERNALCODEC			285
#define FF_QPEG_INTERNALCODEC			286
#define FF_MSRLE_INTERNALCODEC			287

#define FF_ON2VP3_INTERNALCODEC			298
#define FF_ON2VP5_INTERNALCODEC			299
#define FF_ON2VP6F_INTERNALCODEC		300
#define FF_ON2VP6_INTERNALCODEC			301

#define FF_MPEG2_INTERNALCODEC			302

#define FF_WMV7_INTERNALCODEC			303
#define FF_WMV8_INTERNALCODEC			304 
#define FF_WMV9_INTERNALCODEC			305
#define FF_THEORA_INTERNALCODEC			306
#define FF_FLIC_INTERNALCODEC			307
#define FF_AMV_INTERNALCODEC			308
#define FF_RV10_INTERNALCODEC			309
#define FF_RV20_INTERNALCODEC			310
#define FF_RV30_INTERNALCODEC			311
#define FF_RV40_INTERNALCODEC			312
#define FF_FLASHSV_INTERNALCODEC		313
#define FF_SWSCALE_INTERNALCODEC		314
#define FF_FRAPS_INTERNALCODEC			315
#define FF_TSCC_INTERNALCODEC			316
#define FF_DNXHD_INTERNALCODEC			317
#define FF_HUFFMPEG_INTERNALCODEC		318
#define FF_VP8_INTERNALCODEC			319
#define FF_JPEG2000_INTERNALCODEC		320
#define FF_V210_INTERNALCODEC			321

#define LAST_FFMPEGCODEC				321

// RM codecs
#define RV7_INTERNALCODEC				512
#define RV8_INTERNALCODEC				513
#define RV9_INTERNALCODEC				514
#define RV10_INTERNALCODEC				515


#endif // #ifndef _INTERNALCODECTYPES_H_	// For Borland compiler