#pragma once

#define AVS_OFFICESTUDIO_FILE_UNKNOWN					0x0000

#define AVS_OFFICESTUDIO_FILE_DOCUMENT					0x0040
#define AVS_OFFICESTUDIO_FILE_DOCUMENT_DOCX				AVS_OFFICESTUDIO_FILE_DOCUMENT + 0x0001
#define AVS_OFFICESTUDIO_FILE_DOCUMENT_DOC				AVS_OFFICESTUDIO_FILE_DOCUMENT + 0x0002
#define AVS_OFFICESTUDIO_FILE_DOCUMENT_ODT				AVS_OFFICESTUDIO_FILE_DOCUMENT + 0x0003
#define AVS_OFFICESTUDIO_FILE_DOCUMENT_RTF				AVS_OFFICESTUDIO_FILE_DOCUMENT + 0x0004
#define AVS_OFFICESTUDIO_FILE_DOCUMENT_TXT				AVS_OFFICESTUDIO_FILE_DOCUMENT + 0x0005
#define AVS_OFFICESTUDIO_FILE_DOCUMENT_HTML				AVS_OFFICESTUDIO_FILE_DOCUMENT + 0x0006
#define AVS_OFFICESTUDIO_FILE_DOCUMENT_MHT				AVS_OFFICESTUDIO_FILE_DOCUMENT + 0x0007
#define AVS_OFFICESTUDIO_FILE_DOCUMENT_EPUB				AVS_OFFICESTUDIO_FILE_DOCUMENT + 0x0008
#define AVS_OFFICESTUDIO_FILE_DOCUMENT_FB2				AVS_OFFICESTUDIO_FILE_DOCUMENT + 0x0009
#define AVS_OFFICESTUDIO_FILE_DOCUMENT_MOBI				AVS_OFFICESTUDIO_FILE_DOCUMENT + 0x000a

#define AVS_OFFICESTUDIO_FILE_PRESENTATION				0x0080
#define AVS_OFFICESTUDIO_FILE_PRESENTATION_PPTX			AVS_OFFICESTUDIO_FILE_PRESENTATION + 0x0001
#define AVS_OFFICESTUDIO_FILE_PRESENTATION_PPT			AVS_OFFICESTUDIO_FILE_PRESENTATION + 0x0002
#define AVS_OFFICESTUDIO_FILE_PRESENTATION_ODP			AVS_OFFICESTUDIO_FILE_PRESENTATION + 0x0003
#define AVS_OFFICESTUDIO_FILE_PRESENTATION_PPSX			AVS_OFFICESTUDIO_FILE_PRESENTATION + 0x0004

#define AVS_OFFICESTUDIO_FILE_SPREADSHEET				0x0100
#define AVS_OFFICESTUDIO_FILE_SPREADSHEET_XLSX			AVS_OFFICESTUDIO_FILE_SPREADSHEET + 0x0001
#define AVS_OFFICESTUDIO_FILE_SPREADSHEET_XLS			AVS_OFFICESTUDIO_FILE_SPREADSHEET + 0x0002
#define AVS_OFFICESTUDIO_FILE_SPREADSHEET_ODS			AVS_OFFICESTUDIO_FILE_SPREADSHEET + 0x0003
#define AVS_OFFICESTUDIO_FILE_SPREADSHEET_CSV			AVS_OFFICESTUDIO_FILE_SPREADSHEET + 0x0004

#define AVS_OFFICESTUDIO_FILE_CROSSPLATFORM				0x0200
#define AVS_OFFICESTUDIO_FILE_CROSSPLATFORM_PDF			AVS_OFFICESTUDIO_FILE_CROSSPLATFORM + 0x0001
#define AVS_OFFICESTUDIO_FILE_CROSSPLATFORM_SWF			AVS_OFFICESTUDIO_FILE_CROSSPLATFORM + 0x0002
#define AVS_OFFICESTUDIO_FILE_CROSSPLATFORM_DJVU		AVS_OFFICESTUDIO_FILE_CROSSPLATFORM + 0x0003
#define AVS_OFFICESTUDIO_FILE_CROSSPLATFORM_XPS			AVS_OFFICESTUDIO_FILE_CROSSPLATFORM + 0x0004
#define AVS_OFFICESTUDIO_FILE_CROSSPLATFORM_SVG			AVS_OFFICESTUDIO_FILE_CROSSPLATFORM + 0x0005
#define AVS_OFFICESTUDIO_FILE_CROSSPLATFORM_HTMLR		AVS_OFFICESTUDIO_FILE_CROSSPLATFORM + 0x0006
#define AVS_OFFICESTUDIO_FILE_CROSSPLATFORM_HTMLRMenu	AVS_OFFICESTUDIO_FILE_CROSSPLATFORM + 0x0007
#define AVS_OFFICESTUDIO_FILE_CROSSPLATFORM_HTMLRCanvas	AVS_OFFICESTUDIO_FILE_CROSSPLATFORM + 0x0008

#define AVS_OFFICESTUDIO_FILE_IMAGE						0x0400
#define AVS_OFFICESTUDIO_FILE_IMAGE_JPG					AVS_OFFICESTUDIO_FILE_IMAGE + 0x0001
#define AVS_OFFICESTUDIO_FILE_IMAGE_TIFF				AVS_OFFICESTUDIO_FILE_IMAGE + 0x0002
#define AVS_OFFICESTUDIO_FILE_IMAGE_TGA					AVS_OFFICESTUDIO_FILE_IMAGE + 0x0003
#define AVS_OFFICESTUDIO_FILE_IMAGE_GIF					AVS_OFFICESTUDIO_FILE_IMAGE + 0x0004
#define AVS_OFFICESTUDIO_FILE_IMAGE_PNG					AVS_OFFICESTUDIO_FILE_IMAGE + 0x0005
#define AVS_OFFICESTUDIO_FILE_IMAGE_EMF					AVS_OFFICESTUDIO_FILE_IMAGE + 0x0006
#define AVS_OFFICESTUDIO_FILE_IMAGE_WMF					AVS_OFFICESTUDIO_FILE_IMAGE + 0x0007
#define AVS_OFFICESTUDIO_FILE_IMAGE_BMP					AVS_OFFICESTUDIO_FILE_IMAGE + 0x0008
#define AVS_OFFICESTUDIO_FILE_IMAGE_CR2					AVS_OFFICESTUDIO_FILE_IMAGE + 0x0009
#define AVS_OFFICESTUDIO_FILE_IMAGE_PCX					AVS_OFFICESTUDIO_FILE_IMAGE + 0x000a
#define AVS_OFFICESTUDIO_FILE_IMAGE_RAS					AVS_OFFICESTUDIO_FILE_IMAGE + 0x000b
#define AVS_OFFICESTUDIO_FILE_IMAGE_PSD					AVS_OFFICESTUDIO_FILE_IMAGE + 0x000c

#define AVS_OFFICESTUDIO_FILE_OTHER						0x0800
#define AVS_OFFICESTUDIO_FILE_OTHER_EXTRACT_IMAGE		AVS_OFFICESTUDIO_FILE_OTHER + 0x0001
#define AVS_OFFICESTUDIO_FILE_OTHER_MS_OFFCRYPTO		AVS_OFFICESTUDIO_FILE_OTHER + 0x0002
#define AVS_OFFICESTUDIO_FILE_OTHER_HTMLZIP				AVS_OFFICESTUDIO_FILE_OTHER + 0x0003
#define AVS_OFFICESTUDIO_FILE_OTHER_OLD_DOCUMENT		AVS_OFFICESTUDIO_FILE_OTHER + 0x0004
#define AVS_OFFICESTUDIO_FILE_OTHER_OLD_PRESENTATION	AVS_OFFICESTUDIO_FILE_OTHER + 0x0005
#define AVS_OFFICESTUDIO_FILE_OTHER_OLD_DRAWING			AVS_OFFICESTUDIO_FILE_OTHER + 0x0006
#define AVS_OFFICESTUDIO_FILE_OTHER_TEAMLAB_INNER		AVS_OFFICESTUDIO_FILE_OTHER + 0x0007
#define AVS_OFFICESTUDIO_FILE_OTHER_JSON				AVS_OFFICESTUDIO_FILE_OTHER + 0x0008               // Для mail-merge
#define AVS_OFFICESTUDIO_FILE_OTHER_ZIP					AVS_OFFICESTUDIO_FILE_OTHER + 0x0009

#define AVS_OFFICESTUDIO_FILE_TEAMLAB					0x1000
#define AVS_OFFICESTUDIO_FILE_TEAMLAB_DOCY				AVS_OFFICESTUDIO_FILE_TEAMLAB + 0x0001
#define AVS_OFFICESTUDIO_FILE_TEAMLAB_XLSY				AVS_OFFICESTUDIO_FILE_TEAMLAB + 0x0002
#define AVS_OFFICESTUDIO_FILE_TEAMLAB_PPTY				AVS_OFFICESTUDIO_FILE_TEAMLAB + 0x0003

#define AVS_OFFICESTUDIO_FILE_CANVAS					0x2000
#define AVS_OFFICESTUDIO_FILE_CANVAS_WORD				AVS_OFFICESTUDIO_FILE_CANVAS + 0x0001
#define AVS_OFFICESTUDIO_FILE_CANVAS_SPREADSHEET		AVS_OFFICESTUDIO_FILE_CANVAS + 0x0002
#define AVS_OFFICESTUDIO_FILE_CANVAS_PRESENTATION		AVS_OFFICESTUDIO_FILE_CANVAS + 0x0003
