#ifndef ERRORS_H
#define ERRORS_H

namespace HWP
{
enum class EErrorsCode
{
	UNDEFINED,
	SIGANTURE_NOT_MATCH,
	INVALID_MAJORVERSION,
	INVALID_MINORVERSION,
	INVALID_BYTEORDER,
	INVALID_SECTORSHIFT,
	INVALID_MINISECTORSHIFT,
	INVALID_NUM_DIRECTORYSECTOR,
	INVALID_MINI_STREAM_CUTOFF,
	FILE_READ_ERROR,
	INVALID_ZIP_DATA_FORMAT
};
}

#endif // ERRORS_H
