#-------------------------------------------------
#
# Project created by QtCreator 2014-12-16T18:28:23
#
#-------------------------------------------------

QT       -= core gui

TARGET = PptFormatLib
TEMPLATE = lib
CONFIG += staticlib

CORE_ROOT_DIR = $$PWD/../../..
PWD_ROOT_DIR = $$PWD

CONFIG += core_x2t
include(../../../Common/base.pri)

#BOOST
include($$PWD/../../../Common/3dParty/boost/boost.pri)

DEFINES +=  UNICODE \
        _UNICODE \
        _PRESENTATION_WRITER_ \
        _SVG_CONVERT_TO_IMAGE_  \
        DONT_WRITE_EMBEDDED_FONTS
        #DISABLE_FILE_DOWNLOADER

HEADERS += \
    ../../../ASCOfficePPTXFile/Editor/Drawing/Animations.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/Attributes.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/AudioOverlay.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/Document.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/Effects.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/Interactive.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/Metric.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/SlideShow.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/Structures.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/Timing.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/XmlStringWriter.h \
    ../PPTFormatLib.h \
    ../Reader/ClassesAtom.h \
    ../Reader/CommonZLib.h \
    ../Reader/PPTDocumentInfo.h \
    ../Reader/PPTDocumentInfoOneUser.h \
    ../Reader/PPTFileDefines.h \
    ../Reader/PPTFileReader.h \
    ../Reader/ReadStructures.h \
    ../Reader/Records.h \
    ../Reader/Slide.h \
    ../Reader/SlideInfo.h \
    ../Reader/SlidePersist.h \
    ../PPTXWriter/Converter.h \
    ../PPTXWriter/ImageManager.h \
    ../PPTXWriter/ShapeWriter.h \
    ../PPTXWriter/StylesWriter.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/Element.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/Elements.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/Layout.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/Slide.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/TextAttributesEx.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/TextStructures.h \
    ../../../ASCOfficePPTXFile/Editor/Drawing/Theme.h \
    ../../../Common/3dParty/pole/pole.h  \
    ../Records/Enums/_includer.h \
    ../Records/Enums/enums.h \
    ../Records/FStreams_FStorages/_includer.h \
    ../Records/RecordsIncluder.h \
    ../Records/SCommon/ColorIndexStruct.h \
    ../Records/SCommon/ColorStruct.h \
    ../Records/SCommon/DateTimeStruct.h \
    ../Records/SCommon/PointStruct.h \
    ../Records/SCommon/RatioStruct.h \
    ../Records/SCommon/RectStruct.h \
    ../Records/SCommon/ScalingStruct.h \
    ../Records/SCommon/SmallRectStruct.h \
    ../Records/SCommon/TmsfTimeStruct.h \
    ../Records/SCommon/WideColorStruct.h \
    ../Records/SCommon/_includer.h \
    ../Records/TAnimation/AnimationInfoAtom.h \
    ../Records/TAnimation/AnimationInfoContainer.h \
    ../Records/TAnimation/BuildAtom.h \
    ../Records/TAnimation/BuildListContainer.h \
    ../Records/TAnimation/BuildListSubContainer.h \
    ../Records/TAnimation/ChartBuildAtom.h \
    ../Records/TAnimation/ChartBuildContainer.h \
    ../Records/TAnimation/ClientVisualElementContainer.h \
    ../Records/TAnimation/DiagramBuildAtom.h \
    ../Records/TAnimation/DiagramBuildContainer.h \
    ../Records/TAnimation/ExtTimeNodeContainer.h \
    ../Records/TAnimation/HSLColorBy.h \
    ../Records/TAnimation/HashCode10Atom.h \
    ../Records/TAnimation/IndexSchemeColor.h \
    ../Records/TAnimation/LevelInfoAtom.h \
    ../Records/TAnimation/ParaBuildAtom.h \
    ../Records/TAnimation/ParaBuildContainer.h \
    ../Records/TAnimation/ParaBuildLevel.h \
    ../Records/TAnimation/RGBColor.h \
    ../Records/TAnimation/RGBColorBy.h \
    ../Records/TAnimation/SubEffectContainer.h \
    ../Records/TAnimation/TimeAnimateBehaviorAtom.h \
    ../Records/TAnimation/TimeAnimateBehaviorContainer.h \
    ../Records/TAnimation/TimeAnimateColor.h \
    ../Records/TAnimation/TimeAnimateColorBy.h \
    ../Records/TAnimation/TimeAnimationValueAtom.h \
    ../Records/TAnimation/TimeAnimationValueListContainer.h \
    ../Records/TAnimation/TimeAnimationValueListEntry.h \
    ../Records/TAnimation/TimeBehaviorAtom.h \
    ../Records/TAnimation/TimeBehaviorContainer.h \
    ../Records/TAnimation/TimeColorBehaviorAtom.h \
    ../Records/TAnimation/TimeColorBehaviorContainer.h \
    ../Records/TAnimation/TimeColorBehaviorPropertyUsedFlag.h \
    ../Records/TAnimation/TimeColorDirection.h \
    ../Records/TAnimation/TimeColorModel.h \
    ../Records/TAnimation/TimeCommandBehaviorAtom.h \
    ../Records/TAnimation/TimeCommandBehaviorContainer.h \
    ../Records/TAnimation/TimeConditionAtom.h \
    ../Records/TAnimation/TimeConditionContainer.h \
    ../Records/TAnimation/TimeDisplayType.h \
    ../Records/TAnimation/TimeEffectBehaviorAtom.h \
    ../Records/TAnimation/TimeEffectBehaviorContainer.h \
    ../Records/TAnimation/TimeEffectID.h \
    ../Records/TAnimation/TimeEffectNodeType.h \
    ../Records/TAnimation/TimeEffectType.h \
    ../Records/TAnimation/TimeEventFilter.h \
    ../Records/TAnimation/TimeGroupID.h \
    ../Records/TAnimation/TimeIterateDataAtom.h \
    ../Records/TAnimation/TimeMasterRelType.h \
    ../Records/TAnimation/TimeModifierAtom.h \
    ../Records/TAnimation/TimeMotionBehaviorAtom.h \
    ../Records/TAnimation/TimeMotionBehaviorContainer.h \
    ../Records/TAnimation/TimeNodeAtom.h \
    ../Records/TAnimation/TimeNodeTimeFilter.h \
    ../Records/TAnimation/TimeOverride.h \
    ../Records/TAnimation/TimePointsTypes.h \
    ../Records/TAnimation/TimePropertyList4TimeBehavior.h \
    ../Records/TAnimation/TimePropertyList4TimeNodeContainer.h \
    ../Records/TAnimation/TimeRotationBehaviorAtom.h \
    ../Records/TAnimation/TimeRotationBehaviorContainer.h \
    ../Records/TAnimation/TimeRuntimeContext.h \
    ../Records/TAnimation/TimeScaleBehaviorAtom.h \
    ../Records/TAnimation/TimeScaleBehaviorContainer.h \
    ../Records/TAnimation/TimeSequenceDataAtom.h \
    ../Records/TAnimation/TimeSetBehaviorAtom.h \
    ../Records/TAnimation/TimeSetBehaviorContainer.h \
    ../Records/TAnimation/TimeStringListContainer.h \
    ../Records/TAnimation/TimeSubType.h \
    ../Records/TAnimation/TimeVariant.h \
    ../Records/TAnimation/TimeVariant4Behavior.h \
    ../Records/TAnimation/TimeVariant4TimeNode.h \
    ../Records/TAnimation/TimeVariantBool.h \
    ../Records/TAnimation/TimeVariantFloat.h \
    ../Records/TAnimation/TimeVariantInt.h \
    ../Records/TAnimation/TimeVariantString.h \
    ../Records/TAnimation/VisualElementAtom.h \
    ../Records/TAnimation/VisualPageAtom.h \
    ../Records/TAnimation/VisualShapeAtom.h \
    ../Records/TAnimation/VisualShapeChartElementAtom.h \
    ../Records/TAnimation/VisualShapeGeneralAtom.h \
    ../Records/TAnimation/VisualShapeOrSoundAtom.h \
    ../Records/TAnimation/VisualSoundAtom.h \
    ../Records/TAnimation/_includer.h \
    ../Records/TBasic/_includer.h \
    ../Records/TBasic/types.h \
    ../Records/TDocument/DocInfoListContainer.h \
    ../Records/TDocument/DocInfoListSubContainerOrAtom.h \
    ../Records/TDocument/DocumentAtom.h \
    ../Records/TDocument/DocumentContainer.h \
    ../Records/TDocument/DrawingGroupContainer.h \
    ../Records/TDocument/EndDocumentAtom.h \
    ../Records/TDocument/FilterPrivacyFlags10Atom.h \
    ../Records/TDocument/ModifyPasswordAtom.h \
    ../Records/TDocument/PhotoAlbumInfo10Atom.h \
    ../Records/TDocument/PresAdvisorFlags9Atom.h \
    ../Records/TDocument/PrintOptionsAtom.h \
    ../Records/TDocument/TSound/SoundBuiltinIdAtom.h \
    ../Records/TDocument/TSound/SoundCollectionAtom.h \
    ../Records/TDocument/TSound/SoundCollectionContainer.h \
    ../Records/TDocument/TSound/SoundContainer.h \
    ../Records/TDocument/TSound/SoundExtensionAtom.h \
    ../Records/TDocument/TSound/SoundIdAtom.h \
    ../Records/TDocument/TSound/SoundNameAtom.h \
    ../Records/TDocument/TSound/_includer.h \
    ../Records/TDocument/VBAInfoAtom.h \
    ../Records/TDocument/VBAInfoContainer.h \
    ../Records/TDocument/_includer.h \
    ../Records/TExternalObject/ClipboardNameAtom.h \
    ../Records/TExternalObject/ExAviMovieContainer.h \
    ../Records/TExternalObject/ExCDAudioAtom.h \
    ../Records/TExternalObject/ExCDAudioContainer.h \
    ../Records/TExternalObject/ExControlAtom.h \
    ../Records/TExternalObject/ExControlContainer.h \
    ../Records/TExternalObject/ExControlStg.h \
    ../Records/TExternalObject/ExControlStgCompressedAtom.h \
    ../Records/TExternalObject/ExControlStgUncompressedAtom.h \
    ../Records/TExternalObject/ExHyperlink9Container.h \
    ../Records/TExternalObject/ExHyperlinkAtom.h \
    ../Records/TExternalObject/ExHyperlinkContainer.h \
    ../Records/TExternalObject/ExHyperlinkFlagsAtom.h \
    ../Records/TExternalObject/ExHyperlinkRefAtom.h \
    ../Records/TExternalObject/ExMCIMovieContainer.h \
    ../Records/TExternalObject/ExMIDIAudioContainer.h \
    ../Records/TExternalObject/ExMediaAtom.h \
    ../Records/TExternalObject/ExObjListAtom.h \
    ../Records/TExternalObject/ExObjListContainer.h \
    ../Records/TExternalObject/ExObjListSubContainer.h \
    ../Records/TExternalObject/ExOleEmbedAtom.h \
    ../Records/TExternalObject/ExOleEmbedContainer.h \
    ../Records/TExternalObject/ExOleLinkAtom.h \
    ../Records/TExternalObject/ExOleLinkContainer.h \
    ../Records/TExternalObject/ExOleObjAtom.h \
    ../Records/TExternalObject/ExOleObjStg.h \
    ../Records/TExternalObject/ExOleObjStgCompressedAtom.h \
    ../Records/TExternalObject/ExOleObjStgUncompressedAtom.h \
    ../Records/TExternalObject/ExVideoContainer.h \
    ../Records/TExternalObject/ExWAVAudioEmbeddedAtom.h \
    ../Records/TExternalObject/ExWAVAudioEmbeddedContainer.h \
    ../Records/TExternalObject/ExWAVAudioLinkContainer.h \
    ../Records/TExternalObject/FriendlyNameAtom.h \
    ../Records/TExternalObject/LocationAtom.h \
    ../Records/TExternalObject/MenuNameAtom.h \
    ../Records/TExternalObject/ProgIDAtom.h \
    ../Records/TExternalObject/ScreenTipAtom.h \
    ../Records/TExternalObject/TargetAtom.h \
    ../Records/TExternalObject/UncOrLocalPathAtom.h \
    ../Records/TExternalObject/VbaProjectStg.h \
    ../Records/TExternalObject/VbaProjectStgCompressedAtom.h \
    ../Records/TExternalObject/VbaProjectStgUncompressedAtom.h \
    ../Records/TExternalObject/_includer.h \
    ../Records/TFStructure/CryptSession10Container.h \
    ../Records/TFStructure/CurrentUserAtom.h \
    ../Records/TFStructure/PersistDirectoryAtom.h \
    ../Records/TFStructure/PersistDirectoryEntry.h \
    ../Records/TFStructure/RecordHeader.h \
    ../Records/TFStructure/UserEditAtom.h \
    ../Records/TFStructure/_includer.h \
    ../Records/TOther/BinaryTagDataBlob.h \
    ../Records/TOther/DocRoutingSlipAtom.h \
    ../Records/TOther/DocRoutingSlipString.h \
    ../Records/TOther/EnvelopeData9Atom.h \
    ../Records/TOther/EnvelopeFlags9Atom.h \
    ../Records/TOther/FontEmbedDataBlob.h \
    ../Records/TOther/MetafileBlob.h \
    ../Records/TOther/ProgStringTagContainer.h \
    ../Records/TOther/RoundTripAnimationAtom.h \
    ../Records/TOther/RoundTripAnimationHashAtom.h \
    ../Records/TOther/RoundTripColorMappingAtom.h \
    ../Records/TOther/RoundTripCompositeMasterId12Atom.h \
    ../Records/TOther/RoundTripContentMasterId12Atom.h \
    ../Records/TOther/RoundTripContentMasterInfo12Atom.h \
    ../Records/TOther/RoundTripCustomTableStyles12Atom.h \
    ../Records/TOther/RoundTripDocFlags12Atom.h \
    ../Records/TOther/RoundTripHFPlaceholder12Atom.h \
    ../Records/TOther/RoundTripHeaderFooterDefaults12Atom.h \
    ../Records/TOther/RoundTripNewPlaceholderId12Atom.h \
    ../Records/TOther/RoundTripNotesMasterTextStyles12Atom.h \
    ../Records/TOther/RoundTripOArtTextStyles12Atom.h \
    ../Records/TOther/RoundTripOriginalMainMasterId12Atom.h \
    ../Records/TOther/RoundTripShapeCheckSumForCustomLayouts12Atom.h \
    ../Records/TOther/RoundTripShapeId12Atom.h \
    ../Records/TOther/RoundTripSlideSyncInfo12Container.h \
    ../Records/TOther/RoundTripThemeAtom.h \
    ../Records/TOther/ServerIdAtom.h \
    ../Records/TOther/SlideLibUrlAtom.h \
    ../Records/TOther/SlideSyncInfoAtom12.h \
    ../Records/TOther/SmartTagStore11Container.h \
    ../Records/TOther/SoundDataBlob.h \
    ../Records/TOther/TagNameAtom.h \
    ../Records/TOther/TagValueAtom.h \
    ../Records/TOther/UnknownBinaryTag.h \
    ../Records/TOther/_includer.h \
    ../Records/TShape/ExObjRefAtom.h \
    ../Records/TShape/OfficeArtClientAnchor.h \
    ../Records/TShape/OfficeArtClientAnchorData.h \
    ../Records/TShape/OfficeArtClientData.h \
    ../Records/TShape/PP10ShapeBinaryTagExtension.h \
    ../Records/TShape/PP11ShapeBinaryTagExtension.h \
    ../Records/TShape/PP9ShapeBinaryTagExtension.h \
    ../Records/TShape/PlaceholderAtom.h \
    ../Records/TShape/RecolorEntry.h \
    ../Records/TShape/RecolorEntryBrush.h \
    ../Records/TShape/RecolorEntryColor.h \
    ../Records/TShape/RecolorEntryVariant.h \
    ../Records/TShape/RecolorInfoAtom.h \
    ../Records/TShape/ShapeClientRoundtripDataSubContainerOrAtom.h \
    ../Records/TShape/ShapeFlags10Atom.h \
    ../Records/TShape/ShapeFlagsAtom.h \
    ../Records/TShape/ShapeProgBinaryTagContainer.h \
    ../Records/TShape/ShapeProgBinaryTagSubContainerOrAtom.h \
    ../Records/TShape/ShapeProgTagsContainer.h \
    ../Records/TShape/ShapeProgTagsSubContainerOrAtom.h \
    ../Records/TShape/_includer.h \
    ../Records/TSlide/Comment10Atom.h \
    ../Records/TSlide/Comment10AuthorAtom.h \
    ../Records/TSlide/Comment10AuthorInitialAtom.h \
    ../Records/TSlide/Comment10Container.h \
    ../Records/TSlide/Comment10TextAtom.h \
    ../Records/TSlide/DrawingContainer.h \
    ../Records/TSlide/HandoutContainer.h \
    ../Records/TSlide/HandoutRoundTripAtom.h \
    ../Records/TSlide/LinkedShape10Atom.h \
    ../Records/TSlide/LinkedSlide10Atom.h \
    ../Records/TSlide/MainMasterContainer.h \
    ../Records/TSlide/MasterOrSlideContainer.h \
    ../Records/TSlide/NotesAtom.h \
    ../Records/TSlide/NotesContainer.h \
    ../Records/TSlide/NotesRoundTripAtom.h \
    ../Records/TSlide/PP10SlideBinaryTagExtension.h \
    ../Records/TSlide/PP12SlideBinaryTagExtension.h \
    ../Records/TSlide/PerSlideHeadersFootersContainer.h \
    ../Records/TSlide/RoundTripMainMasterRecord.h \
    ../Records/TSlide/RoundTripSlideRecord.h \
    ../Records/TSlide/SchemeListElementColorSchemeAtom.h \
    ../Records/TSlide/SlideAtom.h \
    ../Records/TSlide/SlideContainer.h \
    ../Records/TSlide/SlideFlags.h \
    ../Records/TSlide/SlideFlags10Atom.h \
    ../Records/TSlide/SlideNameAtom.h \
    ../Records/TSlide/SlideProgBinaryTagContainer.h \
    ../Records/TSlide/SlideProgBinaryTagSubContainerOrAtom.h \
    ../Records/TSlide/SlideProgTagsContainer.h \
    ../Records/TSlide/SlideProgTagsSubContainerOrAtom.h \
    ../Records/TSlide/SlideSchemeColorSchemeAtom.h \
    ../Records/TSlide/SlideTime10Atom.h \
    ../Records/TSlide/TemplateNameAtom.h \
    ../Records/TSlide/_includer.h \
    ../Records/TSlideShow/InteractiveInfoAtom.h \
    ../Records/TSlideShow/InteractiveInfoInstance.h \
    ../Records/TSlideShow/MacroNameAtom.h \
    ../Records/TSlideShow/MouseClickInteractiveInfoContainer.h \
    ../Records/TSlideShow/MouseOverInteractiveInfoContainer.h \
    ../Records/TSlideShow/NamedShowContainer.h \
    ../Records/TSlideShow/NamedShowNameAtom.h \
    ../Records/TSlideShow/NamedShowSlidesAtom.h \
    ../Records/TSlideShow/NamedShowsContainer.h \
    ../Records/TSlideShow/SlideShowDocInfoAtom.h \
    ../Records/TSlideShow/SlideShowSlideInfoAtom.h \
    ../Records/TSlideShow/_includer.h \
    ../Records/TText/BlipCollection9Container.h \
    ../Records/TText/BlipEntityAtom.h \
    ../Records/TText/BulletFlags.h \
    ../Records/TText/CFMasks.h \
    ../Records/TText/CFStyle.h \
    ../Records/TText/DateTimeMCAtom.h \
    ../Records/TText/DefaultRulerAtom.h \
    ../Records/TText/DocumentTextInfoContainer.h \
    ../Records/TText/FontCollection10Container.h \
    ../Records/TText/FontCollectionContainer.h \
    ../Records/TText/FontCollectionEntry.h \
    ../Records/TText/FontEmbedFlags10Atom.h \
    ../Records/TText/FontEntityAtom.h \
    ../Records/TText/FooterMCAtom.h \
    ../Records/TText/GenericDateMCAtom.h \
    ../Records/TText/HeaderMCAtom.h \
    ../Records/TText/Kinsoku9Atom.h \
    ../Records/TText/Kinsoku9Container.h \
    ../Records/TText/KinsokuAtom.h \
    ../Records/TText/KinsokuContainer.h \
    ../Records/TText/KinsokuFollowingAtom.h \
    ../Records/TText/KinsokuLeadingAtom.h \
    ../Records/TText/MasterTextPropAtom.h \
    ../Records/TText/MasterTextPropRun.h \
    ../Records/TText/MouseClickTextInteractiveInfoAtom.h \
    ../Records/TText/MouseOverTextInteractiveInfoAtom.h \
    ../Records/TText/OfficeArtClientTextbox.h \
    ../Records/TText/OutlineTextProps10Container.h \
    ../Records/TText/OutlineTextProps10Entry.h \
    ../Records/TText/OutlineTextProps11Container.h \
    ../Records/TText/OutlineTextProps11Entry.h \
    ../Records/TText/OutlineTextProps9Container.h \
    ../Records/TText/OutlineTextProps9Entry.h \
    ../Records/TText/OutlineTextPropsHeaderExAtom.h \
    ../Records/TText/OutlineTextRefAtom.h \
    ../Records/TText/PFMasks.h \
    ../Records/TText/PFWrapFlags.h \
    ../Records/TText/RTFDateTimeMCAtom.h \
    ../Records/TText/SlideNumberMCAtom.h \
    ../Records/TText/SmartTags.h \
    ../Records/TText/SpellingFlags.h \
    ../Records/TText/StyleTextProp10Atom.h \
    ../Records/TText/StyleTextProp11.h \
    ../Records/TText/StyleTextProp11Atom.h \
    ../Records/TText/StyleTextProp9.h \
    ../Records/TText/StyleTextProp9Atom.h \
    ../Records/TText/StyleTextPropAtom.h \
    ../Records/TText/TabStop.h \
    ../Records/TText/TabStops.h \
    ../Records/TText/TextAutoNumberScheme.h \
    ../Records/TText/TextBookmarkAtom.h \
    ../Records/TText/TextBytesAtom.h \
    ../Records/TText/TextCFException.h \
    ../Records/TText/TextCFException10.h \
    ../Records/TText/TextCFException9.h \
    ../Records/TText/TextCFExceptionAtom.h \
    ../Records/TText/TextCFRun.h \
    ../Records/TText/TextCharsAtom.h \
    ../Records/TText/TextClientDataSubContainerOrAtom.h \
    ../Records/TText/TextDefaults10Atom.h \
    ../Records/TText/TextDefaults9Atom.h \
    ../Records/TText/TextHeaderAtom.h \
    ../Records/TText/TextInteractiveInfoInstance.h \
    ../Records/TText/TextMasterStyle10Atom.h \
    ../Records/TText/TextMasterStyle10Level.h \
    ../Records/TText/TextMasterStyle9Atom.h \
    ../Records/TText/TextMasterStyle9Level.h \
    ../Records/TText/TextMasterStyleAtom.h \
    ../Records/TText/TextMasterStyleLevel.h \
    ../Records/TText/TextPFException.h \
    ../Records/TText/TextPFException9.h \
    ../Records/TText/TextPFExceptionAtom.h \
    ../Records/TText/TextPFRun.h \
    ../Records/TText/TextRange.h \
    ../Records/TText/TextRuler.h \
    ../Records/TText/TextRulerAtom.h \
    ../Records/TText/TextSIException.h \
    ../Records/TText/TextSIExceptionAtom.h \
    ../Records/TText/TextSIRun.h \
    ../Records/TText/TextSpecialInfoAtom.h \
    ../Records/TText/_includer.h

core_release {
SOURCES += \
    pptformatlib_logic.cpp
}

core_debug {
SOURCES += \
    ../Reader/ReadStructures.cpp \
    ../Reader/PPTDocumentInfoOneUser.cpp \
    ../Reader/Records.cpp \
    ../Reader/PPTFileReader.cpp \
    ../Reader/SlidePersist.cpp \
    ../PPTXWriter/Converter.cpp \
    ../PPTXWriter/ShapeWriter.cpp
}

SOURCES += \
    ../PPTFormatLib.cpp \
    ../../../ASCOfficePPTXFile/Editor/Drawing/Elements.cpp \
    ../../../ASCOfficePPTXFile/Editor/Drawing/TextAttributesEx.cpp \
    ../../../Common/3dParty/pole/pole.cpp

