#include "graphics.h"

#include <string>

double       to_double(const v8::Local<v8::Value>& v);
bool         to_bool  (const v8::Local<v8::Value>& v);
int          to_int   (const v8::Local<v8::Value>& v);
unsigned int to_uint  (const v8::Local<v8::Value>& v);
std::string  to_string(const v8::Local<v8::Value>& v);

CJSGraphics*         unwrap_Graphics          (v8::Handle<v8::Object> obj);
CFont*               unwrap_Font              (v8::Handle<v8::Object> obj);
CLastFontOriginInfo* unwrap_LastFontOriginInfo(v8::Handle<v8::Object> obj);

void init_w                    (const v8::FunctionCallbackInfo<v8::Value>& args);
void EndDraw_w                 (const v8::FunctionCallbackInfo<v8::Value>& args);
void put_GlobalAlpha_w         (const v8::FunctionCallbackInfo<v8::Value>& args);
void Start_GlobalAlpha_w       (const v8::FunctionCallbackInfo<v8::Value>& args);
void End_GlobalAlpha_w         (const v8::FunctionCallbackInfo<v8::Value>& args);
void p_color_w                 (const v8::FunctionCallbackInfo<v8::Value>& args);
void p_width_w                 (const v8::FunctionCallbackInfo<v8::Value>& args);
void p_dash_w                  (const v8::FunctionCallbackInfo<v8::Value>& args);
void b_color1_w                (const v8::FunctionCallbackInfo<v8::Value>& args);
void b_color2_w                (const v8::FunctionCallbackInfo<v8::Value>& args);
void transform_w               (const v8::FunctionCallbackInfo<v8::Value>& args);
void CalculateFullTransform_w  (const v8::FunctionCallbackInfo<v8::Value>& args);
void _s_w                      (const v8::FunctionCallbackInfo<v8::Value>& args);
void _e_w                      (const v8::FunctionCallbackInfo<v8::Value>& args);
void _z_w                      (const v8::FunctionCallbackInfo<v8::Value>& args);
void _m_w                      (const v8::FunctionCallbackInfo<v8::Value>& args);
void _l_w                      (const v8::FunctionCallbackInfo<v8::Value>& args);
void _c_w                      (const v8::FunctionCallbackInfo<v8::Value>& args);
void _c2_w                     (const v8::FunctionCallbackInfo<v8::Value>& args);
void ds_w                      (const v8::FunctionCallbackInfo<v8::Value>& args);
void df_w                      (const v8::FunctionCallbackInfo<v8::Value>& args);
void save_w                    (const v8::FunctionCallbackInfo<v8::Value>& args);
void restore_w                 (const v8::FunctionCallbackInfo<v8::Value>& args);
void clip_w                    (const v8::FunctionCallbackInfo<v8::Value>& args);
void reset_w                   (const v8::FunctionCallbackInfo<v8::Value>& args);
void transform3_w              (const v8::FunctionCallbackInfo<v8::Value>& args);
void FreeFont_w                (const v8::FunctionCallbackInfo<v8::Value>& args);
void ClearLastFont_w           (const v8::FunctionCallbackInfo<v8::Value>& args);
void drawImage2_w              (const v8::FunctionCallbackInfo<v8::Value>& args);
void drawImage_w               (const v8::FunctionCallbackInfo<v8::Value>& args);
void GetFont_w                 (const v8::FunctionCallbackInfo<v8::Value>& args);
void font_w                    (const v8::FunctionCallbackInfo<v8::Value>& args);
void SetFont_w                 (const v8::FunctionCallbackInfo<v8::Value>& args);
void SetTextPr_w               (const v8::FunctionCallbackInfo<v8::Value>& args);
void SetFontSlot_w             (const v8::FunctionCallbackInfo<v8::Value>& args);
void GetTextPr_w               (const v8::FunctionCallbackInfo<v8::Value>& args);
void FillText_w                (const v8::FunctionCallbackInfo<v8::Value>& args);
void t_w                       (const v8::FunctionCallbackInfo<v8::Value>& args);
void FillText2_w               (const v8::FunctionCallbackInfo<v8::Value>& args);
void t2_w                      (const v8::FunctionCallbackInfo<v8::Value>& args);
void FillTextCode_w            (const v8::FunctionCallbackInfo<v8::Value>& args);
void tg_w                      (const v8::FunctionCallbackInfo<v8::Value>& args);
void charspace_w               (const v8::FunctionCallbackInfo<v8::Value>& args);
void private_FillGlyph_w       (const v8::FunctionCallbackInfo<v8::Value>& args);
void private_FillGlyphC_w      (const v8::FunctionCallbackInfo<v8::Value>& args);
void private_FillGlyph2_w      (const v8::FunctionCallbackInfo<v8::Value>& args);
void SetIntegerGrid_w          (const v8::FunctionCallbackInfo<v8::Value>& args);
void GetIntegerGrid_w          (const v8::FunctionCallbackInfo<v8::Value>& args);
void DrawStringASCII_w         (const v8::FunctionCallbackInfo<v8::Value>& args);
void DrawStringASCII2_w        (const v8::FunctionCallbackInfo<v8::Value>& args);
void DrawHeaderEdit_w          (const v8::FunctionCallbackInfo<v8::Value>& args);
void DrawFooterEdit_w          (const v8::FunctionCallbackInfo<v8::Value>& args);
void DrawLockParagraph_w       (const v8::FunctionCallbackInfo<v8::Value>& args);
void DrawLockObjectRect_w      (const v8::FunctionCallbackInfo<v8::Value>& args);
void DrawEmptyTableLine_w      (const v8::FunctionCallbackInfo<v8::Value>& args);
void DrawSpellingLine_w        (const v8::FunctionCallbackInfo<v8::Value>& args);
void drawHorLine_w             (const v8::FunctionCallbackInfo<v8::Value>& args);
void drawHorLine2_w            (const v8::FunctionCallbackInfo<v8::Value>& args);
void drawVerLine_w             (const v8::FunctionCallbackInfo<v8::Value>& args);
void drawHorLineExt_w          (const v8::FunctionCallbackInfo<v8::Value>& args);
void rect_w                    (const v8::FunctionCallbackInfo<v8::Value>& args);
void TableRect_w               (const v8::FunctionCallbackInfo<v8::Value>& args);
void AddClipRect_w             (const v8::FunctionCallbackInfo<v8::Value>& args);
void RemoveClipRect_w          (const v8::FunctionCallbackInfo<v8::Value>& args);
void SetClip_w                 (const v8::FunctionCallbackInfo<v8::Value>& args);
void RemoveClip_w              (const v8::FunctionCallbackInfo<v8::Value>& args);
void drawCollaborativeChanges_w(const v8::FunctionCallbackInfo<v8::Value>& args);
void drawMailMergeField_w      (const v8::FunctionCallbackInfo<v8::Value>& args);
void drawSearchResult_w        (const v8::FunctionCallbackInfo<v8::Value>& args);
void drawFlowAnchor_w          (const v8::FunctionCallbackInfo<v8::Value>& args);
void SavePen_w                 (const v8::FunctionCallbackInfo<v8::Value>& args);
void RestorePen_w              (const v8::FunctionCallbackInfo<v8::Value>& args);
void SaveBrush_w               (const v8::FunctionCallbackInfo<v8::Value>& args);
void RestoreBrush_w            (const v8::FunctionCallbackInfo<v8::Value>& args);
void SavePenBrush_w            (const v8::FunctionCallbackInfo<v8::Value>& args);
void RestorePenBrush_w         (const v8::FunctionCallbackInfo<v8::Value>& args);
void SaveGrState_w             (const v8::FunctionCallbackInfo<v8::Value>& args);
void RestoreGrState_w          (const v8::FunctionCallbackInfo<v8::Value>& args);
void StartClipPath_w           (const v8::FunctionCallbackInfo<v8::Value>& args);
void EndClipPath_w             (const v8::FunctionCallbackInfo<v8::Value>& args);
void StartCheckTableDraw_w     (const v8::FunctionCallbackInfo<v8::Value>& args);
void EndCheckTableDraw_w       (const v8::FunctionCallbackInfo<v8::Value>& args);
void SetTextClipRect_w         (const v8::FunctionCallbackInfo<v8::Value>& args);
void AddSmartRect_w            (const v8::FunctionCallbackInfo<v8::Value>& args);
void CheckUseFonts2_w          (const v8::FunctionCallbackInfo<v8::Value>& args);
void UncheckUseFonts2_w        (const v8::FunctionCallbackInfo<v8::Value>& args);
void Drawing_StartCheckBounds_w(const v8::FunctionCallbackInfo<v8::Value>& args);
void Drawing_EndCheckBounds_w  (const v8::FunctionCallbackInfo<v8::Value>& args);
void DrawPresentationComment_w (const v8::FunctionCallbackInfo<v8::Value>& args);
void DrawPolygon_w             (const v8::FunctionCallbackInfo<v8::Value>& args);
void DrawFootnoteRect_w        (const v8::FunctionCallbackInfo<v8::Value>& args);

void m_oContext_get_w                (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_dWidthMM_get_w                (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_dHeightMM_get_w               (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_lWidthPix_get_w               (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_lHeightPix_get_w              (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_dDpiX_get_w                   (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_dDpiY_get_w                   (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_bIsBreak_get_w                (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_oPen_get_w                    (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_bPenColorInit_get_w           (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_oBrush_get_w                  (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_bBrushColorInit_get_w         (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_oFontManager_get_w            (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_oCoordTransform_get_w         (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_oBaseTransform_get_w          (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_oTransform_get_w              (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_oFullTransform_get_w          (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_oInvertFullTransform_get_w    (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void ArrayPoints_get_w               (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_oCurFont_get_w                (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_oTextPr_get_w                 (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_oGrFonts_get_w                (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_oLastFont_get_w               (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void LastFontOriginInfo_get_w        (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_bIntegerGrid_get_w            (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void ClipManager_get_w               (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void TextureFillTransformScaleX_get_w(v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void TextureFillTransformScaleY_get_w(v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void IsThumbnail_get_w               (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void IsDemonstrationMode_get_w       (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void GrState_get_w                   (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void globalAlpha_get_w               (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void TextClipRect_get_w              (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void IsClipContext_get_w             (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void IsUseFonts2_get_w               (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_oFontManager2_get_w           (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void m_oLastFont2_get_w              (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void ClearMode_get_w                 (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void IsRetina_get_w                  (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);
void dash_no_smart_get_w             (v8::Local<v8::String> _name, const v8::PropertyCallbackInfo<v8::Value>& info);

void m_oContext_set_w                (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_dWidthMM_set_w                (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_dHeightMM_set_w               (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_lWidthPix_set_w               (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_lHeightPix_set_w              (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_dDpiX_set_w                   (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_dDpiY_set_w                   (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_bIsBreak_set_w                (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_oPen_set_w                    (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_bPenColorInit_set_w           (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_oBrush_set_w                  (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_bBrushColorInit_set_w         (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_oFontManager_set_w            (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_oCoordTransform_set_w         (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_oBaseTransform_set_w          (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_oTransform_set_w              (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_oFullTransform_set_w          (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_oInvertFullTransform_set_w    (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void ArrayPoints_set_w               (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_oCurFont_set_w                (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_oTextPr_set_w                 (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_oGrFonts_set_w                (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_oLastFont_set_w               (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void LastFontOriginInfo_set_w        (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_bIntegerGrid_set_w            (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void ClipManager_set_w               (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void TextureFillTransformScaleX_set_w(v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void TextureFillTransformScaleY_set_w(v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void IsThumbnail_set_w               (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void IsDemonstrationMode_set_w       (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void GrState_set_w                   (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void globalAlpha_set_w               (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void TextClipRect_set_w              (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void IsClipContext_set_w             (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void IsUseFonts2_set_w               (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_oFontManager2_set_w           (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void m_oLastFont2_set_w              (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void ClearMode_set_w                 (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void IsRetina_set_w                  (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);
void dash_no_smart_set_w             (v8::Local<v8::String> _name, v8::Local<v8::Value> value, const v8::PropertyCallbackInfo<void>& info);

v8::Handle<v8::ObjectTemplate> CreateGraphicsTemplate(v8::Isolate* isolate);
void CreateGraphics(const v8::FunctionCallbackInfo<v8::Value>& args);
