/*
 * (c) Copyright Ascensio System SIA 2010-2023
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation. In accordance with
 * Section 7(a) of the GNU AGPL its Section 15 shall be amended to the effect
 * that Ascensio System SIA expressly excludes the warranty of non-infringement
 * of any third-party rights.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For
 * details, see the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA at 20A-6 Ernesta Birznieka-Upish
 * street, Riga, Latvia, EU, LV-1050.
 *
 * The  interactive user interfaces in modified source and object code versions
 * of the Program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU AGPL version 3.
 *
 * Pursuant to Section 7(b) of the License you must retain the original Product
 * logo when distributing the program. Pursuant to Section 7(e) we decline to
 * grant you any rights under trademark law for use of our trademarks.
 *
 * All the Product's GUI elements, including illustrations and icon sets, as
 * well as technical writing content are licensed under the terms of the
 * Creative Commons Attribution-ShareAlike 4.0 International. See the License
 * terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 */

#include "../CAccentBorderCallout1.cpp"
#include "../CAccentBorderCallout2.cpp"
#include "../CAccentBorderCallout3.cpp"
#include "../CAccentCallout1.cpp"
#include "../CAccentCallout2.cpp"
#include "../CAccentCallout3.cpp"
#include "../CActionButtonBackPrevious.cpp"
#include "../CActionButtonBeginning.cpp"
#include "../CActionButtonBlank.cpp"
#include "../CActionButtonDocument.cpp"
#include "../CActionButtonEnd.cpp"
#include "../CActionButtonForwardNext.cpp"
#include "../CActionButtonHelp.cpp"
#include "../CActionButtonHome.cpp"
#include "../CActionButtonInformation.cpp"
#include "../CActionButtonMovie.cpp"
#include "../CActionButtonReturn.cpp"
#include "../CActionButtonSound.cpp"
#include "../CArc.cpp"
#include "../CBentArrow.cpp"
#include "../CBentConnector2.cpp"
#include "../CBentConnector3.cpp"
#include "../CBentConnector4.cpp"
#include "../CBentConnector5.cpp"
#include "../CBentUpArrow.cpp"
#include "../CBevel.cpp"
#include "../CBlockArc.cpp"
#include "../CBorderCallout1.cpp"
#include "../CBorderCallout2.cpp"
#include "../CBorderCallout3.cpp"
#include "../CBracePair.cpp"
#include "../CBracketPair.cpp"
#include "../CCallout1.cpp"
#include "../CCallout2.cpp"
#include "../CCallout3.cpp"
#include "../CCan.cpp"
#include "../CChartPlus.cpp"
#include "../CChartStar.cpp"
#include "../CChartX.cpp"
#include "../CChevron.cpp"
#include "../CChord.cpp"
#include "../CCircularArrow.cpp"
#include "../CCloud.cpp"
#include "../CCloudCallout.cpp"
#include "../CCorner.cpp"
#include "../CCornerTabs.cpp"
#include "../CCube.cpp"
#include "../CCurvedConnector2.cpp"
#include "../CCurvedConnector3.cpp"
#include "../CCurvedConnector4.cpp"
#include "../CCurvedConnector5.cpp"
#include "../CCurvedDownArrow.cpp"
#include "../CCurvedLeftArrow.cpp"
#include "../CCurvedRightArrow.cpp"
#include "../CCurvedUpArrow.cpp"
#include "../CDecagon.cpp"
#include "../CDiagStripe.cpp"
#include "../CDiamond.cpp"
#include "../CDodecagon.cpp"
#include "../CDonut.cpp"
#include "../CDoubleWave.cpp"
#include "../CDownArrow.cpp"
#include "../CDownArrowCallout.cpp"
#include "../CEllipse.cpp"
#include "../CEllipseRibbon.cpp"
#include "../CEllipseRibbon2.cpp"
#include "../CFlowChartAlternateProcess.cpp"
#include "../CFlowChartCollate.cpp"
#include "../CFlowChartConnector.cpp"
#include "../CFlowChartDecision.cpp"
#include "../CFlowChartDelay.cpp"
#include "../CFlowChartDisplay.cpp"
#include "../CFlowChartDocument.cpp"
#include "../CFlowChartExtract.cpp"
#include "../CFlowChartInputOutput.cpp"
#include "../CFlowChartInternalStorage.cpp"
#include "../CFlowChartMagneticDisk.cpp"
#include "../CFlowChartMagneticDrum.cpp"
#include "../CFlowChartMagneticTape.cpp"
#include "../CFlowChartManualInput.cpp"
#include "../CFlowChartManualOperation.cpp"
#include "../CFlowChartMerge.cpp"
#include "../CFlowChartMultidocument.cpp"
#include "../CFlowChartOfflineStorage.cpp"
#include "../CFlowChartOffpageConnector.cpp"
#include "../CFlowChartOnlineStorage.cpp"
#include "../CFlowChartOr.cpp"
#include "../CFlowChartPredefinedProcess.cpp"
#include "../CFlowChartPreparation.cpp"
#include "../CFlowChartProcess.cpp"
#include "../CFlowChartPunchedCard.cpp"
#include "../CFlowChartPunchedTape.cpp"
#include "../CFlowChartSort.cpp"
#include "../CFlowChartSummingJunction.cpp"
#include "../CFlowChartTerminator.cpp"
#include "../CFoldedCorner.cpp"
#include "../CFrame.cpp"
#include "../CFunnel.cpp"
#include "../CGear6.cpp"
#include "../CGear9.cpp"
#include "../CHalfFrame.cpp"
#include "../CHeart.cpp"
#include "../CHeptagon.cpp"
#include "../CHexagon.cpp"
#include "../CHomePlate.cpp"
#include "../CHorizontalScroll.cpp"
#include "../CIrregularSeal1.cpp"
#include "../CIrregularSeal2.cpp"
#include "../CLeftArrow.cpp"
#include "../CLeftArrowCallout.cpp"
#include "../CLeftBrace.cpp"
#include "../CLeftBracket.cpp"
#include "../CLeftCircularArrow.cpp"
#include "../CLeftRightArrow.cpp"
#include "../CLeftRightArrowCallout.cpp"
#include "../CLeftRightCircularArrow.cpp"
#include "../CLeftRightRibbon.cpp"
#include "../CLeftRightUpArrow.cpp"
#include "../CLeftUpArrow.cpp"
#include "../CLightningBolt.cpp"
#include "../CLine.cpp"
#include "../CLineInv.cpp"
#include "../CMathDivide.cpp"
#include "../CMathEqual.cpp"
#include "../CMathMinus.cpp"
#include "../CMathMultiply.cpp"
#include "../CMathNotEqual.cpp"
#include "../CMathPlus.cpp"
#include "../CMoon.cpp"
#include "../CNonIsoscelesTrapezoid.cpp"
#include "../CNoSmoking.cpp"
#include "../CNotchedRightArrow.cpp"
#include "../COctagon.cpp"
#include "../CParallelogram.cpp"
#include "../CPentagon.cpp"
#include "../CPie.cpp"
#include "../CPieWedge.cpp"
#include "../CPlaque.cpp"
#include "../CPlaqueTabs.cpp"
#include "../CPlus.cpp"
#include "../CQuadArrow.cpp"
#include "../CQuadArrowCallout.cpp"
#include "../CRect.cpp"
#include "../CRibbon.cpp"
#include "../CRibbon2.cpp"
#include "../CRightArrow.cpp"
#include "../CRightArrowCallout.cpp"
#include "../CRightBrace.cpp"
#include "../CRightBracket.cpp"
#include "../CRound1Rect.cpp"
#include "../CRound2DiagRect.cpp"
#include "../CRound2SameRect.cpp"
#include "../CRoundRect.cpp"
#include "../CRtTriangle.cpp"
#include "../CSmileyFace.cpp"
#include "../CSnip1Rect.cpp"
#include "../CSnip2DiagRect.cpp"
#include "../CSnip2SameRect.cpp"
#include "../CSnipRoundRect.cpp"
#include "../CSquareTabs.cpp"
#include "../CStar10.cpp"
#include "../CStar12.cpp"
#include "../CStar16.cpp"
#include "../CStar24.cpp"
#include "../CStar32.cpp"
#include "../CStar4.cpp"
#include "../CStar5.cpp"
#include "../CStar6.cpp"
#include "../CStar7.cpp"
#include "../CStar8.cpp"
#include "../CStraightConnector1.cpp"
#include "../CStripedRightArrow.cpp"
#include "../CSun.cpp"
#include "../CSwooshArrow.cpp"
#include "../CTeardrop.cpp"
#include "../CTextArchDown.cpp"
#include "../CTextArchDownPour.cpp"
#include "../CTextArchUp.cpp"
#include "../CTextArchUpPour.cpp"
#include "../CTextButton.cpp"
#include "../CTextButtonPour.cpp"
#include "../CTextCanDown.cpp"
#include "../CTextCanUp.cpp"
#include "../CTextCascadeDown.cpp"
#include "../CTextCascadeUp.cpp"
#include "../CTextChevron.cpp"
#include "../CTextChevronInverted.cpp"
#include "../CTextCircle.cpp"
#include "../CTextCirclePour.cpp"
#include "../CTextCurveDown.cpp"
#include "../CTextCurveUp.cpp"
#include "../CTextDeflate.cpp"
#include "../CTextDeflateBottom.cpp"
#include "../CTextDeflateInflate.cpp"
#include "../CTextDeflateInflateDeflate.cpp"
#include "../CTextDeflateTop.cpp"
#include "../CTextDoubleWave1.cpp"
#include "../CTextFadeDown.cpp"
#include "../CTextFadeLeft.cpp"
#include "../CTextFadeRight.cpp"
#include "../CTextFadeUp.cpp"
#include "../CTextInflate.cpp"
#include "../CTextInflateBottom.cpp"
#include "../CTextInflateTop.cpp"
#include "../CTextPlain.cpp"
#include "../CTextRingInside.cpp"
#include "../CTextRingOutside.cpp"
#include "../CTextSlantDown.cpp"
#include "../CTextSlantUp.cpp"
#include "../CTextStop.cpp"
#include "../CTextTriangle.cpp"
#include "../CTextTriangleInverted.cpp"
#include "../CTextWave1.cpp"
#include "../CTextWave2.cpp"
#include "../CTextWave4.cpp"
#include "../CTrapezoid.cpp"
#include "../CTriangle.cpp"
#include "../CUpArrow.cpp"
#include "../CUpArrowCallout.cpp"
#include "../CUpDownArrow.cpp"
#include "../CUpDownArrowCallout.cpp"
#include "../CUturnArrow.cpp"
#include "../CVerticalScroll.cpp"
#include "../CWave.cpp"
#include "../CWedgeEllipseCallout.cpp"
#include "../CWedgeRectCallout.cpp"
#include "../CWedgeRoundRectCallout.cpp"
