#pragma once

#include "office_body.h"
#include "office_document.h"
#include "office_elements.h"
#include "office_text.h"
#include "office_spreadsheet.h"
#include "office_presentation.h"
#include "office_scripts.h"
#include "office_settings.h"
#include "paragraph_elements.h"
#include "office_binary_data.h"

#include "text_elements.h"
#include "list.h"
#include "style_text_properties.h"
#include "style_paragraph_properties.h"
#include "style_presentation.h"
#include "styles.h"
#include "font_face.h"
#include "table_calculation_settings.h"
#include "number_style.h"
