#pragma once

#include "./oldAutoShapes/accentbordercallout90type.h"
#include "./oldAutoShapes/accentbordercallout1type.h"
#include "./oldAutoShapes/AccentBorderCallout2Type.h"
#include "./oldAutoShapes/accentbordercallout3type.h"

#include "./oldAutoShapes/AccentCallout90Type.h"
#include "./oldAutoShapes/AccentCallout1Type.h"
#include "./oldAutoShapes/AccentCallout2Type.h"
#include "./oldAutoShapes/AccentCallout3Type.h"

#include "./oldAutoShapes/BorderCallout90Type.h"
#include "./oldAutoShapes/BorderCallout1Type.h"
#include "./oldAutoShapes/BorderCallout2Type.h"
#include "./oldAutoShapes/BorderCallout3Type.h"

#include "./oldAutoShapes/Callout90Type.h"
#include "./oldAutoShapes/Callout1Type.h"
#include "./oldAutoShapes/Callout2Type.h"
#include "./oldAutoShapes/Callout3Type.h"

#include "./oldAutoShapes/BentConnector.h"
#include "./oldAutoShapes/CurvedConnector.h"

#include "./oldAutoShapes/ActionButtonBlank.h"
#include "./oldAutoShapes/ActionButtonHome.h"
#include "./oldAutoShapes/ActionButtonHelp.h"
#include "./oldAutoShapes/ActionButtonInfo.h"
#include "./oldAutoShapes/ActionButtonBack.h"
#include "./oldAutoShapes/ActionButtonNext.h"
#include "./oldAutoShapes/ActionButtonBeginning.h"
#include "./oldAutoShapes/ActionButtonEnd.h"
#include "./oldAutoShapes/ActionButtonReturn.h"
#include "./oldAutoShapes/ActionButtonDocument.h"
#include "./oldAutoShapes/ActionButtonSound.h"
#include "./oldAutoShapes/ActionButtonMovie.h"

#include "./oldAutoShapes/arctype.h"
#include "./oldAutoShapes/LineType.h"

#include "./oldAutoShapes/BentArrowType.h"
#include "./oldAutoShapes/BentUpArrowType.h"
#include "./oldAutoShapes/BevelType.h"
#include "./oldAutoShapes/BlockArcType.h"
#include "./oldAutoShapes/BracePairType.h"
#include "./oldAutoShapes/BracketPairType.h"

#include "./oldAutoShapes/CanType.h"
#include "./oldAutoShapes/ChevronType.h"
#include "./oldAutoShapes/CircularArrowType.h"
#include "./oldAutoShapes/CloudCalloutType.h"
#include "./oldAutoShapes/CubeType.h"
#include "./oldAutoShapes/CurvedDownArrowType.h"
#include "./oldAutoShapes/CurvedLeftArrowType.h"
#include "./oldAutoShapes/CurvedRightArrowType.h"
#include "./oldAutoShapes/CurvedUpArrowType.h"

#include "./oldAutoShapes/DiamondType.h"
#include "./oldAutoShapes/DonutType.h"
#include "./oldAutoShapes/DownArrowCalloutType.h"
#include "./oldAutoShapes/DownArrowType.h"

#include "./oldAutoShapes/EllipseType.h"
#include "./oldAutoShapes/EllipseRibbon2Type.h"
#include "./oldAutoShapes/EllipseRibbonType.h"

#include "./oldAutoShapes/FlowChartAlternateProcessType.h"
#include "./oldAutoShapes/FlowChartCollateType.h"
#include "./oldAutoShapes/FlowChartConnectorType.h"
#include "./oldAutoShapes/FlowChartDecisionType.h"
#include "./oldAutoShapes/FlowChartDelayType.h"
#include "./oldAutoShapes/FlowChartDisplayType.h"
#include "./oldAutoShapes/FlowChartDocumentType.h"
#include "./oldAutoShapes/FlowChartExtractType.h"
#include "./oldAutoShapes/FlowChartInputOutputType.h"
#include "./oldAutoShapes/FlowChartInternalStorageType.h"
#include "./oldAutoShapes/FlowChartMagneticDiskType.h"
#include "./oldAutoShapes/FlowChartMagneticDrumType.h"
#include "./oldAutoShapes/FlowChartMagneticTapeType.h"
#include "./oldAutoShapes/FlowChartManualInputType.h"
#include "./oldAutoShapes/FlowChartManualOperationType.h"
#include "./oldAutoShapes/FlowChartMergeType.h"
#include "./oldAutoShapes/FlowChartMultidocumentType.h"
#include "./oldAutoShapes/FlowChartOffpageConnectorType.h"
#include "./oldAutoShapes/FlowChartOnlineStorageType.h"
#include "./oldAutoShapes/FlowChartOrType.h"
#include "./oldAutoShapes/FlowChartPredefinedProcessType.h"
#include "./oldAutoShapes/FlowChartPreparationType.h"
#include "./oldAutoShapes/FlowChartProcessType.h"
#include "./oldAutoShapes/FlowChartPunchedCardType.h"
#include "./oldAutoShapes/FlowChartPunchedTapeType.h"
#include "./oldAutoShapes/FlowChartSortType.h"
#include "./oldAutoShapes/FlowChartSummingJunctionType.h"
#include "./oldAutoShapes/FlowChartTerminatorType.h"
#include "./oldAutoShapes/FoldedCornerType.h"

#include "./oldAutoShapes/HeartType.h"
#include "./oldAutoShapes/HexagonType.h"
#include "./oldAutoShapes/HomePlateType.h"

#include "./oldAutoShapes/IrregularSealOneType.h"
#include "./oldAutoShapes/IrregularSealTwo.h"
#include "./oldAutoShapes/IsoscelesTriangleType.h"

#include "./oldAutoShapes/LeftArrowCalloutType.h"
#include "./oldAutoShapes/LeftArrowType.h"
#include "./oldAutoShapes/LeftBraceType.h"
#include "./oldAutoShapes/LeftBracketType.h"
#include "./oldAutoShapes/LeftRightArrowCalloutType.h"
#include "./oldAutoShapes/LeftRightArrowType.h"
#include "./oldAutoShapes/LeftRightUpArrow.h"
#include "./oldAutoShapes/LeftUpArrowType.h"
#include "./oldAutoShapes/LightningBoltType.h"

#include "./oldAutoShapes/MoonType.h"

#include "./oldAutoShapes/NoSmokingType.h"
#include "./oldAutoShapes/NotchedRightArrowType.h"

#include "./oldAutoShapes/OctagonType.h"

#include "./oldAutoShapes/ParallelogramType.h"
#include "./oldAutoShapes/PentagonType.h"
#include "./oldAutoShapes/PlaqueType.h"
#include "./oldAutoShapes/PlusType.h"

#include "./oldAutoShapes/QuadArrowCalloutType.h"
#include "./oldAutoShapes/QuadArrowType.h"

#include "./oldAutoShapes/RectangleType.h"
#include "./oldAutoShapes/RibbonDownType.h"
#include "./oldAutoShapes/RibbonUpType.h"
#include "./oldAutoShapes/RightArrowCalloutType.h"
#include "./oldAutoShapes/RightArrowType.h"
#include "./oldAutoShapes/RightBracetype.h"
#include "./oldAutoShapes/RightBracketType.h"
#include "./oldAutoShapes/RightTriangleType.h"
#include "./oldAutoShapes/RoundedRectangleType.h"

#include "./oldAutoShapes/Seal16Type.h"
#include "./oldAutoShapes/Seal24Type.h"
#include "./oldAutoShapes/Seal32Type.h"
#include "./oldAutoShapes/Seal4Type.h"
#include "./oldAutoShapes/Seal8Type.h"
#include "./oldAutoShapes/SmileyFaceType.h"
#include "./oldAutoShapes/Startype.h"
#include "./oldAutoShapes/StraightConnectorType.h"
#include "./oldAutoShapes/StripedRightArrowType.h"
#include "./oldAutoShapes/SunType.h"

#include "./oldAutoShapes/TextboxType.h"
#include "./oldAutoShapes/TrapezoidType.h"

#include "./oldAutoShapes/UpArrowCalloutType.h"
#include "./oldAutoShapes/UpArrowType.h"
#include "./oldAutoShapes/UpDownArrowCalloutType.h"
#include "./oldAutoShapes/UpDownArrowType.h"
#include "./oldAutoShapes/UturnArrowType.h"

#include "./oldAutoShapes/VerticalScrollType.h"
#include "./oldAutoShapes/HorisontalScrollType.h"

#include "./oldAutoShapes/WedgeEllipseCalloutType.h"
#include "./oldAutoShapes/WedgeRectCalloutType.h"
#include "./oldAutoShapes/WedgeRoundedRectCalloutType.h"

#include "./oldAutoShapes/WaveType.h"
#include "./oldAutoShapes/WaveDoubleType.h"
