#include "PrstClrVal.h"

namespace PPTX
{
	namespace Limit
	{
		PrstClrVal::PrstClrVal()
		{
			add("aliceBlue"); // (Alice Blue Preset Color)  Specifies a color with RGB value (240,248,255) 
			add("antiqueWhite"); // (Antique White Preset Color)  Specifies a color with RGB value (250,235,215) 
			add("aqua"); // (Aqua Preset Color)  Specifies a color with RGB value (0,255,255) 
			add("aquamarine"); // (Aquamarine Preset Color)  Specifies a color with RGB value (127,255,212) 
			add("azure"); // (Azure Preset Color)  Specifies a color with RGB value (240,255,255) 
			add("beige"); // (Beige Preset Color)  Specifies a color with RGB value (245,245,220) 
			add("bisque"); // (Bisque Preset Color)  Specifies a color with RGB value (255,228,196) 
			add("black"); // (Black Preset Color)  Specifies a color with RGB value (0,0,0) 
			add("blanchedAlmond"); // (Blanched Almond Preset Color)  Specifies a color with RGB value (255,235,205) 
			add("blue"); // (Blue Preset Color)  Specifies a color with RGB value (0,0,255) 
			add("blueViolet"); // (Blue Violet Preset Color)  Specifies a color with RGB value (138,43,226) 
			add("brown"); // (Brown Preset Color)  Specifies a color with RGB value (165,42,42) 
			add("burlyWood"); // (Burly Wood Preset Color)  Specifies a color with RGB value (222,184,135) 
			add("cadetBlue"); // (Cadet Blue Preset Color)  Specifies a color with RGB value (95,158,160) 
			add("chartreuse"); // (Chartreuse Preset Color)  Specifies a color with RGB value (127,255,0) 
			add("chocolate"); // (Chocolate Preset Color)  Specifies a color with RGB value (210,105,30) 
			add("coral"); // (Coral Preset Color)  Specifies a color with RGB value (255,127,80) 
			add("cornflowerBlue"); // (Cornflower Blue Preset Color)  Specifies a color with RGB value (100,149,237) 
			add("cornsilk"); // (Cornsilk Preset Color)  Specifies a color with RGB value (255,248,220) 
			add("crimson"); // (Crimson Preset Color)  Specifies a color with RGB value (220,20,60) 
			add("cyan"); // (Cyan Preset Color)  Specifies a color with RGB value (0,255,255) 
			add("darkBlue"); // (Dark Blue Preset Color)  Specifies a color with RGB value (0,0,139) 
			add("darkCyan"); // (Dark Cyan Preset Color)  Specifies a color with RGB value (0,139,139) 
			add("darkGoldenrod"); // (Dark Goldenrod Preset Color)  Specifies a color with RGB value (184,134,11) 
			add("darkGray"); // (Dark Gray Preset Color)  Specifies a color with RGB value (169,169,169) 
			add("darkGreen"); // (Dark Green Preset Color)  Specifies a color with RGB value (0,100,0) 
			add("darkGrey"); // (Dark Gray Preset Color)  Specifies a color with RGB value (169,169,169) 
			add("darkKhaki"); // (Dark Khaki Preset Color)  Specifies a color with RGB value (189,183,107) 
			add("darkMagenta"); // (Dark Magenta Preset Color)  Specifies a color with RGB value (139,0,139) 
			add("darkOliveGreen"); // (Dark Olive Green Preset Color)  Specifies a color with RGB value (85,107,47) 
			add("darkOrange"); // (Dark Orange Preset Color)  Specifies a color with RGB value (255,140,0) 
			add("darkOrchid"); // (Dark Orchid Preset Color)  Specifies a color with RGB value (153,50,204) 
			add("darkRed"); // (Dark Red Preset Color)  Specifies a color with RGB value (139,0,0) 
			add("darkSalmon"); // (Dark Salmon Preset Color)  Specifies a color with RGB value (233,150,122) 
			add("darkSeaGreen"); // (Dark Sea Green Preset Color)  Specifies a color with RGB value (143,188,143) 
			add("darkSlateBlue"); // (Dark Slate Blue Preset Color)  Specifies a color with RGB value (72,61,139) 
			add("darkSlateGray"); // (Dark Slate Gray Preset Color)  Specifies a color with RGB value (47,79,79) 
			add("darkSlateGrey"); // (Dark Slate Gray Preset Color)  Specifies a color with RGB value (47,79,79) 
			add("darkTurquoise"); // (Dark Turquoise Preset Color)  Specifies a color with RGB value (0,206,209) 
			add("darkViolet"); // (Dark Violet Preset Color)  Specifies a color with RGB value (148,0,211) 
			add("deepPink"); // (Deep Pink Preset Color)  Specifies a color with RGB value (255,20,147) 
			add("deepSkyBlue"); // (Deep Sky Blue Preset Color)  Specifies a color with RGB value (0,191,255) 
			add("dimGray"); // (Dim Gray Preset Color)  Specifies a color with RGB value (105,105,105) 
			add("dimGrey"); // (Dim Gray Preset Color)  Specifies a color with RGB value (105,105,105) 
			add("dkBlue"); // (Dark Blue Preset Color)  Specifies a color with RGB value (0,0,139) 
			add("dkCyan"); // (Dark Cyan Preset Color)  Specifies a color with RGB value (0,139,139) 
			add("dkGoldenrod"); // (Dark Goldenrod Preset Color)  Specifies a color with RGB value (184,134,11) 
			add("dkGray"); // (Dark Gray Preset Color)  Specifies a color with RGB value (169,169,169) 
			add("dkGreen"); // (Dark Green Preset Color)  Specifies a color with RGB value (0,100,0) 
			add("dkGrey"); // (Dark Gray Preset Color)  Specifies a color with RGB value (169,169,169) 
			add("dkKhaki"); // (Dark Khaki Preset Color)  Specifies a color with RGB value (189,183,107) 
			add("dkMagenta"); // (Dark Magenta Preset Color)  Specifies a color with RGB value (139,0,139) 
			add("dkOliveGreen"); // (Dark Olive Green Preset Color)  Specifies a color with RGB value (85,107,47) 
			add("dkOrange"); // (Dark Orange Preset Color)  Specifies a color with RGB value (255,140,0) 
			add("dkOrchid"); // (Dark Orchid Preset Color)  Specifies a color with RGB value (153,50,204) 
			add("dkRed"); // (Dark Red Preset Color)  Specifies a color with RGB value (139,0,0) 
			add("dkSalmon"); // (Dark Salmon Preset Color)  Specifies a color with RGB value (233,150,122) 
			add("dkSeaGreen"); // (Dark Sea Green Preset Color)  Specifies a color with RGB value (143,188,139) 
			add("dkSlateBlue"); // (Dark Slate Blue Preset Color)  Specifies a color with RGB value (72,61,139) 
			add("dkSlateGray"); // (Dark Slate Gray Preset Color)  Specifies a color with RGB value (47,79,79) 
			add("dkSlateGrey"); // (Dark Slate Gray Preset Color)  Specifies a color with RGB value (47,79,79) 
			add("dkTurquoise"); // (Dark Turquoise Preset Color)  Specifies a color with RGB value (0,206,209) 
			add("dkViolet"); // (Dark Violet Preset Color)  Specifies a color with RGB value (148,0,211) 
			add("dodgerBlue"); // (Dodger Blue Preset Color)  Specifies a color with RGB value (30,144,255) 
			add("firebrick"); // (Firebrick Preset Color)  Specifies a color with RGB value (178,34,34) 
			add("floralWhite"); // (Floral White Preset Color)  Specifies a color with RGB value (255,250,240) 
			add("forestGreen"); // (Forest Green Preset Color)  Specifies a color with RGB value (34,139,34) 
			add("fuchsia"); // (Fuchsia Preset Color)  Specifies a color with RGB value (255,0,255) 
			add("gainsboro"); // (Gainsboro Preset Color)  Specifies a color with RGB value (220,220,220) 
			add("ghostWhite"); // (Ghost White Preset Color)  Specifies a color with RGB value (248,248,255) 
			add("gold"); // (Gold Preset Color)  Specifies a color with RGB value (255,215,0) 
			add("goldenrod"); // (Goldenrod Preset Color)  Specifies a color with RGB value (218,165,32) 
			add("gray"); // (Gray Preset Color)  Specifies a color with RGB value (128,128,128) 
			add("green"); // (Green Preset Color)  Specifies a color with RGB value (0,128,0) 
			add("greenYellow"); // (Green Yellow Preset Color)  Specifies a color with RGB value (173,255,47) 
			add("grey"); // (Gray Preset Color)  Specifies a color with RGB value (128,128,128) 
			add("honeydew"); // (Honeydew Preset Color)  Specifies a color with RGB value (240,255,240) 
			add("hotPink"); // (Hot Pink Preset Color)  Specifies a color with RGB value (255,105,180) 
			add("indianRed"); // (Indian Red Preset Color)  Specifies a color with RGB value (205,92,92) 
			add("indigo"); // (Indigo Preset Color)  Specifies a color with RGB value (75,0,130) 
			add("ivory"); // (Ivory Preset Color)  Specifies a color with RGB value (255,255,240) 
			add("khaki"); // (Khaki Preset Color)  Specifies a color with RGB value (240,230,140) 
			add("lavender"); // (Lavender Preset Color)  Specifies a color with RGB value (230,230,250) 
			add("lavenderBlush"); // (Lavender Blush Preset Color)  Specifies a color with RGB value (255,240,245) 
			add("lawnGreen"); // (Lawn Green Preset Color)  Specifies a color with RGB value (124,252,0) 
			add("lemonChiffon"); // (Lemon Chiffon Preset Color)  Specifies a color with RGB value (255,250,205) 
			add("lightBlue"); // (Light Blue Preset Color)  Specifies a color with RGB value (173,216,230) 
			add("lightCoral"); // (Light Coral Preset Color)  Specifies a color with RGB value (240,128,128) 
			add("lightCyan"); // (Light Cyan Preset Color)  Specifies a color with RGB value (224,255,255) 
			add("lightGoldenrodYellow"); // (Light Goldenrod Color) Yellow Preset  Specifies a color with RGB value (250,250,210) 
			add("lightGray"); // (Light Gray Preset Color)  Specifies a color with RGB value (211,211,211) 
			add("lightGreen"); // (Light Green Preset Color)  Specifies a color with RGB value (144,238,144) 
			add("lightGrey"); // (Light Gray Preset Color)  Specifies a color with RGB value (211,211,211) 
			add("lightPink"); // (Light Pink Preset Color)  Specifies a color with RGB value (255,182,193) 
			add("lightSalmon"); // (Light Salmon Preset Color)  Specifies a color with RGB value (255,160,122) 
			add("lightSeaGreen"); // (Light Sea Green Preset Color)  Specifies a color with RGB value (32,178,170) 
			add("lightSkyBlue"); // (Light Sky Blue Preset Color)  Specifies a color with RGB value (135,206,250) 
			add("lightSlateGray"); // (Light Slate Gray Preset Color)  Specifies a color with RGB value (119,136,153) 
			add("lightSlateGrey"); // (Light Slate Gray Preset Color)  Specifies a color with RGB value (119,136,153) 
			add("lightSteelBlue"); // (Light Steel Blue Preset Color)  Specifies a color with RGB value (176,196,222) 
			add("lightYellow"); // (Light Yellow Preset Color)  Specifies a color with RGB value (255,255,224) 
			add("lime"); // (Lime Preset Color)  Specifies a color with RGB value (0,255,0) 
			add("limeGreen"); // (Lime Green Preset Color)  Specifies a color with RGB value (50,205,50) 
			add("linen"); // (Linen Preset Color)  Specifies a color with RGB value (250,240,230) 
			add("ltBlue"); // (Light Blue Preset Color)  Specifies a color with RGB value (173,216,230) 
			add("ltCoral"); // (Light Coral Preset Color)  Specifies a color with RGB value (240,128,128) 
			add("ltCyan"); // (Light Cyan Preset Color)  Specifies a color with RGB value (224,255,255) 
			add("ltGoldenrodYellow"); // (Light Goldenrod Color) Yellow Preset  Specifies a color with RGB value (250,250,120) 
			add("ltGray"); // (Light Gray Preset Color)  Specifies a color with RGB value (211,211,211) 
			add("ltGreen"); // (Light Green Preset Color)  Specifies a color with RGB value (144,238,144) 
			add("ltGrey"); // (Light Gray Preset Color)  Specifies a color with RGB value (211,211,211) 
			add("ltPink"); // (Light Pink Preset Color)  Specifies a color with RGB value (255,182,193) 
			add("ltSalmon"); // (Light Salmon Preset Color)  Specifies a color with RGB value (255,160,122) 
			add("ltSeaGreen"); // (Light Sea Green Preset Color)  Specifies a color with RGB value (32,178,170) 
			add("ltSkyBlue"); // (Light Sky Blue Preset Color)  Specifies a color with RGB value (135,206,250) 
			add("ltSlateGray"); // (Light Slate Gray Preset Color)  Specifies a color with RGB value (119,136,153) 
			add("ltSlateGrey"); // (Light Slate Gray Preset Color)  Specifies a color with RGB value (119,136,153) 
			add("ltSteelBlue"); // (Light Steel Blue Preset Color)  Specifies a color with RGB value (176,196,222) 
			add("ltYellow"); // (Light Yellow Preset Color)  Specifies a color with RGB value (255,255,224) 
			add("magenta"); // (Magenta Preset Color)  Specifies a color with RGB value (255,0,255) 
			add("maroon"); // (Maroon Preset Color)  Specifies a color with RGB value (128,0,0) 
			add("medAquamarine"); // (Medium Aquamarine Preset Color)  Specifies a color with RGB value (102,205,170) 
			add("medBlue"); // (Medium Blue Preset Color)  Specifies a color with RGB value (0,0,205) 
			add("mediumAquamarine"); // (Medium Aquamarine Color) Preset  Specifies a color with RGB value (102,205,170) 
			add("mediumBlue"); // (Medium Blue Preset Color)  Specifies a color with RGB value (0,0,205) 
			add("mediumOrchid"); // (Medium Orchid Preset Color)  Specifies a color with RGB value (186,85,211) 
			add("mediumPurple"); // (Medium Purple Preset Color)  Specifies a color with RGB value (147,112,219) 
			add("mediumSeaGreen"); // (Medium Sea Green Preset Color)  Specifies a color with RGB value (60,179,113) 
			add("mediumSlateBlue"); // (Medium Slate Blue Preset Color)  Specifies a color with RGB value (123,104,238) 
			add("mediumSpringGreen"); // (Medium Spring Color) Green Preset  Specifies a color with RGB value (0,250,154) 
			add("mediumTurquoise"); // (Medium Turquoise Preset Color)  Specifies a color with RGB value (72,209,204) 
			add("mediumVioletRed"); // (Medium Violet Red Preset Color)  Specifies a color with RGB value (199,21,133) 
			add("medOrchid"); // (Medium Orchid Preset Color)  Specifies a color with RGB value (186,85,211) 
			add("medPurple"); // (Medium Purple Preset Color)  Specifies a color with RGB value (147,112,219) 
			add("medSeaGreen"); // (Medium Sea Green Preset Color)  Specifies a color with RGB value (60,179,113) 
			add("medSlateBlue"); // (Medium Slate Blue Preset Color)  Specifies a color with RGB value (123,104,238) 
			add("medSpringGreen"); // (Medium Spring Green Preset Color)  Specifies a color with RGB value (0,250,154) 
			add("medTurquoise"); // (Medium Turquoise Preset Color)  Specifies a color with RGB value (72,209,204) 
			add("medVioletRed"); // (Medium Violet Red Preset Color)  Specifies a color with RGB value (199,21,133) 
			add("midnightBlue"); // (Midnight Blue Preset Color)  Specifies a color with RGB value (25,25,112) 
			add("mintCream"); // (Mint Cream Preset Color)  Specifies a color with RGB value (245,255,250) 
			add("mistyRose"); // (Misty Rose Preset Color)  Specifies a color with RGB value (255,228,225) 
			add("moccasin"); // (Moccasin Preset Color)  Specifies a color with RGB value (255,228,181) 
			add("navajoWhite"); // (Navajo White Preset Color)  Specifies a color with RGB value (255,222,173) 
			add("navy"); // (Navy Preset Color)  Specifies a color with RGB value (0,0,128) 
			add("oldLace"); // (Old Lace Preset Color)  Specifies a color with RGB value (253,245,230) 
			add("olive"); // (Olive Preset Color)  Specifies a color with RGB value (128,128,0) 
			add("oliveDrab"); // (Olive Drab Preset Color)  Specifies a color with RGB value (107,142,35) 
			add("orange"); // (Orange Preset Color)  Specifies a color with RGB value (255,165,0) 
			add("orangeRed"); // (Orange Red Preset Color)  Specifies a color with RGB value (255,69,0) 
			add("orchid"); // (Orchid Preset Color)  Specifies a color with RGB value (218,112,214) 
			add("paleGoldenrod"); // (Pale Goldenrod Preset Color)  Specifies a color with RGB value (238,232,170) 
			add("paleGreen"); // (Pale Green Preset Color)  Specifies a color with RGB value (152,251,152) 
			add("paleTurquoise"); // (Pale Turquoise Preset Color)  Specifies a color with RGB value (175,238,238) 
			add("paleVioletRed"); // (Pale Violet Red Preset Color)  Specifies a color with RGB value (219,112,147) 
			add("papayaWhip"); // (Papaya Whip Preset Color)  Specifies a color with RGB value (255,239,213) 
			add("peachPuff"); // (Peach Puff Preset Color)  Specifies a color with RGB value (255,218,185) 
			add("peru"); // (Peru Preset Color)  Specifies a color with RGB value (205,133,63) 
			add("pink"); // (Pink Preset Color)  Specifies a color with RGB value (255,192,203) 
			add("plum"); // (Plum Preset Color)  Specifies a color with RGB value (221,160,221) 
			add("powderBlue"); // (Powder Blue Preset Color)  Specifies a color with RGB value (176,224,230) 
			add("purple"); // (Purple Preset Color)  Specifies a color with RGB value (128,0,128) 
			add("red"); // (Red Preset Color)  Specifies a color with RGB value (255,0,0) 
			add("rosyBrown"); // (Rosy Brown Preset Color)  Specifies a color with RGB value (188,143,143) 
			add("royalBlue"); // (Royal Blue Preset Color)  Specifies a color with RGB value (65,105,225) 
			add("saddleBrown"); // (Saddle Brown Preset Color)  Specifies a color with RGB value (139,69,19) 
			add("salmon"); // (Salmon Preset Color)  Specifies a color with RGB value (250,128,114) 
			add("sandyBrown"); // (Sandy Brown Preset Color)  Specifies a color with RGB value (244,164,96) 
			add("seaGreen"); // (Sea Green Preset Color)  Specifies a color with RGB value (46,139,87) 
			add("seaShell"); // (Sea Shell Preset Color)  Specifies a color with RGB value (255,245,238) 
			add("sienna"); // (Sienna Preset Color)  Specifies a color with RGB value (160,82,45) 
			add("silver"); // (Silver Preset Color)  Specifies a color with RGB value (192,192,192) 
			add("skyBlue"); // (Sky Blue Preset Color)  Specifies a color with RGB value (135,206,235) 
			add("slateBlue"); // (Slate Blue Preset Color)  Specifies a color with RGB value (106,90,205) 
			add("slateGray"); // (Slate Gray Preset Color)  Specifies a color with RGB value (112,128,144) 
			add("slateGrey"); // (Slate Gray Preset Color)  Specifies a color with RGB value (112,128,144) 
			add("snow"); // (Snow Preset Color)  Specifies a color with RGB value (255,250,250) 
			add("springGreen"); // (Spring Green Preset Color)  Specifies a color with RGB value (0,255,127) 
			add("steelBlue"); // (Steel Blue Preset Color)  Specifies a color with RGB value (70,130,180) 
			add("tan"); // (Tan Preset Color)  Specifies a color with RGB value (210,180,140) 
			add("teal"); // (Teal Preset Color)  Specifies a color with RGB value (0,128,128) 
			add("thistle"); // (Thistle Preset Color)  Specifies a color with RGB value (216,191,216) 
			add("tomato"); // (Tomato Preset Color)  Specifies a color with RGB value (255,99,71) 
			add("turquoise"); // (Turquoise Preset Color)  Specifies a color with RGB value (64,224,208) 
			add("violet"); // (Violet Preset Color)  Specifies a color with RGB value (238,130,238) 
			add("wheat"); // (Wheat Preset Color)  Specifies a color with RGB value (245,222,179) 
			add("white"); // (White Preset Color)  Specifies a color with RGB value (255,255,255) 
			add("whiteSmoke"); // (White Smoke Preset Color)  Specifies a color with RGB value (245,245,245) 
			add("yellow"); // (Yellow Preset Color)  Specifies a color with RGB value (255,255,0) 
			add("yellowGreen"); // (Yellow Green Preset Color)  Specifies a color with RGB value (154,205,50) 
 		}

		const std::string PrstClrVal::no_find() const
		{
			return "black";
		}
	} // namespace Limit
} // namespace PPTX